### ISSUE TITLE
bgp_Gr_helper test suite fails in Latest Sonic Code

### ISSUE THREAD

**Issue by DhinakaranDayalan** [Azure/sonic-mgmt#1148]
**Description**

**Steps to reproduce the issue:**
1. Execute the bgp_gr_helper test suite on t1-lag 32 configuration.
2. Test suite fails with the error mentioned in description
3.

**Describe the results you received:**

In the bgp_gr_helper.yml in the Following Code sequence fails

====================
    # When RIBD up and send bgp open message it will set F bit to 1. Which means that during restart
    # all routes were preserved in FIB. When DUT receives open message with F bit set to 1 it also
    # should preserve all routes (no route update should happens).
    - name: Force stop RIBD to simulate GR.
      shell: "killall -9 ribd; sleep 0.5; ifconfig et1 down"
      delegate_to: "{{ vm_ip }}"
=====================

When I checked the SONIC docker I could not find this process

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by DhinakaranDayalan** [comment]
# When RIBD up and send bgp open message it will set F bit to 1. Which means that during restart
    # all routes were preserved in FIB. When DUT receives open message with F bit set to 1 it also
    # should preserve all routes (no route update should happens).
    - name: Force stop RIBD to simulate GR.
      shell: "killall -9 ribd; sleep 0.5; ifconfig et1 down"
      delegate_to: "{{ vm_ip }}"

**Comment by wangxin** [comment]
@DhinakaranDayalan This operation is not performed on the SONiC switch under testing. That's why you couldn't find the process on SONiC. Because of "delegate_to: "{{ vm_ip }}", it is executed on the veos virtual machines. It's purpose is to stop BGP on the VMs.

**Comment by alanC-Cameo** [comment]
@DhinakaranDayalan ssh into your veos VM and make sure the process name is correct; for me, it's name is 'Rib' instead of 'ribd'; and the test passed after made the correction.

**Comment by lguohan** [comment]
fixed in pytest version.
