### ISSUE TITLE
Syntax error in advanced-reboot.yml

### ISSUE THREAD

**Issue by mykolaf** [Azure/sonic-mgmt#1175]
**Description**
The latest advanced-reboot.yml has a syntax error,
resulting in Fast-reboot & Warm-reboot test failures.

I got the error using ansible 2.0.0.2.
Was this change tested with newer version? Did we update our ansible version?

**Steps to reproduce the issue:**
1. Run warm-reboot/fast-reboot
2.
3.

**Describe the results you received:**
```
FAILED! => {"failed": true, "reason": "ERROR! Syntax Error while loading YAML.\n\n\nThe error appears to have been in '/builds2/jenkins2/workspace/SONiC_Test-Warm-Reboot/ansible/roles/test/tasks/advanced-reboot.yml': line 28, column 25, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n      set_fact:\n          inboot_list: {% if inboot_list is not defined %}[None]{% else %}{{ inboot_list }}{% endif %}\n                        ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
```

**Describe the results you expected:**
The ansible playbook be parsed.

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by liat-grozovik** [comment]
issue is now fixed. thanks Mykola
