### ISSUE TITLE
Deploy fails on bare sonic-generic.bin

### ISSUE THREAD

**Issue by marian-pritsak** [Azure/sonic-mgmt#120]
```
TASK [sonicv2 : syncd - Post docker - restart container service] ***************
Monday 13 February 2017  12:51:38 +0200 (0:00:00.643)       0:03:32.696 ******* 
fatal: [arc-switch1027]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to start syncd.service: Unit swss.service failed to load: No such file or directory.\n"}
```

syncd.service is deployed before swss, but service file for syncd requires swss service, which is not there yet if deployment is done on a bare sonic-generic.bin for the first time.

**Comment by NStetskovych** [comment]
https://github.com/Azure/sonic-mgmt/pull/118 fix the issue

**Comment by liatgrozovik** [comment]
As it seems from the comments that #118 is not going to be merged now we have a broken solution. deployment on a bare sonic-generic.bin from the first time is not allowed any more.

**Comment by marian-pritsak** [comment]
Fixed in https://github.com/Azure/sonic-mgmt/pull/125
