### ISSUE TITLE
VNET test is not working  for large scale numbers

### ISSUE THREAD

**Issue by volodymyrsamotiy** [Azure/sonic-mgmt#1208]
**Description**
VNET test fails with the few different errors for different scaling numbers. All failures are related to the test itself and to be more specific to the config generation logic. 

1. In some cases it fails due to some syntax error which is most probably relate to config generation logic in the test. Please see below for the example of used command and error output.
```
ansible-playbook test_sonic.yml -i inventory --limit <testbed> -e testbed_name=<testbed> -e testbed_type=t0 -e testcase_name=vnet_vxlan -e cleanup=False -e "num_vnet=32 num_routes=20000 num_endpoints=2000"
...
TASK [test : Load VNet info from file] *****************************************
Tuesday 12 November 2019  16:43:57 +0000 (0:00:00.654)       0:00:32.498 ******
fatal: [<testbed>]: FAILED! => {"failed": true, "msg": "ERROR! Syntax Error while loading YAML.\n\n\nThe error appears to have been in 'True': line 3229, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\n(could not open file to display line)"}

PLAY RECAP *********************************************************************
<testbed>           : ok=40   changed=9    unreachable=0    failed=1
```

2. Also in some other cases different problem is observed, but still related to the config generation logic in the test. In some cases invalid endpoint IP address is generated for some VNET routes (e.g. "200.1.1.666"). Please see below for the example of used command and error output.
```
ansible-playbook test_sonic.yml -i inventory --limit <testbed> -e testbed_name=<testbed> -e testbed_type=t0 -e testcase_name=vnet_vxlan -e cleanup=False -e "num_vnet=32 num_routes=12000 num_endpoints=4000"
...       "======================================================================",
        "ERROR: vnet_vxlan.VNET",
        "----------------------------------------------------------------------",
        "Traceback (most recent call last):",
        "  File \"ptftests/vnet_vxlan.py\", line 287, in runTest",
        "    self.FromServer(test)",
        "  File \"ptftests/vnet_vxlan.py\", line 396, in FromServer",
        "    if isinstance(ip_address(test['host']), ipaddress.IPv4Address):",
        "  File \"/usr/local/lib/python2.7/dist-packages/ipaddress.py\", line 168, in ip_address",
        "    address)",
        "ValueError: u'200.1.1.666' does not appear to be an IPv4 or IPv6 address",
        "",
        "----------------------------------------------------------------------",
        "Ran 1 test in 1.512s",
        "",
        "FAILED (errors=1)"
...
```

**Steps to reproduce the issue:**
1. Run VNET test with the parameters shown in the description.
2. Observe test fails with the error shown in the description.

**Describe the results you received:**
VNET test fails with the few different errors due to invalid config generation logic in the test implementation for large scaling numbers.

**Describe the results you expected:**
VNET test should pass for the large scaling numbers.

**Additional information you deem important:**

This is issue with the test itself so it is reproducible on any image that supports VNET feature.

**Comment by manjuv1** [comment]
The issue is with incorrect IPv4 address generation for endpoints. This is seen in cases when less number of vnets and large number of routes are configured. The number of routes per vnets in these cases is more than 250 and hence the last part of the endpoint IPv4 addresses generated from it becomes a invalid IP address. The fix made with PR 1240 is to spread it across to last two parts of the endpoint address so that it becomes a valid IP.
