### ISSUE TITLE
ansible using ssh to ptf is failed, because ansible can't got ptf-username and ptf-password from inventory file

### ISSUE THREAD

**Issue by robert1030** [Azure/sonic-mgmt#1293]
**Description**
1. ansible-playbook SSH connect to PTF, username is NONE, it can't got username and password from inventory file.
2. inventory file is lab
3. sonic-buildimage build rev-parse HEAD is 4ba0ff25d2ac89b10b2a94208140f7c52776fb69
4. old sonic-buildimage build (build date is 2019/10/28), it can't reproduce the issue

**Steps to reproduce the issue:**
1. set up ip, username & password of sonic dut to inventory file (lab) 
2. set up ip, username & password of PTF to inventory file (lab)
3. set up ip, username & password of fanout switch to inventory file (lab)
4. add-topo ptf32
5. deploy ptf32 config to sonic dut
6. using below command to run arp case of ptf32.
ansible-playbook -vvvi lab -l sonicdev test_sonic.yml -e "testcase_name=arp testbed_type=ptf32 testbed_file=testbed.csv testbed_name=ptf-32"

**Describe the results you received:**
TASK [test : copy test files over] **************************************************************************************************************************************
task path: /var/sqa/sonic-mgmt/ansible/roles/test/tasks/arpall.yml:70
Wednesday 18 December 2019  07:10:12 +0000 (0:00:00.152)       0:00:19.105 **** 
<192.168.59.88> ESTABLISH SSH CONNECTION FOR USER: None
<192.168.59.88> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=120s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/var/sqa/.ansible/cp/51f2697b93 192.168.59.88 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1576653012.78-162589759020731 `" && echo ansible-tmp-1576653012.78-162589759020731="` echo $HOME/.ansible/tmp/ansible-tmp-1576653012.78-162589759020731 `" ) && sleep 0'"'"''
<192.168.59.88> (255, '', "Warning: Permanently added '192.168.59.88' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey,password).\r\n")
fatal: [sonicdev]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: Warning: Permanently added '192.168.59.88' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey,password).", 
    "unreachable": true
}

**Describe the results you expected:**
TASK [test : copy test files over] *********************************************
task path: /var/sqa/sonic-mgmt/ansible/roles/test/tasks/arpall.yml:70
Wednesday 18 December 2019  06:53:23 +0000 (0:00:00.038)       0:00:15.182 **** 
<192.168.59.88> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.59.88> SSH: EXEC sshpass -d15 ssh -C -q -o ControlMaster=auto -o ControlPersist=120s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/var/sqa/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.59.88 'mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1576652003.58-241844331337431 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1576652003.58-241844331337431 )"'
<192.168.59.88> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.59.88> SSH: EXEC sshpass -d15 ssh -C -q -o ControlMaster=auto -o ControlPersist=120s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/var/sqa/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.59.88 'rc=flag; [ -r /root/ptftests/mtu_test.py ] || rc=2; [ -f /root/ptftests/mtu_test.py ] || rc=1; [ -d /root/ptftests/mtu_test.py ] && rc=3; python -V 2>/dev/null || rc=4; [ x"$rc" != "xflag" ] && echo "${rc}  "/root/ptftests/mtu_test.py && exit 0; (python -c '"'"'import hashlib; BLOCKSIZE = 65536; hasher = hashlib.sha1();
afile = open("'"'"'/root/ptftests/mtu_test.py'"'"'", "rb")

**Additional information you deem important:**

## 1. inventory file - lab info **
[sonic_xxxx_100]
sonicdev ansible_host=192.168.59.84      ansible_user=admin      ansible_ssh_pass=password       hwsku="xxxxxxxx" os="sonic"

[sonic_xxxx_100:vars]
hwsku=xxxxxxxx
iface_speed=100000

[sonic:children]
sonic_xxxx_100

[fanout]
xxx-fanoutleaf     ansible_host=192.168.59.18      ansible_user=admin      ansible_ssh_pass=password       hwsku="xxxxx"  os="xxxx"
xxx-fanoutroot   ansible_host=192.168.59.16      ansible_user=admin      ansible_ssh_pass=password       hwsku="xxxxx"        os="xxxx"

[lab:children]
sonic
fanout
ptf

[lab:vars]
mgmt_subnet_mask_length=24

[ptf]
ptf_pt32   ansible_host=192.168.59.88      ansible_user=root       ansible_ssh_pass=root 
ptf_vmt0  ansible_host=192.168.59.89      ansible_user=root       ansible_ssh_pass=root

## 2. testbed.csv file info
conf-name,group-name,topo,ptf_image_name,ptf_ip,server,vm_base,dut,ptf,comment
ptf-32,pt32,ptf32,docker-ptf,192.168.59.88/24,server_1,,sonicdev,ptf_pt32,SQA Test PTF32 for sonicdev
vms-t0,vmt0,t0,docker-ptf,192.168.59.89/24,server_1,VM0100,sonicdev,ptf_vmt0,SQA Test T0 for sonicdev
    ```

**Comment by wangxin** [comment]
Can you try to add `ptf_host=ptf_pt32` var to the `sonicdev` host in your inventory file? For example:
```
[sonic_xxxx_100]
sonicdev ansible_host=192.168.59.84 ansible_user=admin ansible_ssh_pass=password hwsku="xxxxxxxx" os="sonic" ptf_host=ptf_pt32 

...
```

**Comment by robert1030** [comment]
@wangxin
Hi wangxin:

After add ptf_host=ptf_pt32  to lab file, the issue still can be reproduced.

[sonic_xxxx_100]
sonicdev    ansible_host=192.168.59.84      ansible_user=admin      ansible_ssh_pass=password       hwsku="xxxxxxxx" os="sonic"      ptf_host=ptf_pt32

TASK [test : copy test files over] **************************************************************************************************************************************
task path: /var/sqa/sonic-mgmt/ansible/roles/test/tasks/arpall.yml:70
Monday 23 December 2019  06:20:40 +0000 (0:00:00.144)       0:00:17.243 ******* 
<192.168.59.88> ESTABLISH SSH CONNECTION FOR USER: None
<192.168.59.88> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=120s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/var/sqa/.ansible/cp/51f2697b93 192.168.59.88 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1577082040.76-62184758274669 `" && echo ansible-tmp-1577082040.76-62184758274669="` echo $HOME/.ansible/tmp/ansible-tmp-1577082040.76-62184758274669 `" ) && sleep 0'"'"''
<192.168.59.88> (255, '', "Warning: Permanently added '192.168.59.88' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey,password).\r\n")
fatal: [sonic-ag9032v2a]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: Warning: Permanently added '192.168.59.88' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey,password).", 
    "unreachable": true
}

But add "ptf_host=ptf_pt32" to the end of the command:  ansible-playbook -vvvi lab -l sonicdev test_sonic.yml -e "testcase_name=arp testbed_type=ptf32 testbed_file=testbed.csv testbed_name=ptf-32 ptf_host=ptf_pt32", the issue can't be reproduced.

Adding ptf_host = ptf_pt32 to ansible-playbook is not necessary at old sonic-mgmt versions (old sonic-buildimage build (build date is 2019/10/28))

**Comment by wangxin** [comment]
I guess the ansible version in your sonic-mgmt docker is 2.8.7. I am not sure if it is an issue of new Ansible. At least the new ansible's behavior of parsing inventory file is different.

**Comment by gord1306** [comment]
Hi @wangxin, @robert1030 , I also encounter the same issue.

**Comment by gord1306** [comment]
Hi @robert1030 , I tried a workaround that to use extra vars when perfroming the ansib-playbook, e.g. ansible-playbook -vvvv lab -l sonicdev test_sonic.yml -e "testcase_name=arp testbed_type=ptf32 testbed_file=testbed.csv testbed_name=ptf-32 **ptf_host=ptf1**"

Could you try this is work for you

**Comment by robert1030** [comment]
Hi @gord1306

I have try to add "ptf_host=ptf_pt32" to the end of the command: ansible-playbook -vvvi lab -l sonicdev test_sonic.yml -e "testcase_name=arp testbed_type=ptf32 testbed_file=testbed.csv testbed_name=ptf-32 ptf_host=ptf_pt32", the issue can't be reproduced.

Adding ptf_host = ptf_pt32 to ansible-playbook is not necessary at old sonic-mgmt versions (old sonic-buildimage build (build date is 2019/10/28))

thanks for your response.

**Comment by wangxin** [comment]
Problem solved.
