### ISSUE TITLE
delegate_to failed due to ssh key error

### ISSUE THREAD

**Issue by stephenxs** [Azure/sonic-mgmt#1302]
**Description**
delegate_to failed due to ssh key error.
It seems only the host running sonic-mgmt has the correct ssh key for DUT can the test case pass.
With mismatched key or without key it will fail.

ansible log:

    10:50:23 TASK [test : Gathering peer VM information from lldp] **************************
    10:50:23 task path: /SONiC_Test-LAG2-minlink/ansible/roles/test/tasks/lag_2.yml:30
    10:50:23 Tuesday 24 December 2019  02:50:23 +0000 (0:00:00.740)       0:01:10.080 ****** 
    10:50:23 fatal: [r-tigris-13-t1-lag]: FAILED! => {
    10:50:23     "msg": "Docker version check (['/usr/bin/docker', u'-H=ssh://admin@r-tigris-13', 'version', '--format', \"'{{.Server.Version}}'\"]) failed: error during connect: Get http://docker/v1.40/version: command [ssh -l admin r-tigris-13 -- docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=Host key verification failed.\r\n\n"
    10:50:23 }

test script:

    - name: Gathering peer VM information from lldp
    lldp:
    delegate_to: "{{ ansible_host }}_lldp"

**Steps to reproduce the issue:**
Just run the testcase lag_2.
Testcases including copp, qos, lag_minilink, sensors, and dip_sip also fail because of this issue.

**Describe the results you received:**
Test failed due to ssh key error.

**Describe the results you expected:**
Test should pass.

**Additional information you deem important:**
    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
@msosyak, it looks like this change is introduced by you. can you look into this?

**Comment by msosyak** [comment]
@stephenxs Could you provide logs with verbosity level -vvv starts from https://github.com/Azure/sonic-mgmt/blob/master/ansible/roles/test/tasks/lag_2.yml#L26.

**Comment by stephenxs** [comment]
Hi @msosyak 
please check 
[lag_2.log](https://github.com/Azure/sonic-mgmt/files/4039635/lag_2.log)

**Comment by msosyak** [comment]
Looks like ssh key is generated and added to known host on dut successfully.

@stephenxs  Could you provide the output of `show version` from dut and ` docker version` from both dut and sonic-mgmt container.
Also try to add `- pause:` before https://github.com/Azure/sonic-mgmt/blob/74fb5978eee7e078c89e349c5b30f276c1e755ff/ansible/roles/test/tasks/lag_2.yml#L30.
Then when the test will stop try to ssh from sonic-mgmt container to dut `ssh admin@r-anaconda-10`.
You should be prompted to dut with any additional input. 

If you receive a password request or message "WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED! " then it means that add_container_to_inventory.yml did some configuration incorrectly.

Also, I see that keys are generated under /root/.ssh. Are you logged to sonic-mgmt under root user?

**Comment by stephenxs** [comment]
Days before I manually tested. It promoted something like the following, indicating the key saved in the host was out-of-date. (The following isn't captured from the DUT but they are similar)

    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    @    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
    Someone could be eavesdropping on you right now (man-in-the-middle attack)!
    It is also possible that a host key has just been changed.
    The fingerprint for the RSA key sent by the remote host is
    SHA256:YcIjZL6H9sSEUCdsVbJW7PMTggXRHLFjBeaE3Ef/EEA.
    Please contact your system administrator.
    Add correct host key in /c/Users/stephens/.ssh/known_hosts to get rid of this message.
    Offending RSA key in /c/Users/stephens/.ssh/known_hosts:17
    RSA host key for arc-mtbc-1001 has changed and you have requested strict checking.
    Host key verification failed.
    lost connection

**Comment by stephenxs** [comment]
I tried on another testbed at the point you mentioned and got:

    root@dc8700b74501:~# ssh admin@mtbc-sonic-03-2700
    Warning: the RSA host key for 'mtbc-sonic-03-2700' differs from the key for the IP address '10.112.71.251'
    Offending key for IP in /root/.ssh/known_hosts:6
    Matching host key in /root/.ssh/known_hosts:9
    Are you sure you want to continue connecting (yes/no)? no
    Host key verification failed.
    root@dc8700b74501:~#

**Comment by msosyak** [comment]
The reason for this error is that you have two entries for dut in your know_host file. One by hostname and another by IP.

Once you change the ssh key on dut, e.g. reinstall the image, the appropriate entry should be updated in your known_hosts to be able to access docker-engine on dut from sonic-mgmt container.
This is done automatically here https://github.com/Azure/sonic-mgmt/blob/74fb5978eee7e078c89e349c5b30f276c1e755ff/ansible/roles/test/tasks/add_container_to_inventory.yml#L1

As I see in your testbed `ansible_host` contains a hostname and entry by hostname is updated during the task described above. 

The entry by IP was probably generated when you ssh to the dut by IP address manually before.

I would recommend you to clean up your known_host file to be able to run CT.
Also, you could extend https://github.com/Azure/sonic-mgmt/blob/74fb5978eee7e078c89e349c5b30f276c1e755ff/ansible/roles/test/tasks/add_container_to_inventory.yml to handle this case.

**Comment by stephenxs** [comment]
Hi @msosyak, with the old ssh key removed, the issue won't be reproduced.
