### ISSUE TITLE
ansible syntax error in pfc watchdog test case

### ISSUE THREAD

**Issue by stephenxs** [Azure/sonic-mgmt#1303]
**Description**
Ansible syntax error in pfc watchdog test case.
The test script:

        - name: Test PFC WD Functional tests.
          include_tasks: roles/test/tasks/pfc_wd/functional_test/functional_test.yml
          with_dict: "{{select_test_ports}}"
          when: subtest is undefined or (subtest is defined and 'pfc_functional' in subtest)

The error log

    06:23:07 
    06:23:07 TASK [test : Test PFC WD Functional tests.] ************************************
    06:23:07 task path: /builds2/jenkins2/workspace/SONiC_Test-PFCWD/ansible/roles/test/tasks/pfc_wd.yml:154
    06:23:07 Tuesday 24 December 2019  22:23:07 +0000 (0:00:02.384)       0:10:33.109 ****** 
    06:23:08 Read vars_file 'vars/docker_registry.yml'
    06:23:08 fatal: [arc-switch1041]: FAILED! => {
    06:23:08     "reason": "Syntax Error while loading YAML.\n  expected <block end>, but found '<block mapping start>'\n\nThe error appears to be in '/builds2/jenkins2/workspace/SONiC_Test-PFCWD/ansible/roles/test/tasks/pfc_wd/functional_test/functional_test.yml': line 82, column 2, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n- name: Deploy pfc packet generater file to fanout switch\n include_tasks: roles/test/tasks/pfc_wd/functional_test/deploy_pfc_pktgen.yml\n ^ here\n"
    06:23:08 }
    06:23:08 fatal: [arc-switch1041]: FAILED! => {
    06:23:08     "reason": "Syntax Error while loading YAML.\n  expected <block end>, but found '<block mapping start>'\n\nThe error appears to be in '/builds2/jenkins2/workspace/SONiC_Test-PFCWD/ansible/roles/test/tasks/pfc_wd/functional_test/functional_test.yml': line 82, column 2, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n- name: Deploy pfc packet generater file to fanout switch\n include_tasks: roles/test/tasks/pfc_wd/functional_test/deploy_pfc_pktgen.yml\n ^ here\n"
    06:23:08 }

**Steps to reproduce the issue:**
execute the pfcwd

**Describe the results you received:**
The error log mentioned above.

**Describe the results you expected:**
There should not be errors when executing pfcwd test.

**Additional information you deem important:**

    **Output of `show version`:**

    ```
commit d12069180dbae9660ee8e1f42869524e58c667a7
Author: Renuka Manavalan <47282725+renukamanavalan@users.noreply.github.com>
Date:   Wed Dec 18 11:04:11 2019 -0800

    Replace apply_configlet parameter with a check on if apply configlet script exist for this topo. (#1297)

    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by liat-grozovik** [comment]
This issue is preventing to approve pfcwd in 201911 and master.
The changes are due a new ansible version pushed to sonic-mgmt.

**Comment by msosyak** [comment]
I guess that issue is there 
https://github.com/Azure/sonic-mgmt/blob/47feff7a6e87feff901aa7f1968c436d685f861e/ansible/roles/test/tasks/pfc_wd/functional_test/functional_test.yml#L82
