### ISSUE TITLE
"eos_login" and "eos_password" undefined if run playbook bgp_gr_helper.yml test

### ISSUE THREAD

**Issue by robert1030** [Azure/sonic-mgmt#1321]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Description**
1. sonic-mgmt test suite stop at "Force stop RIBD to simulate GR" of bgp_gr_helper.yml
2. playbook command: ansible-playbook -vvvi lab -l sonicdev test_sonic.yml -e "testcase_name=bgp_gr_helper testbed_type=t1 testbed_file=testbed.csv testbed_name=vms-t1 ptf_host=ptf_vmt1"
3.  ansible-playbook 2.8.7 can't got eos_login and eos_password even if they has been defined in sonic-mgmt/ansible/group_vars/all/creds.yml.

**Steps to reproduce the issue:**
1. start-vms for T1 test
2. add-topo T1 topology
3. gen-mg t1 minigraph
4. deploy-mg to DUT.
5. Run: ansible-playbook -vvvi lab -l sonicdev test_sonic.yml -e "testcase_name=bgp_gr_helper testbed_type=t1 testbed_file=testbed.csv testbed_name=vms-t1 ptf_host=ptf_vmt1"

6. got below error message @ Force stop RIBD to simulate GR step.
TASK [test : Force stop RIBD to simulate GR.] ***************************************************************************************************************************
task path: /var/sqa/sonic-mgmt/ansible/roles/test/tasks/bgp_gr_helper.yml:49
Thursday 09 January 2020  01:19:27 +0000 (0:00:00.782)       0:01:01.587 ****** 
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/commands/command.py
Pipelining is enabled.
<192.168.59.47> ESTABLISH SSH CONNECTION FOR USER: None
<192.168.59.47> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=120s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/var/sqa/.ansible/cp/a46f235326 192.168.59.47 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
fatal: [sonicdev]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Data could not be sent to remote host \"192.168.59.47\". Make sure this host can be reached over ssh: Warning: Permanently added '192.168.59.47' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey,keyboard-interactive).\r\n", 
    "unreachable": true
}

**Additional information you deem important:**
sonic-mgmt/ansible/group_vars/all/creds.yml info:

---
eos_default_login: admin
eos_default_password: ''
eos_login: admin
eos_password: 123456
eos_root_password: 123456
sonic_default_password:
sonic_login: admin
sonic_password: password

**Comment by lguohan** [comment]
not sure if it is the same issue, but I think it should be vm_name instead of vm_ip used in delegate_to.

https://github.com/ansible/ansible/issues/12079

**Comment by robert1030** [comment]
@lguohan 
Try run playbook again after change vm_ip to vm_name in  delegate_to, it still get error message same to issue.

TASK [test : Force stop RIBD to simulate GR.] ***************************************************************************************************************************
task path: /var/sqa/sonic-mgmt/ansible/roles/test/tasks/bgp_gr_helper.yml:49
Thursday 09 January 2020  07:55:01 +0000 (0:00:00.890)       0:01:03.013 ****** 
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/commands/command.py
Pipelining is enabled.
<ARISTA12T0> ESTABLISH SSH CONNECTION FOR USER: None
<ARISTA12T0> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=120s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/var/sqa/.ansible/cp/21333b5bcd ARISTA12T0 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
fatal: [sonicdev]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Data could not be sent to remote host \"ARISTA12T0\". Make sure this host can be reached over ssh: ssh: Could not resolve hostname arista12t0: Name or service not known\r\n", 
    "unreachable": true
}

[log file, please refer the link](https://drive.google.com/open?id=1HcQHdrDxdit5vSaXXfqAwsrrSHrPPoIm0Q-Wukwqocc)

**Comment by lguohan** [comment]
plan to rewrite it in pytest. will not address this in ansible.
