### ISSUE TITLE
[LAG fallback] Conditional check Error for the flapping lag member

### ISSUE THREAD

**Issue by chenkelly** [Azure/sonic-mgmt#1331]
**Description**
In [lag_fallback.yml](https://github.com/Azure/sonic-mgmt/blob/master/ansible/roles/test/tasks/lag_fallback.yml#L17) line 17, to create "po_fallback" variable based on the "fallback" definition of lag_facts, but forget to consider its value when run some test cases. 

**Steps to reproduce the issue:**
1.  Run t0 topology.
     -- Set fallback to true for PortChannel0001, fallback to false for PortChannel0002, and not assign fallback for PortChannel0003 and PortChannel0004
2. ansible-playbook -i {INVENTORY} --limit {DUT_NAME} test_sonic.yml -e testbed_name={TESTBED_NAME} -e testcase_name=lag_2

**Describe the results you received:**
All fallback test cases passed.

**Describe the results you expected:**
Error on the task below.
> 
    - name: Verify {{ flap_intf}}  lag member interfaces are marked as deselected for the shutdown port
      assert: { that: "'{{ lag_facts.lags[po]['po_stats']['ports'][item]['runner']['selected'] }}' == 'False'" }
      with_items: "{{ po_interfaces.keys() }}"
      when: item == "{{ flap_intf }}"

We shall consider "po_fallback" value on when statement.
After shut down neighbor interface on VM to stop LACPDU sending, If  LAG fallback is enabled, the member port should still be up and selected because the member port is connected to fanout switch on physical topology. 
> 
    - name: Verify {{ flap_intf}}  lag member interfaces are marked as deselected for the shutdown port without fallback
      assert: { that: "'{{ lag_facts.lags[po]['po_stats']['ports'][item]['runner']['selected'] }}' == 'False'" }
      with_items: "{{ po_interfaces.keys() }}"
      when:
        - po_fallback != True
        - item == "{{ flap_intf }}"

    - name: Verify {{ flap_intf}}  lag member interfaces are marked as selected for the shutdown port with fallback
      assert: { that: "'{{ lag_facts.lags[po]['po_stats']['ports'][item]['runner']['selected'] }}' == 'True'" }
      with_items: "{{ po_interfaces.keys() }}"
      when:
        - po_fallback == True
        - item == "{{ flap_intf }}"

Signed-off-by: kelly_chen@edge-core.com

**Comment by chenkelly** [comment]
Hi @hzheng5 
Could you give us some advice about the question? 
If our solution is correct, we will send PR to address the issue.
Thanks very much.

**Comment by hzheng5** [comment]
> Hi @hzheng5
> Could you give us some advice about the question?
> If our solution is correct, we will send PR to address the issue.
> Thanks very much.

Hi @chenkelly 

Yes. The issue looks valid to me. Please send the PR.

Many thanks,
Haiyang
