### ISSUE TITLE
[Everflow] EverflowNeighborTest test does not support egress mirroring

### ISSUE THREAD

**Issue by nazariig** [Azure/sonic-mgmt#1399]
**Description**
EverflowNeighborTest test does not support egress mirroring:
```bash
TASK [test : debug] *******************************************************************************************************************************************************************************************
task path: /auto/mtrswgwork/nazariig/git/sysgit/bug/everflow/sonic-mgmt/ansible/roles/test/tasks/ptf_runner.yml:52
Tuesday 18 February 2020  17:06:23 +0000 (0:00:01.272)       0:13:58.375 ******
ok: [sonic-t1-lag] => {
    "out.stdout_lines": [
        "everflow_neighbor_test.EverflowNeighborTest ... ERROR",
        "",
        "======================================================================",
        "ERROR: everflow_neighbor_test.EverflowNeighborTest",
        "----------------------------------------------------------------------",
        "Traceback (most recent call last):",
        "  File \"acstests/everflow_neighbor_test.py\", line 195, in runTest",
        "    self.check_mirrored_packet()",
        "  File \"acstests/everflow_neighbor_test.py\", line 140, in check_mirrored_packet",
        "    payload['IP'].ttl -= 1",
        "  File \"/usr/local/lib/python2.7/dist-packages/scapy/packet.py\", line 772, in __getitem__",
        "    raise IndexError(\"Layer [%s] not found\" % lname)",
        "IndexError: Layer [IP] not found",
        "",
        "----------------------------------------------------------------------",
        "Ran 1 test in 0.004s",
        "",
        "FAILED (errors=1)"
    ]
}
Read vars_file 'vars/docker_registry.yml'
```
The test tries to modify IP layer of ARP/NDP packet:
```python
pkt = self.basev6_pkt if ipv6 else self.base_pkt
payload = pkt.copy()

if self.mirror_stage == "egress":
    payload['Ethernet'].src = self.router_mac
    payload['IP'].ttl -= 1
```

**Steps to reproduce the issue:**
1. Deploy t1-lag
2. Run Everflow test

**Describe the results you received:**
* Everflow test fails

**Describe the results you expected:**
* Everflow test should pass

**Additional information you deem important:**

    **Output of `show version`:**
    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**
    ```
    (paste your output here)
    ```

**Comment by daall** [comment]
@nazariig @abdosi @yxieca Unless any of you have any objections, I'm planning on just updating the EverflowNeighborTest to only run with ingress mirroring. My rationale is:
1. We currently don't use egress mirroring to handle ARP/ND packets anywhere explicitly like we do for ingress mirroring, and
2. I can't think of a really strong use case for mirroring these packets on the egress (and if someone comes up with one, they're probably in a better/more informed position to update the test case than we are anyways... :))

I'm happy to discuss more, otherwise I will go ahead and open a PR to skip the egress tests for this particular test case.

**Comment by yxieca** [comment]
We have an official test for warm reboot arp behavior: https://github.com/Azure/sonic-mgmt/blob/master/tests/arp/test_wr_arp.py. I think we can remove this scenario.

**Comment by abdosi** [comment]
> @nazariig @abdosi @yxieca Unless any of you have any objections, I'm planning on just updating the EverflowNeighborTest to only run with ingress mirroring. My rationale is:
> 
> 1. We currently don't use egress mirroring to handle ARP/ND packets anywhere explicitly like we do for ingress mirroring, and
> 2. I can't really think of a strong use case for mirroring these types of packets on the egress (and if someone comes up with one, they're probably in a better/more informed position to update the test case than we are anyways... :))
> 
> I'm happy to discuss more, otherwise I will go ahead and open a PR to skip the egress tests for this particular test case.

@daall I also agree there is no use-case i am aware of egress mirroring ARP/ND Packet
