### ISSUE TITLE
Ansible template fib.j2 fails due removed configuration properties for the ToRRouter in T0 topology

### ISSUE THREAD

**Issue by monipko** [Azure/sonic-mgmt#1430]
**Description**

Ansible template ansible/roles/test/templates/fib.j2 fails due removed configuration properties for the ToRRouter in T0 topology. 
Since T0 topo files have changed in [#1233](https://github.com/Azure/sonic-mgmt/pull/1233) template ansible/roles/test/templates/fib.j2  has no corresponding updates.
It affects warm-reboot-fib and decap tests which are failing.

**Steps to reproduce the issue:**
1. Run any warm-reboot-fib test case with deployed topology T0.
```
ansible-playbook test_sonic.yml -i inventory --limit <testbed> \
        -e testbed_name=<testbed> \
        -e testbed_type=t0 -e testcase_name=warm-reboot-fib
```
2. Run any decap test case with deployed topology T0.
```
ansible-playbook test_sonic.yml -i inventory --limit <testbed> \
        -e testbed_name=<testbed> \
        -e testbed_type=t0 -e testcase_name=decap -e dscp_mode=pipe -e ecn_mode=copy_from_outer
```

**Describe the results you received:**

For both runs:
```
TASK [test : template] *********************************************************
Thursday 05 March 2020  19:41:02 +0000 (0:00:00.496)       0:00:42.571 ******** 
fatal: [testbed -> 10.10.10.67]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'podset_number'"}

```

**Describe the results you expected:**
1.  warm-reboot-fib TC passed
2. decap copy_from_outer TC passed

**Comment by lguohan** [comment]
we are going to refactor the template part.

**Comment by monipko** [comment]
Issue should be reopened.
warm-reboot-fib test case still fails with:

> "AnsibleUndefinedVariable: 'dict object' has no attribute 'podset_number'"

and the same is for decap [#1480](https://github.com/Azure/sonic-mgmt/issues/1480)

**Comment by poornaviswa** [comment]
Issue should be re-opened. Fib test too fails with the same error. Thanks.
