### ISSUE TITLE
Decap test case failed due removed configuration properties for the ToRRouter in T0 topology

### ISSUE THREAD

**Issue by monipko** [Azure/sonic-mgmt#1480]
**Description**

Decap test case failed due removed configuration properties for the ToRRouter in T0 topology
Since T0 topo files have changed in [#1233](https://github.com/Azure/sonic-mgmt/pull/1233) template ansible/roles/test/templates/fib.j2  has no corresponding updates.
It affects decap tests which are failing.

**Steps to reproduce the issue:**
1.  Run any decap test case with deployed topology T0.
```
ansible-playbook test_sonic.yml -i inventory --limit <testbed> \
        -e testbed_name=<testbed> \
        -e testbed_type=t0 -e testcase_name=decap -e dscp_mode=pipe -e ecn_mode=copy_from_outer
```

**Describe the results you received:**

Test case fails on template execution step:

```
TASK [test : template] *********************************************************
Thursday 05 March 2020  19:41:02 +0000 (0:00:00.496)       0:00:42.571 ******** 
fatal: [testbed -> 10.10.10.67]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'podset_number'"}

```

**Describe the results you expected:**
1.  decap copy_from_outer TC passed

**Comment by wangxin** [comment]
The FIB testing (tests/fib/test_fib.py) is also affected by this issue.

**Comment by lguohan** [comment]
need to run test_announce_routes.py before run test_fib.py. test_fib is not affected.

**Comment by wangxin** [comment]
Sorry, my mistake. The existing ansible FIB tests were affected. We should have switched to the pytest version.

**Comment by prsunny** [comment]
Can we close this?

**Comment by wangxin** [comment]
The problem has been resolved. I am closing this issue.
