### ISSUE TITLE
Unable to Start VM (vEOS and SONiC)

### ISSUE THREAD

**Issue by li7hui** [Azure/sonic-mgmt#1489]
i was following the steps in below links:
https://github.com/Azure/sonic-mgmt/blob/master/ansible/doc/README.testbed.Setup.md
after put in 
`./testbed-cli.sh start-vms server_1 password.txt`
I got 
```
skipping: [STR-ACS-SERV-01]
STR-ACS-SERV-01            : ok=39   changed=2    unreachable=0    failed=0    skipped=25   rescued=0    ignored=0 
```
after put in 
`ansible -m ping -i veos server_1`
I got 
```
VM0100 | UNREACHABLE! => {
    "changed": false, 
    "msg": "Data could not be sent to remote host \"172.28.56.144\". Make sure this host can be reached over ssh: ssh: connect to host 172.28.56.144 port 22: No route to host\r\n", 
    "unreachable": true
}
```
In addition, when I put in the following command on STR-ACS-SERV-01
`sudo virsh list --state-running`
I got empty list of VMs. 

There is a duplicated issue #851 , but it didn't mention how to debug this in detail. 
And here is the screen print out of running ansible-playbook with -vvv enabled. 
[ansible.log](https://github.com/Azure/sonic-mgmt/files/4385857/ansible.log)

**Comment by li7hui** [comment]
i just found the following screen print out of Start VMs task in ansible-playbook. It did nothing to start VMs but print out task name. Can anyone tell me the problem about this. 
![image](https://user-images.githubusercontent.com/1718938/77631103-16ae2100-6f87-11ea-8c5f-5e122b4efe39.png)

**Comment by wangxin** [comment]
The latest testbed-cli.sh script need argument `-n num` to specify the number of VMs to be started. The default number is 0. Could you please try again using CLI like below?
```
./testbed-cli.sh -n 32 start-vms server_1 password.txt
```

**Comment by li7hui** [comment]
@wangxin   it works now, thanks.

**Comment by Steven-Lin09002** [comment]
@li7hui , can you share your docker and server IP config ?
