### ISSUE TITLE
Unable ssh to vEOS VM in Ansible with "Permission denied (publickey,keyboard-interactive)"

### ISSUE THREAD

**Issue by li7hui** [Azure/sonic-mgmt#1513]
Hi team.
I am setting up the PTF testbed according to below link: 
https://github.com/Azure/sonic-mgmt/blob/master/ansible/doc/README.testbed.Setup.md

The vEOS VM has started and I can ping and ssh to the vEOS VM. However, when I run 
ansible -m ping -i veos server_1
It throws out error as below: 
![image](https://user-images.githubusercontent.com/1718938/77999152-ceb34380-7364-11ea-80e6-349cf6ed1ea2.png)

**Comment by feng891005** [comment]
The reason may be that when starting the vm, you need to specify the parameter -n
0 VMs started by default

./testbed-cli.sh -n 32 start-vms server_1 password.txt

**Comment by li7hui** [comment]
@feng891005 , i know that, and it has been solved by #1489

**Comment by li7hui** [comment]
i added following lines into veos, and it solve my problem. 
[vms_1]
VM0100 ansible_host=172.28.55.143 ansible_ssh_user=root ansible_ssh_pass=123456
VM0101 ansible_host=172.28.55.142 ansible_ssh_user=root ansible_ssh_pass=123456
VM0102 ansible_host=172.28.55.141 ansible_ssh_user=root ansible_ssh_pass=123456
