### ISSUE TITLE
Script tries to start a docker engine  inside a container which is not allowed - nested containerization 

### ISSUE THREAD

**Issue by Vishalkumarc95** [Azure/sonic-mgmt#1554]
Script tries to perform nested containerization operation which is not a valid operation . It is allowed only on KVM's as they have their own dedicated  OS.  Starting a docker engine inside a container is not a valid scenario.

1. While running decap test by executing below command :-

**ansible-playbook -i lab -l  bisle -e testbed_name=t1-lag test_sonic.yml -e testcase_name=decap**

at task path --> /var/johnar/sonic-mgmt/ansible/roles/test/tasks/decap.yml:142

Getting error that - "Error response from daemon: Container c56c2be2b4391f4c707a7caeef030f61cc66ced13bdf658187e2b18ddfe69a45 is not running", "rc": 1, "invocation": {"module_args": {"creates": null, "executable": null, "_uses_shell": true, "strip_empty_ends": true, "_raw_params": "docker exec swss sh -c \\"swssconfig /decap_conf.json\\"", "removes": null, "argv": null, "warn": true, "chdir": null, "stdin_add_newline": true, "stdin": null}}, "start": "2020-04-04 05:13:54.715880", "msg": "non-zero return code"}\n', '')

Detailed logs 👎 

FAILED! => {
    "changed": true,
    "cmd": "docker exec swss sh -c \"swssconfig /decap_conf.json\"",
    "delta": "0:00:00.063858",
    "end": "2020-04-04 05:13:54.779738",
    "invocation": {
        "module_args": {
            "_raw_params": "docker exec swss sh -c \"swssconfig /decap_conf.json\"",
            "_uses_shell": true,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2020-04-04 05:13:54.715880",
    "stderr": "Error response from daemon: Container c56c2be2b4391f4c707a7caeef030f61cc66ced13bdf658187e2b18ddfe69a45 is not running",
    "stderr_lines": [
        "Error response from daemon: Container c56c2be2b4391f4c707a7caeef030f61cc66ced13bdf658187e2b18ddfe69a45 is not running"
    ],
    "stdout": "",
    "stdout_lines": []
}

**Comment by msosyak** [comment]
This command just tried to run the command inside swss container on SONiC host.
And this error `Error response from daemon: Container c56c2be2b4391f4c707a7caeef030f61cc66ced13bdf658187e2b18ddfe69a45 is not running` directly said that container is not running.

**Comment by Vishalkumarc95** [comment]
Hi Msosyak ,

We need to add the below logic in the script before applying the given command :-

To check , if the container is running or not , if not , then start the container & then execute the below command :-docker exec swss sh -c "swssconfig /decap_conf.json"


I added this login locally & it worked.

**Comment by msosyak** [comment]
swss is one of the main SONiC services and swss container should not exist during test execution.

**Comment by Vishalkumarc95** [comment]
But this has been observed that swss container gets exited during execution. Perhaps need to check closely why this is happening but for sure ,I had to restart this container every time,I ran this ansible playbook.

**Comment by lguohan** [comment]
the title is really misleading here. it is about orchagent crash. does not look like a test issue. Please triage why orchagent crash. closing the ticket here.
