### ISSUE TITLE
[Copp tests]: Changing ip2me config fails 

### ISSUE THREAD

**Issue by chitra-raghavan** [Azure/sonic-mgmt#1555]
**Description**

Changing ip2me config fails .

	
	
	root@sonic-s5232-01:~# cat /root/ip2me_600.json
	[
		{
			 "COPP_TABLE:trap.group.ip2me": {
				 "cir":"600",
				 "cbs":"600"
			 },
			 "OP": "SET"
		 }
	]
	syslog: 
	root@sonic-s5232-01:~# swssconfig /root/ip2me_600.json
	Apr  9 14:05:21.162061 sonic-s5232-01 NOTICE swss#swssconfig: :- main: Loading config from JSON file:/root/ip2me_600.json...
	Apr  9 14:05:21.164409 sonic-s5232-01 WARNING swss#orchagent: :- processCoppRule: Creating policer for existing Trap group:11000000000753 (name:trap.group.ip2me).
	Apr  9 14:05:21.164409 sonic-s5232-01 ERR swss#orchagent: :- meta_generic_validation_create: SAI_POLICER_ATTR_METER_TYPE:SAI_ATTR_VALUE_TYPE_INT32 attribute is mandatory but not passed in attr list
	Apr  9 14:05:21.164409 sonic-s5232-01 ERR swss#orchagent: :- createPolicer: Failed to create policer trap group trap.group.ip2me, rc=-14
	Apr  9 14:05:21.164409 sonic-s5232-01 ERR swss#orchagent: :- doTask: Processing copp task item failed, exiting.

Due to this SNMP,SSH,IP2ME tests are failing 

**Steps to reproduce the issue:**
1.run copp  tests in 201911 branch 

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

https://github.com/Azure/sonic-swss/issues/1253

**Output of `show version`:**

	root@sonic-s6100-07:~#
	root@sonic-s6100-07:~# show ver

	SONiC Software Version: SONiC.HEAD.31-055d7cd1
	Distribution: Debian 9.12
	Kernel: 4.9.0-11-2-amd64
	Build commit: 055d7cd1
	Build date: Mon Mar 16 20:46:35 UTC 2020
	Built by: johnar@jenkins-worker-7

	Platform: x86_64-dell_s6100_c2538-r0
	HwSKU: Force10-S6100
	ASIC: broadcom
	Serial Number: 2G5ZZP2
	Uptime: 06:05:45 up 16:23,  1 user,  load average: 2.49, 2.44, 2.45

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by msosyak** [comment]
Which version of sonic-mgmt you use?

**Comment by chitra-raghavan** [comment]
Thanks @msosyak .  I have updated  the fix , #1396 , But seeing orchagent crash upon  loading that .json .

 

	root@sonic-s5232-01:~# cat ip2me_600.json
	[
		{
			 "COPP_TABLE:trap.group.nat.ip2me": {
				 "cir":"600",
				 "cbs":"600"
			 },
			 "OP": "SET"
		 }
	 ]
	root@sonic-s5232-01:~#
	root@sonic-s5232-01:~#
	root@sonic-s5232-01:~#
	root@sonic-s5232-01:~# swssconfig ip2me_600.json


	Apr 13 14:29:45.613640 sonic-s5232-01 NOTICE swss#swssconfig: :- main: Loading config from JSON file:ip2me_600.json...
	Apr 13 14:29:45.617865 sonic-s5232-01 ERR syncd#syncd: [none] brcm_sai_set_policer_attribute:473 policer create failed with error Operation still running (0xfffffff6).
	Apr 13 14:29:45.617931 sonic-s5232-01 ERR syncd#syncd: :- processEvent: VID: oid:0x1200000000061c RID: oid:0x41200000003
	Apr 13 14:29:45.618607 sonic-s5232-01 ERR syncd#syncd: :- processEvent: attr: SAI_POLICER_ATTR_CBS: 600
	Apr 13 14:29:45.618607 sonic-s5232-01 ERR syncd#syncd: :- processEvent: failed to execute api: set, key: SAI_OBJECT_TYPE_POLICER:oid:0x1200000000061c, status: SAI_STATUS_OBJECT_IN_USE
	Apr 13 14:29:45.618607 sonic-s5232-01 NOTICE swss#orchagent: :- handle_switch_shutdown_request: switch shutdown request
	Apr 13 14:29:45.619509 sonic-s5232-01 INFO swss#supervisord: orchagent terminate called after throwing an instance of 'std::invalid_argument'
	Apr 13 14:29:45.619509 sonic-s5232-01 INFO swss#supervisord: orchagent   what():  parse error - unexpected end of input
	Apr 13 14:29:45.620326 sonic-s5232-01 ERR syncd#syncd: :- syncd_main: Runtime error: :- processEvent: failed to execute api: set, key: SAI_OBJECT_TYPE_POLICER:oid:0x1200000000061c, status: SAI_STATUS_OBJECT_IN_USE
	Apr 13 14:29:45.620326 sonic-s5232-01 NOTICE syncd#syncd: :- notify_OA_about_syncd_exception: sending switch_shutdown_request notification to OA
	Apr 13 14:29:45.620356 sonic-s5232-01 NOTICE syncd#syncd: :- notify_OA_about_syncd_exception: notification send successfull

	Apr 13 14:29:48.882415 sonic-s5232-01 INFO swss#supervisord 2020-04-13 14:29:46,536 INFO exited: orchagent (terminated by SIGABRT (core dumped); not expected)

**Comment by msosyak** [comment]
Looks like brcm SDK do not allow to change cir/cbs attribute on the fly.
In that case, to test COPP at least manually I could suggest changing original COPP config inside swss and restart services or reboot the dut to apply changes.

**Comment by chitra-raghavan** [comment]
@msosyak, Thanks , after changing the configs manually and upon reload , test passes.

**Comment by daall** [comment]
Fixed by #1633
