### ISSUE TITLE
[Pytest] Need to refactor conn_graph_facts with inv_mapping.json processing

### ISSUE THREAD

**Issue by yvolynets-mlnx** [Azure/sonic-mgmt#1654]
**Description**

Hi,
It is regarding `conn_graph_facts` fixture from `tests/common/fixtures/conn_graph_facts.py` and `ansible/group_vars/all/inv_mapping.json` file.

As I understand the idea of “inv_mapping.json” file is to add possibility to use different graph xml other than the default 'lab_connection_graph.xml'.
Also idea of “conn_graph_facts” fixture is for sure get lab fanout and switch connections information.

There are several issues:
1. Based on current implementation it looks like the following content of the “ansible/group_vars/all/inv_mapping.json” is considered as ok (possible extended example of existed file):
{
   "lab": "lab_connection_graph.xml",
   "": "// This is a comment.  specify all internal mappings below this line",
   "inventory": "lab_connection_graph.xml",
   "veos": "lab_connection_graph.xml",
   "some_example": "lab_connection_graph.xml"
}

It looks redundant that there is a need to map different inventory names to the same lab connection file.

Also `'"": "// This is a comment.  specify all internal mappings below this line"'` should be removed in any case because it creates issue when inventory name obtained from `duthost` is not "lab".

2. Previously “conn_graph_facts” always returned its data because it directly read information from hardcoded “lab_connection_graph.xml” file. Now if inventory name passed in console via “--inventory” option is not defined in “inv_mapping.json” file so “conn_graph_facts” will return empty dictionary - {}. For now to not obtain empty dictionary we at least should have the following content of the “inv_mapping.json” (which looks redundant):

{
   "lab": "lab_connection_graph.xml",
   "": "// This is a comment.  specify all internal mappings below this line",
   "inventory": "lab_connection_graph.xml",
}

**Notes:**
- In `ansible/doc/README.testbed.Config.md` file is described that lab connectivity definition is defined in `lab_connection_graph.xml`.
Is there a plan to add more? Because if no, for now `inv_mapping.json`  looks as redundant file which add additional complexity to "conn_graph_facts" fixture code.

**Comment by yvolynets-mlnx** [comment]
@wangxin @neethajohn Please take a look, and comment.

**Comment by wangxin** [comment]
@yvolynets-mlnx

Question 1:
I agree that `"": "// This is a comment. specify all internal mappings below this line",` should be removed.  Empty string as a key is weird.

This inv_mapping.json is to support multiple labs. Each of the lab could have an inventory file and its corresponding lab connection xml file. Here the concept of lab can be virtual. For example, we can divide the lab test setups into two groups, we can call one group as lab1 and the other lab2. 

Assume we define inventory files and lab connection graph files for the two labs as below:
* lab1: inventory1 and lab_conn1.xml
* lab2: inventory2 and lab_conn2.xml

Then the inv_mapping.json file can be customized to:
```
{
   "inventory1": "lab_conn1.xml",
   "inventory2": "lab_conn2.xml"
}
```
So, please customize this file according to your lab organization.

Question 2:
You need to customize this mapping file according to your lab definition.

Regarding the document, good catch. It need to be updated.

**Comment by neethajohn** [comment]
The empty string as a key was added to avoid conflicts to make rebasing easier. I couldn't find any other way to add a comment inside json.
