### ISSUE TITLE
Please help this beginner... LOL(/ansible/doc)

### ISSUE THREAD

**Issue by stephengzh** [Azure/sonic-mgmt#1691]
**Description**

Hey guys, I ve got an error in "Setup Arista VMs in the server". (https://github.com/Azure/sonic-mgmt/blob/master/ansible/doc/README.testbed.VsSetup.md)

When executing the command:
./testbed-cli.sh -m veos.vtb -n 4 start-vms server_1 password.txt

The result I obtain is:

[WARNING]:  * Failed to parse /var/johnar/sonic-mgmt/ansible/veos.vtb with ini plugin: /var/johnar/sonic-mgmt/ansible/veos.vtb:1: Expected
key=value host variable assignment, got: git

[WARNING]: Unable to parse /var/johnar/sonic-mgmt/ansible/veos.vtb as an inventory source

[WARNING]: No inventory was parsed, only implicit localhost is available

[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

[WARNING]: Could not match supplied host pattern, ignoring: server_1

[WARNING]: Could not match supplied host pattern, ignoring: servers

[WARNING]: Could not match supplied host pattern, ignoring: vm_host

I also feel diffcult in "Setup public key to login into the linux host from sonic-mgmt docker" step.
The instruction: "Modify veos.vtb to use the user name, e.g., foo to login linux host."
The example here "foo" is the host name? I mean, this so called "user name” is my linux name, right?
And for the rest three steps "Adding the public/private key,sudoer list", I found some answers in Google search, but I m not sure correctness...Anyway, it failed..

By the way, folks, I just start learning to build this testbed, so please help me. Really not familiar with it... Trying my best to study.. .LOL

**Comment by stephengzh** [comment]
The modified veos.vtb file is uploaded:

johnar@daa6351ee577:/data/sonic-mgmt/ansible$ cat veos.vtb 
johnar@daa6351ee577:/data/sonic/sonic-mgmt/ansible$ git diff
diff --git a/ansible/veos.vtb b/ansible/veos.vtb
index 4ea5a7a..4cfc448 100644
--- a/ansible/veos.vtb
+++ b/ansible/veos.vtb
@@ -1,5 +1,5 @@

[vm_host_1]
-STR-ACS-VSERV-01 ansible_host=172.17.0.1 ansible_user=use_oiwn_value
+STR-ACS-VSERV-01 ansible_host=172.17.0.1 ansible_user=admin5

[vm_host:children]
vm_host_1

[vms_1]
VM0100 ansible_host=10.250.0.51
VM0101 ansible_host=10.250.0.52
VM0102 ansible_host=10.250.0.53
VM0103 ansible_host=10.250.0.54
VM0104 ansible_host=10.250.0.55
VM0105 ansible_host=10.250.0.56
VM0106 ansible_host=10.250.0.57
VM0107 ansible_host=10.250.0.58
VM0108 ansible_host=10.250.0.59
VM0109 ansible_host=10.250.0.60
VM0110 ansible_host=10.250.0.61
VM0111 ansible_host=10.250.0.62
VM0112 ansible_host=10.250.0.63
VM0113 ansible_host=10.250.0.64
VM0114 ansible_host=10.250.0.65
VM0115 ansible_host=10.250.0.66
VM0116 ansible_host=10.250.0.67
VM0117 ansible_host=10.250.0.68
VM0118 ansible_host=10.250.0.69
VM0119 ansible_host=10.250.0.70
VM0120 ansible_host=10.250.0.71
VM0121 ansible_host=10.250.0.72
VM0122 ansible_host=10.250.0.73
VM0123 ansible_host=10.250.0.74
VM0124 ansible_host=10.250.0.75
VM0125 ansible_host=10.250.0.76
VM0126 ansible_host=10.250.0.77
VM0127 ansible_host=10.250.0.78
VM0128 ansible_host=10.250.0.79
VM0129 ansible_host=10.250.0.80
VM0130 ansible_host=10.250.0.81
VM0131 ansible_host=10.250.0.82

[eos:children]
vms_1

## The groups below are helper to limit running playbooks to server_1, server_2 or server_3 only
[server_1:children]
vm_host_1
vms_1

[server_1:vars]
host_var_file=host_vars/STR-ACS-VSERV-01.yml

[servers:children]
server_1

[servers:vars]
topologies=['t1', 't1-lag', 't1-64-lag', 't1-64-lag-clet', 't0', 't0-16', 't0-56', 't0-52', 'ptf32', 'ptf64', 't0-64', 't0-64-32', 't0-116']

[sonic]
vlab-01 ansible_host=10.250.0.101 type=kvm hwsku=Force10-S6000 serial_port=9000
vlab-02 ansible_host=10.250.0.102 type=kvm hwsku=Force10-S6100 serial_port=9000
vlab-03 ansible_host=10.250.0.105 type=kvm hwsku=Force10-S6000 serial_port=9001
vlab-simx-01 ansible_host=10.250.0.103 type=simx hwsku=MSN2700
vlab-simx-02 ansible_host=10.250.0.104 type=simx hwsku=MSN3700

**Comment by wangxin** [comment]
Your veos.vtb file is not a clean inventory file. It is indeed a git diff file with extra content like
```
johnar@daa6351ee577:/data/sonic/sonic-mgmt/ansible$ git diff
diff --git a/ansible/veos.vtb b/ansible/veos.vtb
index 4ea5a7a..4cfc448 100644
--- a/ansible/veos.vtb
+++ b/ansible/veos.vtb
@@ -1,5 +1,5 @@

[vm_host_1]
-STR-ACS-VSERV-01 ansible_host=172.17.0.1 ansible_user=use_oiwn_value
+STR-ACS-VSERV-01 ansible_host=172.17.0.1 ansible_user=admin5
```

**Comment by stephengzh** [comment]
Thanks wangxin, I misunderstood the instruction. >_<...

**Comment by stephengzh** [comment]
The issue solved, another issue appeared..
![image](https://user-images.githubusercontent.com/65524539/82532722-877f4d00-9b74-11ea-9ee6-0161e80324b0.png)

**Comment by stephengzh** [comment]
An issue solved, another issue appeared……
(By the way, I found two veos.vtb files,one is under "/data/sonic-mgmt/ansible", the other one is under "~/sonic-mgmt/ansible ". The step here is done under the file "/data/sonig-mgmt/ansible", right?)
Issue:

johnar@daa6351ee577:/data/sonic-mgmt/ansible$ ./testbed-cli.sh -m veos.vtb -n 4 start-vms server_1 password.txt
Starting VMs on server 'server_1'

PLAY [servers:&vm_host] **************************************************************************************************************************

TASK [vm_set : get host distribution] ************************************************************************************************************
Thursday 21 May 2020  07:04:01 +0000 (0:00:00.202)       0:00:00.202 ********** 
[WARNING]: Unhandled error in Python interpreter discovery for host STR-ACS-VSERV-01: Invalid/incorrect password: Warning: Permanently added
'172.17.0.1' (ECDSA) to the list of known hosts.  Permission denied, please try again.

fatal: [STR-ACS-VSERV-01]: UNREACHABLE! => {"changed": false, "msg": "Invalid/incorrect password: Warning: Permanently added '172.17.0.1' (ECDSA) to the list of known hosts.\r\nPermission denied, please try again.", "unreachable": true}

PLAY RECAP ***************************************************************************************************************************************
STR-ACS-VSERV-01           : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   

Thursday 21 May 2020  07:04:05 +0000 (0:00:04.114)       0:00:04.316 ********** 
=============================================================================== 
vm_set : get host distribution ------------------------------------------------------------------------------------------------------------ 4.11s

**Comment by glorialearnscoding** [comment]
Hello @stephengao-ragilenetworks  / @DhabeRushabh , I'm having the exactly same issue as yours: fatal: [STR-ACS-VSERV-01] UNREACHABLE

I've tried two ips:
-172.17.0.1 (the docker0 of the host), followed this instructions https://github.com/Azure/sonic-mgmt/blob/master/docs/testbed/README.testbed.VsSetup.md
-10.250.0.1 (the bri1 of the host), as @stephengao-ragilenetworks suggested
and used the correct server host name.
But they all failed. Below are the details:

1. checked server interfaces:
![image](https://user-images.githubusercontent.com/25305252/181451294-8feae86a-0685-4489-9461-e8d4e362e3fe.png)

2. added password.txt:
![image](https://user-images.githubusercontent.com/25305252/181451801-714f6109-fdb3-42d0-9a58-f6d5395c274c.png)

3.1.1 first try with docker0's ip and name "byan"
![image](https://user-images.githubusercontent.com/25305252/181451602-d504e845-0197-4cf3-ab3e-3bac6e4b3f9f.png)

3.1.2 and run script to start VMs:
![image](https://user-images.githubusercontent.com/25305252/181451930-56d3ce1f-9eef-4c0a-88b4-ad19e6644620.png)

3.2.1 then try with br1's ip and name "byan"
![image](https://user-images.githubusercontent.com/25305252/181452322-3623c519-2ebb-4505-8754-c503797fab7a.png)

3.2.2 and run script to start VMs:
![image](https://user-images.githubusercontent.com/25305252/181452494-5dd655a6-a7c3-40c7-b10d-3c9883cd65c9.png)


BTW this looks like a ssh failure, however, I can ssh byan@172.17.0.1 and ssh byan@10.250.0.1 successfully and no password prompted.
![image](https://user-images.githubusercontent.com/25305252/181452876-7af3080c-a675-474f-a6f8-138cf74155f1.png)

**Comment by glorialearnscoding** [comment]
To provide more info, I'm running the script on a Linux VM through Hyper-V with nested virtualization enabled.
Can someone take a look and help me understand the weird result? Thanks!

I saved the messages while running cmd with -vvvv to a temp file:
![image](https://user-images.githubusercontent.com/25305252/181552664-b0348783-d02b-4a66-9b65-bd94c889acd3.png)
![image](https://user-images.githubusercontent.com/25305252/181553934-808a04d0-88f9-4093-925f-e09ad3988eb6.png)
![image](https://user-images.githubusercontent.com/25305252/181554884-35183c11-6381-4aa3-9c48-cea07bdfb6ac.png)

not sure if the last few lines "no such identity: xxx : No such file or directory" mean anything? I assume the ssh keys should be setup by the script in tutorial. I actually couldn't find the /root/.ssh directory. On host, I have only ~/.ssh:
![image](https://user-images.githubusercontent.com/25305252/181559001-5990225f-5481-4abe-839e-7c0a0f1e8950.png)
