### ISSUE TITLE
Unable to start VM (New issue)

### ISSUE THREAD

**Issue by stephengzh** [Azure/sonic-mgmt#1694]
**Description**

Hello guys, Im back again.
The question here is unable to start VM. I searched similar issues but they didn't share the same issue with mine.
The link: https://github.com/Azure/sonic-mgmt/blob/master/ansible/doc/README.testbed.VsSetup.md#setup-arista-vms-in-the-server

I touched a password.txt file and input 123456.

When I execute the command:
./testbed-cli.sh -m veos.vtb -n 4 start-vms server_1 password.txt

The result is:

johnar@daa6351ee577:/data/sonic-mgmt/ansible$ ./testbed-cli.sh -n 4 start-vms server_1 password.txt
Starting VMs on server 'server_1'

PLAY [servers:&vm_host] **************************************************************************************************************************

TASK [vm_set : get host distribution] ************************************************************************************************************
Thursday 21 May 2020  08:54:43 +0000 (0:00:00.201)       0:00:00.201 ********** 
[WARNING]: Unhandled error in Python interpreter discovery for host STR-ACS-SERV-01: Failed to connect to the host via ssh: ssh: connect to host
10.251.0.245 port 22: Connection timed out

fatal: [STR-ACS-SERV-01]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"10.251.0.245\". Make sure this host can be reached over ssh: ssh: connect to host 10.251.0.245 port 22: Connection timed out\r\n", "unreachable": true}

PLAY RECAP ***************************************************************************************************************************************
STR-ACS-SERV-01            : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   

Thursday 21 May 2020  08:55:03 +0000 (0:00:20.266)       0:00:20.468 ********** 
=============================================================================== 
vm_set : get host distribution ----------------------------------------------------------------------------------------------------------- 20.27s

Can anyone fix this issue? Many thanks!

**Comment by gord1306** [comment]
suggest to append -vvvv to show more messages. And the debug file (filename is debug****) may be also located in the /tmp on host OS

**Comment by stephengzh** [comment]
The issue is solved!

**Comment by Wlyy0314** [comment]
how can you fix this issue? I have the same question
<10.251.0.245> ESTABLISH SSH CONNECTION FOR USER: use_own_value
<10.251.0.245> SSH: EXEC sshpass -d10 ssh -o ControlMaster=auto -o ControlPersist=120s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o StrictHostKeyChecking=no -o 'User="use_own_value"' -o ConnectTimeout=30 -o ControlPath=/home/wl/.ansible/cp/f2923a677a 10.251.0.245 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp `"&& mkdir $HOME/.ansible/tmp/ansible-tmp-1668586264.27-7816-164003984435827 && echo ansible-tmp-1668586264.27-7816-164003984435827="` echo $HOME/.ansible/tmp/ansible-tmp-1668586264.27-7816-164003984435827 `" ) && sleep 0'"'"''
<10.251.0.245> (255, '', 'ssh: connect to host 10.251.0.245 port 22: Connection timed out\r\n')
fatal: [STR-ACS-SERV-01]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 10.251.0.245 port 22: Connection timed out", 
    "unreachable": true
}
