### ISSUE TITLE
dhcp_relay test is not stable

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-mgmt#1699]
**Description**

**Steps to reproduce the issue:**
1. check the vs image test. 
https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image-test/263/
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by tahmed-dev** [comment]
It looks like Discover packets were not received by the ptf docker test script:
```
AssertionError: Failed: Discover count of 0 != 4
```
I also noticed in [another](https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image-test/265/testReport/junit/route/test_default_route/test_default_route_set_src/) build, that default route test cases were failing.

```
            # parse set_src
>           m = re.match(r"^default proto (bgp|186) src (\S+)", rt[0])
E           IndexError: list index out of range

common/devices.py:482: IndexError
```

**Comment by lguohan** [comment]
I think somehow, can we check the default route in the dhcp relay test, to make sure the default is there? otherwise, it is a little bit to troubleshoot the issue.

**Comment by lguohan** [comment]
for that build, it seems the dut is not receiving all the route from the neighbor, I do not know how this happens, need to check the bgp summary, but "show bgp summary" was not correct for that build, so I fixed the test to use "show ip bgp summary" to check.

**Comment by tahmed-dev** [comment]
I just updated my setup (6/4) and the test is passing on my setup. Will add fixture to verify routes exist from DUT for DHCP servers. Also, there is internal error where vlan membership was not reflected upon DUT running config. This caused the Discover packets to not be received. The sanity check should probably catch such testbed setup issues.

**Comment by lguohan** [comment]
I think it some infra work going behaind, but I haven't figure out. Likely the ptf docker got updated, or removed? but we have lock to prevent that.

**Comment by lguohan** [comment]
stabilized the infra part. now the test become stabler. close for now. will open issue if we see later.
