### ISSUE TITLE
bgp_speaker test fails when running with vtestbed t0 topology

### ISSUE THREAD

**Issue by arawal1** [Azure/sonic-mgmt#1717]
**Description**
I am trying to run bgp_speaker test with t0 topology using vtestbed but it fails as no packets are received on expected ports

**Steps to reproduce the issue:**
1. Run bgp_speaker test:
py.test bgp/bgp_speaker.py --testbed=vms-kvm-t0  --inventory=../ansible/veos.vtb --testbed_file=../ansible/vtestbed.csv --host-pattern=all --show-capture stdout --module-path=../ansible/library -vvv
2.
3.

**Describe the results you received:**
 File "ptftests/fib_test.py", line 353, in runTest
    self.check_ip_ranges()
  File "ptftests/fib_test.py", line 156, in check_ip_ranges
    self.check_ip_range(ip_range, next_hop, ipv4)
  File "ptftests/fib_test.py", line 171, in check_ip_range
    self.check_ip_route(src_port, ip_range.get_first_ip(), exp_port_list, ipv4)
  File "ptftests/fib_test.py", line 193, in check_ip_route
    res = self.check_ipv4_route(src_port, dst_ip_addr, dst_port_list)
  File "ptftests/fib_test.py", line 252, in check_ipv4_route
    return verify_packet_any_port(self, masked_exp_pkt, dst_port_list)
  File "/usr/lib/python2.7/dist-packages/ptf/testutils.py", line 2538, in verify_packet_any_port
    % (ports, device_number, result.format()))
AssertionError: Did not receive expected packet on any of ports [28, 29, 30, 31] for device 0.

The fib_info file bgp_speaker:
has two entries:
 bgp_speaker_route.txt
0.0.0.0/0 [28] [29] [30] [31]
10.10.10.0/26 [1] [2] [3] [4] [5] [6] [7] [8] [9] [10] [11] [12] [13] [14] [15] [16] [17] [18] [19] [20] [21] [22] [23] [24]

if I remove the first entry I get key error 1.0.0.0

**Describe the results you expected:**
test should pass

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by wangxin** [comment]
@arawal1 Can you try to run test_announce_routes.py and then run the test_bgp_speaker.py test?
The bgp speaker testing depend on routes available in DUT. The test_announce_routes.py script is for announcing IP routes from the PTF exabgp process to VMs. Then DUT can learn the routes from the VMs.

**Comment by arawal1** [comment]
Thank you Xin wang, I found that first fib_info.txt file has test to send traffic default route 0.0.0.0/0 which was failing as bgp neighbors were not advertising default route comparing t0-leaf.j2 with t0-64-leaf.j2 at https://github.com/Azure/sonic-mgmt/blob/master/ansible/roles/eos/templates/ , I see t0-leaf.j2 did not have config  "neighbor {{ remote_ip }} default-originate route-map DEFAULT_ROUTES"  under bgp after adding the default-originate and corresponding route map to t0-leaf.j2 the test passes.

**Comment by wangxin** [comment]
Yes, the bgp speaker testing depend on correct default route on DUT. There was an infrastructure design change. Just after deployment, the VMs do not have static IP routes like before. The default route points to the management gateway. We need to run the test_announce_routes.py to explicitly announce routes via exabgp running in PTF to the VMs. Then DUT can lean the IP routes from VMs, including the default route. After this operation, the default route on DUT points to the VMs if topology is t0.
