### ISSUE TITLE
DHCP relay test fails

### ISSUE THREAD

**Issue by marian-pritsak** [Azure/sonic-mgmt#173]
```
TASK [test : PTF Test - DHCP Relay Test] ***************************************
task path: /.autodirect/rdmzsysgwork/marianp/sonic/sonic-mgmt/ansible/roles/test/tasks/ptf_runner.yml:41
Friday 28 April 2017  19:03:22 +0300 (0:00:00.093)       0:00:07.734 ********** 
fatal: [arc-switch1026-t0-64-32]: FAILED! => {"failed": true, "msg": "ERROR! list object has no element 0"}
```

Looks like minigraph lacks some information.
How to set dhcp servers in minigraph?

**Comment by jleveque** [comment]
Please refer to the following minigraph for the proper format:

https://github.com/Azure/sonic-buildimage/blob/c7ea3470ed3262b3f4f1e7531ab777e1c1b82063/device/mellanox/x86_64-mlnx_msn2410-r0/minigraph.xml#L499

DHCP server IPs should be listed in the <a:Value> tag inside the "DhcpResources" section, delimited by semicolons.

**Comment by jleveque** [comment]
I will leave this issue open, as I think there should be a more verbose error message stating that DHCP servers must be configured in the minigraph.

**Comment by jleveque** [comment]
Added a clear error message if no DHCP servers are specified @ https://github.com/Azure/sonic-mgmt/pull/203.
