### ISSUE TITLE
Issue when generating Minigraph: about the portmap file

### ISSUE THREAD

**Issue by stephengzh** [Azure/sonic-mgmt#1773]
Hi, I am generating  the Minigraph of ptf32 topo.
./testbed-cli.sh deploy-mg ptf1-m lab password.txt

I met a problem, I thought I know the reason, but have no idea to solve:

Here only shows the error lines:

johnar@a3376dfd3b21:~/sonic-mgmt/ansible$ ./testbed-cli.sh deploy-mg ptf1-m lab password.txt -vvv

....
....
....

task path: /var/johnar/sonic-mgmt/ansible/config_sonic_basedon_testbed.yml:83
Monday 15 June 2020  10:56:29 +0000 (0:00:00.058)       0:00:02.866 *********** 
<str-msn2700-01> Attempting python interpreter discovery
<172.28.55.15> ESTABLISH SSH CONNECTION FOR USER: admin5
<172.28.55.15> SSH: EXEC sshpass -d10 ssh -o ControlMaster=auto -o ControlPersist=120s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o StrictHostKeyChecking=no -o 'User="admin5"' -o ConnectTimeout=10 -o ControlPath=/var/johnar/.ansible/cp/b457b01add 172.28.55.15 '/bin/sh -c '"'"'echo PLATFORM; uname; echo FOUND; command -v '"'"'"'"'"'"'"'"'/usr/bin/python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.5'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/libexec/platform-python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/bin/python3'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python'"'"'"'"'"'"'"'"'; echo ENDFOUND && sleep 0'"'"''
<172.28.55.15> (0, 'PLATFORM\nLinux\nFOUND\n/usr/bin/python\n/usr/bin/python3.6\n/usr/bin/python2.7\n/usr/bin/python3\n/usr/bin/python\nENDFOUND\n', "Warning: Permanently added '172.28.55.15' (ECDSA) to the list of known hosts.\r\n")
<172.28.55.15> ESTABLISH SSH CONNECTION FOR USER: admin5
<172.28.55.15> SSH: EXEC sshpass -d10 ssh -o ControlMaster=auto -o ControlPersist=120s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o StrictHostKeyChecking=no -o 'User="admin5"' -o ConnectTimeout=10 -o ControlPath=/var/johnar/.ansible/cp/b457b01add 172.28.55.15 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<172.28.55.15> (0, '{"osrelease_content": "NAME=\\"Ubuntu\\"\\nVERSION=\\"18.04.4 LTS (Bionic Beaver)\\"\\nID=ubuntu\\nID_LIKE=debian\\nPRETTY_NAME=\\"Ubuntu 18.04.4 LTS\\"\\nVERSION_ID=\\"18.04\\"\\nHOME_URL=\\"https://www.ubuntu.com/\\"\\nSUPPORT_URL=\\"https://help.ubuntu.com/\\"\\nBUG_REPORT_URL=\\"https://bugs.launchpad.net/ubuntu/\\"\\nPRIVACY_POLICY_URL=\\"https://www.ubuntu.com/legal/terms-and-policies/privacy-policy\\"\\nVERSION_CODENAME=bionic\\nUBUNTU_CODENAME=bionic\\n", "platform_dist_result": ["Ubuntu", "18.04", "bionic"]}\n', '')
Using module file /var/johnar/sonic-mgmt/ansible/library/port_alias.py
Pipelining is enabled.
<172.28.55.15> ESTABLISH SSH CONNECTION FOR USER: admin5
<172.28.55.15> SSH: EXEC sshpass -d10 ssh -o ControlMaster=auto -o ControlPersist=120s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o StrictHostKeyChecking=no -o 'User="admin5"' -o ConnectTimeout=10 -o ControlPath=/var/johnar/.ansible/cp/b457b01add 172.28.55.15 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<172.28.55.15> (1, '\n{"msg": "failed to find the correct port config for ACS-MSN2700Something wrong when trying to find the portmap file, either the hwsku is not available or file location is not correct", "failed": true, "exception": "WARNING: The below traceback may *not* be related to the actual failure.\\n  File \\"/tmp/ansible_port_alias_payload_RKNDUV/__main__.py\\", line 130, in main\\n    (aliases, portmap, aliasmap, portspeed) = allmap.get_portmap()\\n  File \\"/tmp/ansible_port_alias_payload_RKNDUV/__main__.py\\", line 88, in get_portmap\\n    raise Exception(\\"Something wrong when trying to find the portmap file, either the hwsku is not available or file location is not correct\\")\\n", "invocation": {"module_args": {"hwsku": "ACS-MSN2700"}}}\n', '')
<172.28.55.15> Failed to connect to the host via ssh: 
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_port_alias_payload_RKNDUV/__main__.py", line 130, in main
    (aliases, portmap, aliasmap, portspeed) = allmap.get_portmap()
  File "/tmp/ansible_port_alias_payload_RKNDUV/__main__.py", line 88, in get_portmap
    raise Exception("Something wrong when trying to find the portmap file, either the hwsku is not available or file location is not correct")

fatal: [str-msn2700-01]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "hwsku": "ACS-MSN2700"
        }
    }, 
    "msg": "failed to find the correct port config for ACS-MSN2700Something wrong when trying to find the portmap file, either the hwsku is not available or file location is not correct"
}

PLAY RECAP **********************************************************************************************************************************************************************************
str-msn2700-01             : ok=5    changed=0    unreachable=0    failed=1    skipped=5    rescued=0    ignored=0   

Monday 15 June 2020  10:56:31 +0000 (0:00:01.977)       0:00:04.843 *********** 
=============================================================================== 
find interface name mapping and individual interface speed if defined ---------------------------------------------------------------------------------------------------------------- 1.98s
/var/johnar/sonic-mgmt/ansible/config_sonic_basedon_testbed.yml:83 -------------------------------------------------------------------------------------------------------------------------
topo_facts --------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 1.03s
/var/johnar/sonic-mgmt/ansible/config_sonic_basedon_testbed.yml:66 -------------------------------------------------------------------------------------------------------------------------
Gathering testbed information -------------------------------------------------------------------------------------------------------------------------------------------------------- 0.65s
/var/johnar/sonic-mgmt/ansible/config_sonic_basedon_testbed.yml:49 -------------------------------------------------------------------------------------------------------------------------
set_fact ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.07s
/var/johnar/sonic-mgmt/ansible/config_sonic_basedon_testbed.yml:74 -------------------------------------------------------------------------------------------------------------------------
fail --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.06s
/var/johnar/sonic-mgmt/ansible/config_sonic_basedon_testbed.yml:53 -------------------------------------------------------------------------------------------------------------------------
set default vm file path ------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.06s
/var/johnar/sonic-mgmt/ansible/config_sonic_basedon_testbed.yml:69 -------------------------------------------------------------------------------------------------------------------------
gather testbed VM informations ------------------------------------------------------------------------------------------------------------------------------------------------------- 0.06s
/var/johnar/sonic-mgmt/ansible/config_sonic_basedon_testbed.yml:78 -------------------------------------------------------------------------------------------------------------------------
set testbed_type --------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.05s
/var/johnar/sonic-mgmt/ansible/config_sonic_basedon_testbed.yml:56 -------------------------------------------------------------------------------------------------------------------------
set vm ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.05s
/var/johnar/sonic-mgmt/ansible/config_sonic_basedon_testbed.yml:60 -------------------------------------------------------------------------------------------------------------------------
Set default dut index ---------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
/var/johnar/sonic-mgmt/ansible/config_sonic_basedon_testbed.yml:44 -------------------------------------------------------------------------------------------------------------------------
set default testbed file ------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.03s
/var/johnar/sonic-mgmt/ansible/config_sonic_basedon_testbed.yml:39 -------------------------------------------------------------------------------------------------------------------------
The problem:
raise Exception("Something wrong when trying to find the portmap file, either the hwsku is not available or file location is not correct")
So, I thought the problem should be the portmap is disable or something? I need to enable it? But no idea how to fix this issue. And I didn't find similar issues on github.
Can anyone fix it?

**Comment by wangxin** [comment]
Please check the existence of port_config.ini file on your SONiC switch. Location of the file is:
`/usr/share/sonic/device/<platform>/<hwsku>/port_config.ini`.

* Replace `<platform>` with the actual platform of your SONiC switch. You can get its value from file `/host/machine.conf`. Looking for the value of key `onie_platform`.  In below example `/host/machine.conf`, the platform is `x86_64-mlnx_msn2700-r0`
```
...
onie_platform=x86_64-mlnx_msn2700-r0
...
```
* Replace `hwsku` with the actual hwsku of your SONiC switch. According to your log, it is `ACS-MSN2700`. Is this the correct hwsku of the system you are using? If not, please check your inventory file. Update the 'hwsku' var for your SONiC switch host in the inventory file. For example:

```
[sonic]
str-msn2700-01 ansible_host=172.28.55.15 hwsku=YourActualHwsku
```
Another example:
```
[sonic]
str-msn2700-01 ansible_host=172.28.55.15

[sonic:vars]
hwsku=YourActualHwsku
```

Please refer to ansible documentation for more details about how to specify host variables. https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#adding-variables-to-inventory
