### ISSUE TITLE
ACL test failed on t1 topology 

### ISSUE THREAD

**Issue by msosyak** [Azure/sonic-mgmt#1785]
**Description**
Part of ACL test fails on **t1** topology, but the same time passes on **t1-lag**. Looks like an issue with rout configuration fo t1.  I have checked t1 routes and was surprised that routes for t1 are statically configured on VMs. I thought that we use dynamically announced routes for all topologies.

**Steps to reproduce the issue:**
1. `py.test $PYTEST_COMMON_ARGS acl -v -rA -k acl and not egress and not reboot and not port_toggle`
2.
3.

**Describe the results you received:**

Here are the test with failed on t1:
```
FAILED acl/test_acl.py::TestBasicAcl::test_source_ip_match_forwarded[ingress-spine->tor]
FAILED acl/test_acl.py::TestBasicAcl::test_rules_priority_forwarded[ingress-spine->tor]
FAILED acl/test_acl.py::TestBasicAcl::test_dest_ip_match_forwarded[ingress-spine->tor]
FAILED acl/test_acl.py::TestBasicAcl::test_udp_source_ip_match_forwarded[ingress-spine->tor]
FAILED acl/test_acl.py::TestBasicAcl::test_icmp_source_ip_match_forwarded[ingress-spine->tor]
FAILED acl/test_acl.py::TestBasicAcl::test_l4_dport_match_forwarded[ingress-spine->tor]
FAILED acl/test_acl.py::TestBasicAcl::test_l4_sport_match_forwarded[ingress-spine->tor]
FAILED acl/test_acl.py::TestBasicAcl::test_l4_dport_range_match_forwarded[ingress-spine->tor]
FAILED acl/test_acl.py::TestBasicAcl::test_l4_sport_range_match_forwarded[ingress-spine->tor]
FAILED acl/test_acl.py::TestBasicAcl::test_ip_proto_match_forwarded[ingress-spine->tor]
FAILED acl/test_acl.py::TestBasicAcl::test_tcp_flags_match_forwarded[ingress-spine->tor]
FAILED acl/test_acl.py::TestIncrementalAcl::test_source_ip_match_forwarded[ingress-spine->tor]
FAILED acl/test_acl.py::TestIncrementalAcl::test_rules_priority_forwarded[ingress-spine->tor]
FAILED acl/test_acl.py::TestIncrementalAcl::test_dest_ip_match_forwarded[ingress-spine->tor]
FAILED acl/test_acl.py::TestIncrementalAcl::test_udp_source_ip_match_forwarded[ingress-spine->tor]
FAILED acl/test_acl.py::TestIncrementalAcl::test_icmp_source_ip_match_forwarded[ingress-spine->tor]
FAILED acl/test_acl.py::TestIncrementalAcl::test_l4_dport_match_forwarded[ingress-spine->tor]
FAILED acl/test_acl.py::TestIncrementalAcl::test_l4_sport_match_forwarded[ingress-spine->tor]
FAILED acl/test_acl.py::TestIncrementalAcl::test_l4_dport_range_match_forwarded[ingress-spine->tor]
FAILED acl/test_acl.py::TestIncrementalAcl::test_l4_sport_range_match_forwarded[ingress-spine->tor]
FAILED acl/test_acl.py::TestIncrementalAcl::test_ip_proto_match_forwarded[ingress-spine->tor]
FAILED acl/test_acl.py::TestIncrementalAcl::test_tcp_flags_match_forwarded[ingress-spine->tor]
```
All failed with similar errors like:
```
AssertionError: Received expected packet on port 0 for device 0, but it should have arrived on one of these ports: [27, 25, 26, 24, 31, 23, 30, 19, 18, 22, 29, 20, 28, 21, 16, 17]
```

**Describe the results you expected:**
Test passed

**Additional information you deem important:**

  Affects SONiC master and 201911

**Comment by msosyak** [comment]
@wangxin have you run the same test_functions mentioned above to verify https://github.com/Azure/sonic-mgmt/pull/1688?

**Comment by daall** [comment]
+1, I also just noticed this.

**Comment by wangxin** [comment]
@msosyak Yes, I have. Not sure why it's broken again. I'll check and feedback.

**Comment by wangxin** [comment]
@msosyak. I checked from my side. Egress ACL testing will fail on platforms that do not support egress ACL. Please check whether the platform you are using supports egress ACL.

Could you try limiting ACL test cases to "TestBasicAcl and ingress" to see if the results look better?

The result from my side is `1 failed, 45 passed, 322 deselected`.  The only failed case is `TestBasicAcl.test_source_ip_match_forwarded[ingress-tor->spine]`.  I suspect it was because the ACL configuration is not set down to ASIC yet since this case is the third one been executed. The two previous test cases are to verify that packets should be dropped:
* acl/test_acl.py::TestBasicAcl::test_unmatched_blocked[ingress-tor->spine]
* acl/test_acl.py::TestBasicAcl::test_unmatched_blocked[ingress-spine->tor]
They can pass anyway even if ACL configuration is not ready yet.

I can see two issues with the test_acl.py script from the observation:
1. Need to wait some time to run test cases after the ACL rules are loaded.
2. Need to adjust the test case execution sequence. For example, promote case `test_source_ip_match_forwarded` in front of `test_unmatched_blocked`

**Comment by msosyak** [comment]
@wangxin I use the following expression to limit acl tests `-k acl and not egress and not reboot and not port_toggle` and all failed tests have ingress direction. Will play with a timeout after rule applies, but for me is strange that the same tests that fail on `t1` pass on `t1-lag`(same hardware/no changes).

**Comment by rajneeshaec** [comment]
Ingress(spine---> tor) test cases are also failing for me

Here are the result given below:-

"FAILED acl/test_acl.py::TestBasicAcl::test_source_ip_match_forwarded[ingress-spine->tor]",
        "FAILED acl/test_acl.py::TestBasicAcl::test_rules_priority_forwarded[ingress-spine->tor]",
        "FAILED acl/test_acl.py::TestBasicAcl::test_dest_ip_match_forwarded[ingress-spine->tor]",
        "FAILED acl/test_acl.py::TestBasicAcl::test_udp_source_ip_match_forwarded[ingress-spine->tor]",
        "FAILED acl/test_acl.py::TestBasicAcl::test_icmp_source_ip_match_forwarded[ingress-spine->tor]",
        "FAILED acl/test_acl.py::TestBasicAcl::test_l4_dport_match_forwarded[ingress-spine->tor]",
        "FAILED acl/test_acl.py::TestBasicAcl::test_l4_sport_match_forwarded[ingress-spine->tor]",
        "FAILED acl/test_acl.py::TestBasicAcl::test_l4_dport_range_match_forwarded[ingress-spine->tor]",
        "FAILED acl/test_acl.py::TestBasicAcl::test_l4_sport_range_match_forwarded[ingress-spine->tor]",
        "FAILED acl/test_acl.py::TestBasicAcl::test_ip_proto_match_forwarded[ingress-spine->tor]",
        "FAILED acl/test_acl.py::TestBasicAcl::test_tcp_flags_match_forwarded[ingress-spine->tor]",
        "FAILED acl/test_acl.py::TestIncrementalAcl::test_source_ip_match_forwarded[ingress-spine->tor]",
        "FAILED acl/test_acl.py::TestIncrementalAcl::test_rules_priority_forwarded[ingress-spine->tor]",
        "FAILED acl/test_acl.py::TestIncrementalAcl::test_dest_ip_match_forwarded[ingress-spine->tor]",
        "FAILED acl/test_acl.py::TestIncrementalAcl::test_udp_source_ip_match_forwarded[ingress-spine->tor]",
        "FAILED acl/test_acl.py::TestIncrementalAcl::test_icmp_source_ip_match_forwarded[ingress-spine->tor]",
        "FAILED acl/test_acl.py::TestIncrementalAcl::test_l4_dport_match_forwarded[ingress-spine->tor]",
        "FAILED acl/test_acl.py::TestIncrementalAcl::test_l4_sport_match_forwarded[ingress-spine->tor]",
        "FAILED acl/test_acl.py::TestIncrementalAcl::test_l4_dport_range_match_forwarded[ingress-spine->tor]",
        "FAILED acl/test_acl.py::TestIncrementalAcl::test_l4_sport_range_match_forwarded[ingress-spine->tor]",
        "FAILED acl/test_acl.py::TestIncrementalAcl::test_ip_proto_match_forwarded[ingress-spine->tor]",
        "FAILED acl/test_acl.py::TestIncrementalAcl::test_tcp_flags_match_forwarded[ingress-spine->tor]",
        "============ 22 failed, 70 passed, 276 deselected in 914.12 seconds ============"
    ]
}

all test cases failed because of the same assertion error

AssertionError: Received expected packet on port 0 for device 0, but it should have arrived on one of these ports: [27, 25, 26, 24, 31, 23, 30, 19, 18, 22, 29, 20, 28, 21, 16, 17]

*Note:- * All tor to spine acl test cases are passing

**Comment by alanC-Cameo** [comment]
same fail as rajneeshaec on master branch 2020/Jul/14 commit.

"=========================== short test summary info ============================",
"FAILED acl/test_acl.py::TestBasicAcl::test_source_ip_match_forwarded[ingress-spine->tor]",
"FAILED acl/test_acl.py::TestBasicAcl::test_rules_priority_forwarded[ingress-spine->tor]",
"FAILED acl/test_acl.py::TestBasicAcl::test_dest_ip_match_forwarded[ingress-spine->tor]",
"FAILED acl/test_acl.py::TestBasicAcl::test_udp_source_ip_match_forwarded[ingress-spine->tor]",
"FAILED acl/test_acl.py::TestBasicAcl::test_icmp_source_ip_match_forwarded[ingress-spine->tor]",
"FAILED acl/test_acl.py::TestBasicAcl::test_l4_dport_match_forwarded[ingress-spine->tor]",
"FAILED acl/test_acl.py::TestBasicAcl::test_l4_sport_match_forwarded[ingress-spine->tor]",
"FAILED acl/test_acl.py::TestBasicAcl::test_l4_dport_range_match_forwarded[ingress-spine->tor]",
"FAILED acl/test_acl.py::TestBasicAcl::test_l4_sport_range_match_forwarded[ingress-spine->tor]",
"FAILED acl/test_acl.py::TestBasicAcl::test_ip_proto_match_forwarded[ingress-spine->tor]",
"FAILED acl/test_acl.py::TestBasicAcl::test_tcp_flags_match_forwarded[ingress-spine->tor]",
"FAILED acl/test_acl.py::TestIncrementalAcl::test_source_ip_match_forwarded[ingress-spine->tor]",
"FAILED acl/test_acl.py::TestIncrementalAcl::test_rules_priority_forwarded[ingress-spine->tor]",
"FAILED acl/test_acl.py::TestIncrementalAcl::test_dest_ip_match_forwarded[ingress-spine->tor]",
"FAILED acl/test_acl.py::TestIncrementalAcl::test_udp_source_ip_match_forwarded[ingress-spine->tor]",
"FAILED acl/test_acl.py::TestIncrementalAcl::test_icmp_source_ip_match_forwarded[ingress-spine->tor]",
"FAILED acl/test_acl.py::TestIncrementalAcl::test_l4_dport_match_forwarded[ingress-spine->tor]",
"FAILED acl/test_acl.py::TestIncrementalAcl::test_l4_sport_match_forwarded[ingress-spine->tor]",
"FAILED acl/test_acl.py::TestIncrementalAcl::test_l4_dport_range_match_forwarded[ingress-spine->tor]",
"FAILED acl/test_acl.py::TestIncrementalAcl::test_l4_sport_range_match_forwarded[ingress-spine->tor]",
"FAILED acl/test_acl.py::TestIncrementalAcl::test_ip_proto_match_forwarded[ingress-spine->tor]",
"FAILED acl/test_acl.py::TestIncrementalAcl::test_tcp_flags_match_forwarded[ingress-spine->tor]",
"====== 22 failed, 70 passed, 276 deselected, 3 warnings in 489.03 seconds ======"

"msg = 'Received expected packet on port 4 for device 0, but it should have arrived on one of these ports: [27, 22, 29, 25, 2..."

**Comment by William-zx** [comment]
@wangxin 
The t0 and t1-lag routes have been changed after replacing static routes on VM with exabgp announced routes, But t1 not. So the DST_IP_TOR = '192.168.0.1' is point to the spine. This caused the acl testing failed on all spine->tor direction on t1 topology.

**Comment by wangxin** [comment]
@William-zx Thanks for the analysis! I'll look into this.
