### ISSUE TITLE
Variable is not defined in test_dhcp_relay.py module

### ISSUE THREAD

**Issue by yvolynets-mlnx** [Azure/sonic-mgmt#1793]
**Description**
If there will be no route to DHCP server during run any of "sonic-mgmt/tests/dhcp_relay/test_dhcp_relay.py" test cases , failure reasone message will be displayed, but will fail because of variable "result" is not defined.

    @pytest.fixture(scope="module") 
    def validate_dut_routes_exist(duthost, dut_dhcp_relay_data): 
        """Fixture to valid a route to each DHCP server exist 
        """ 
        dhcp_servers = set() 
        for dhcp_relay in dut_dhcp_relay_data: 
            dhcp_servers |= set(dhcp_relay['downlink_vlan_iface']['dhcp_server_addrs']) 

        for dhcp_server in dhcp_servers: 
            rtInfo = duthost.get_ip_route_info(ipaddress.ip_address(dhcp_server)) 
            assert len(rtInfo["nexthops"]) > 0, \ 
>               "Failed to find route to DHCP server '{0}' with error '{1}".format(dhcp_server, result["stderr"]) 
E           NameError: global name 'result' is not defined 

**Steps to reproduce the issue:**
1. Run "sonic-mgmt/tests/dhcp_relay/test_dhcp_relay.py" test cases

**Describe the results you received:**
Function "validate_dut_routes_exist" failes on routes verirication

**Describe the results you expected:**
Test failure message should be correctly displayed

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
duplicated #1792
