### ISSUE TITLE
ACL table test failure due to JSON file format issue

### ISSUE THREAD

**Issue by stcheng** [Azure/sonic-mgmt#182]
https://github.com/Azure/sonic-mgmt/blob/master/ansible/roles/test/templates/acltb_test_rules.j2

In this file, several arrays are appended with each other and the format is not correct so that after the JSON file is generated, it cannot be applied.

```
root@str-msn2700-05:/etc/swss/config.d# swssconfig acltb_test_rules.json
Exception caught:parse error - unexpected ','; expected end of input
```

**Comment by stcheng** [comment]
@andriymoroz-mlnx could you take a look at this?

**Comment by andriymoroz-mlnx** [comment]
Could you send me the generated json file?

**Comment by stcheng** [comment]
```
    {
        "ACL_RULE_TABLE:ACL_Testbed_Test_Table:RuleB2_Priority_test_permit": {
            "priority" : "51",
            "src_ip" : "10.0.0.3",
            "packet_action" : "forward"
        },
        "OP": "SET"
    }
]
[
    {
        "ACL_RULE_TABLE:ACL_Testbed_Test_Table:Rule01_SRC_IP_test": {
            "priority" : "50",
            "src_ip" : "10.0.0.2",
            "packet_action" : "drop"
        },
        "OP": "SET"
    },
```

between two sets of rules, they are divided by `]` and `[`, which cannot be parsed by swssconfig.

**Comment by andriymoroz-mlnx** [comment]
This is not supposed to be generated...
The code inside loop should be inserted only once for loop.index==2

**Comment by stcheng** [comment]
@andriymoroz-mlnx it seems to be jinja2 version issue: https://github.com/Azure/sonic-buildimage/pull/618.
