### ISSUE TITLE
Run the first spytest script with error "AttributeError: 'NoneType' object has no attribute 'get_testbed_vars'"

### ISSUE THREAD

**Issue by ljyfree** [Azure/sonic-mgmt#1832]
**Description**
Try Spytest for test_box_services.py::test_ft_system_uptime but fail

**Steps to reproduce the issue:**
1. CentOS Linux release 7.8.2003 (Core)
2.git clone https://github.com/Azure/sonic-mgmt.git
3.cd ~/sonic-mgmt/spytest/bin
4.
```
yum install python-pip -y
pip install wheel
pip install -r requirements0.txt
```
5.cd ~/sonic-mgmt/spytest/tests/system
6. execute one case

![image](https://user-images.githubusercontent.com/13234976/86113397-ca312f00-bafb-11ea-9d8a-e9fd227ebce3.png)

**Describe the results you received:**
```
    def get_testbed_vars():
        """
        returns the testbed variables in a dictionary
        :return: testbed variables dictionary
        :rtype: dict
        """
>       return getwa().get_testbed_vars()
E       AttributeError: 'NoneType' object has no attribute 'get_testbed_vars'
```

**Describe the results you expected:**
Should not report error

**Comment by lguohan** [comment]
I do not think we support centos. can you follow testbed setup doc to setup the testbed?
