### ISSUE TITLE
How to run the scripts under sonic-mgmt/tests/

### ISSUE THREAD

**Issue by ljyfree** [Azure/sonic-mgmt#1863]
Hi all,

    I want to run the test scripts under sonic-mgmt/tests/ but don't know how to. Could anyone give me some guidance step-by-step or show me where I can find guidance doc?
    Looks like the way to run the cases under sonic-mgmt/ansible/roles/test/files/ptftests/ did not work here.
```
$ ansible-playbook -i lab -l str-msn2700-01 test_sonic.yml -e testbed_name=ptf1-m -e ptf_host=ptf1 testcase_name=arp -vvv
```

**Comment by ljyfree** [comment]
What's the relationship between `sonic-mgmt/ansible/roles/test/files/ptftests/` and `https://github.com/Azure/sonic-mgmt/tree/master/tests`?

**Comment by stephengzh** [comment]
The guidance is updated on: https://github.com/Azure/sonic-mgmt/blob/master/tests/README.md

**Comment by ljyfree** [comment]
Thanks for your reply.
One more quick question, how to define "testbed"? Still deployed by ansible? 

```
./run_tests.sh -d <dut_name> -n <testbed_name> [-s ] -t t1
```

**Comment by stephengzh** [comment]
@ljyfree The testbed setup should be still defined in Ansible. Because Ansible playbook for running test cases is now deprecated.

**Comment by ljyfree** [comment]
Thanks a lot!
