### ISSUE TITLE
sonic-mgmt repo not found in sonic-mgmt docker 

### ISSUE THREAD

**Issue by richawil7** [Azure/sonic-mgmt#1876]
**Description**
Following the testbed setup instructions from github.com/Azure/sonic-mgmt/blob/master/ansible/doc/README.testbed.Setup.md.  
Successfully built the sonic-mgmt docker image.  
But when the image is run, the sonic-mgmt repository is not included

**Steps to reproduce the issue:**
    1.git clone --recursive https://github.com/Azure/sonic-buildimage.git
      make configure PLATFORM=generic
      make target/docker-sonic-mgmt.gz
    2.  docker load -i target/docker-sonic-mgmt.gz
       docker run -it docker-sonic-mgmt bash
       cd ~/sonic-mgmt

**Describe the results you received:**
    caglab@d77ec686523e:~$ cd /var
    caglab@d77ec686523e:/var$ ls
    backups  cache  caglab  lib  local  lock  log  mail  opt  run  spool  tmp
    caglab@d77ec686523e:/var$ cd caglab
    caglab@d77ec686523e:~$ ls
    azure-cli_bundle.tar.gz  azure-cli_bundle_2.0.10  bin  env-201811  lib

**Describe the results you expected:**
I expected to see the directory /var/caglab/sonic-mgmt

**Comment by ljyfree** [comment]
Hi

    I was told that the sonic-mgmt repo had been removed from docker. So it need  to download and copy into mgmt docker by yourself.

**Comment by alanC-Cameo** [comment]
same here even used the "docker run -v $PWD:/data -it docker-sonic-mgmt bash" which mentioned as a solution in ljyfree's previous issue report.

My 201811 docker-sonic-mgmt woks fine but 201911 just missed the sonic-mgmt/ folder after entering docker. Not sure which steps I missed?

**Comment by alanC-Cameo** [comment]
I have figured out what it is.

Simply done below in your host.
1. cd ~
2. git clone --recurse-submodules https://github.com/Azure/sonic-mgmt.git
3. docker run -v $PWD:/var/caglab/sonic-mgmt -it docker-sonic-mgmt bash

now you have sonic-mgmt/ in your docker ~

**Comment by lguohan** [comment]
@daall , have we removed the clone sonic-mgmt repo in the docker-sonic-mgmt, is this expected?

**Comment by daall** [comment]
That's correct, this is expected behavior. I'll add this to the `sonic-mgmt` README.
