### ISSUE TITLE
test_vlan.py may unintentionally add a port-channel member port as a VLAN member

### ISSUE THREAD

**Issue by rck-innovium** [Azure/sonic-mgmt#1882]
**Description**
 _test_vlan_ verifies the VLAN functionality.
https://github.com/Azure/sonic-mgmt/blob/master/tests/vlan/test_vlan.py

It selects four ports from the device and adds them as VLAN members. 
The script creates a candidate list of ports consisting of all port-channels and ports from the config whose links are up. From this candidate list, the first four ports are picked.

The candidate list of ports (stored in variable _ports_) should be either Port-channels or front panel ports that are not members of any port-channel.
However, in the current script, _ports_ contains port-channels and all front-panel ports including ports that are members of port-channels.
Depending on the order in which the ports are present in the python dictionary,  the test could end up unintentionally adding a port-channel member port as a VLAN member. 
Ideally, port-channel members should not be added to a VLAN, only the parent port-channel interface should be added to the VLAN.

```
 42     # when running on t0 we can use the portchannel members
 43     if config_portchannels:
 44         for po in config_portchannels.keys()[:2]:
 45             port = config_portchannels[po]['members'][0]
 46             vlan_ports_list.append({
 47                 'dev' : po,
 48                 'port_index' : config_port_indices[port],
 49                 'pvid' : pvid_cycle.next(),
 50                 'permit_vlanid' : { vid : {
 51                     'peer_ip' : '192.168.{}.{}'.format(vid, 2 + config_port_indices.keys().index(port)),
 52                     'remote_ip' : '{}.1.1.{}'.format(vid, 2 + config_port_indices.keys().index(port))
 53                     } for vid in vlan_id_list }
 54             })
 55
 56     ports = [ port for port in config_ports
 57         if config_port_indices[port] in ptf_ports_available_in_topo and config_ports[port].get('admin_status',     'down') == 'up' ]
 58
 59     for port in ports[:4]:
 60         vlan_ports_list.append({
 61             'dev' : port,
 62             'port_index' : config_port_indices[port],
 63             'pvid' : pvid_cycle.next(),
 64             'permit_vlanid' : { vid : {
 65                 'peer_ip' : '192.168.{}.{}'.format(vid, 2 + config_port_indices.keys().index(port)),
 66                 'remote_ip' : '{}.1.1.{}'.format(vid, 2 + config_port_indices.keys().index(port))
 67                 } for vid in vlan_id_list }
 68         })
 69
 70     return vlan_ports_list
```

**Steps to reproduce the issue:**
1. Run vlan/test_vlan.py  on t0 testbed
2. Reproduction depends on the internal python dictionary hashing. If any of the port-channel member ports occur among the first four entries, then the script would fail.

**Describe the results you received:**
On some topologies, the test fails. This happens if any of the port-channel member ports occur among the first four entries in the script variable _ports_

**Describe the results you expected:**
Port-channel member ports should not be added as VLAN members.

**Fix for the issue:**
The below patch fixed the issue.

```
--- a/tests/vlan/test_vlan.py
+++ b/tests/vlan/test_vlan.py
@@ -36,9 +36,10 @@ def vlan_ports_list(cfg_facts, ptfhost):
     config_portchannels = cfg_facts.get('PORTCHANNEL', {})
     config_port_indices = cfg_facts['port_index_map']
     ptf_ports_available_in_topo = ptfhost.host.options['variable_manager'].extra_vars.get("ifaces_map")
+    config_port_channel_member_ports = [port_channel_member[1].keys()[0] for port_channel_member in config_portchannels.items()]
 
    pvid_cycle = itertools.cycle(vlan_id_list)

     # when running on t0 we can use the portchannel members
     if config_portchannels:
         for po in config_portchannels.keys()[:2]:
@@ -54,7 +55,7 @@ def vlan_ports_list(cfg_facts, ptfhost):
             })
 
     ports = [ port for port in config_ports
-        if config_port_indices[port] in ptf_ports_available_in_topo and config_ports[port].get('admin_status', 'down') == 'up' ]
+        if config_port_indices[port] in ptf_ports_available_in_topo and config_ports[port].get('admin_status', 'down') == 'up' and port not in config_port_channel_member_ports]
 
     for port in ports[:4]:
         vlan_ports_list.append({
 
```

**Comment by ljyfree** [comment]
Hi rck

   Could you please show me how to "Run vlan/test_vlan.py on t0 testbed"?

**Comment by ljyfree** [comment]
![微信图片_20200713141714](https://user-images.githubusercontent.com/13234976/87276775-9ef30a80-c513-11ea-8df1-f7c300622e1c.jpg)

**Comment by rck-innovium** [comment]
> Hi rck
> 
> Could you please show me how to "Run vlan/test_vlan.py on t0 testbed"?

```
docker exec -it docker-sonic-mgmt bash
cd sonic-mgmt/tests/


py.test vlan/test_vlan.py --testbed=vms_centec-t0 --inventory=/var/admin/sonic-mgmt/ansible/inventory --testbed_file=../ansible/testbed.csv --host-pattern=vms_centec-t0 --module-path=../ansible/library -v --log-level=info
```

**Comment by ljyfree** [comment]
Hi rck

   What are the setup steps before run the "py.test" command above?

**Comment by ljyfree** [comment]
Hi rck-innovium

     I am working on running https://github.com/Azure/sonic-mgmt/blob/master/tests/vlan/test_vlan.py too.  There was no attr “members” for the specific portchannel port in table 'PORTCHANNEL' , so it would report "KeyError:'members'".
     Could you please share the content of table 'PORTCHANNEL' on your side?
