### ISSUE TITLE
Could not find where the “ansible_Ethernet0” was defined during run testcase "fdb" and "fdb_mac_expire"

### ISSUE THREAD

**Issue by ljyfree** [Azure/sonic-mgmt#1884]
**Description**

**Steps to reproduce the issue:**
1. run testcase: fdb or fdb_mac_expire
2.
3.

**Describe the results you received:**
![ansible_error](https://user-images.githubusercontent.com/13234976/87275133-1d4dad80-c510-11ea-9330-d22eef953d11.jpg)

I could not find where “ansible_Ethernet0” was defined.

**Comment by lguohan** [comment]
ansible_Ethernet0 is defined in ansible_facts. if you see this error, it mostly likely means your do not Ethernet0 on your DUT. Usually, this is a image isue. can you check if your image has Ethernet0 created before you run the test?

**Comment by ljyfree** [comment]
Hi han

    Where could I find "ansible_facts"? Were they recorded in a file？
