### ISSUE TITLE
Errors when running cases.

### ISSUE THREAD

**Issue by stephengzh** [Azure/sonic-mgmt#1947]
Hey guys, 
When I ran some test cases, an error always appeared which disturbed me:

py.test fdb/test_fdb.py --testbed=vms-kvm-t0 --inventory=/var/johnar/sonic-mgmt/ansible/lab --testbed_file=../ansible/testbed.csv --host-pattern=vms-kvm-t0 --module-path=../ansible/library -v

        if (res.is_failed or 'exception' in res) and not module_ignore_errors:
>           raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
E           RunAnsibleModuleFail: run module script failed, Ansible Results =>
E           {
E               "changed": true, 
E               "msg": "non-zero return code", 
E               "rc": 1, 
E               "stderr": "OpenSSH_7.2p2 Ubuntu-4ubuntu2.8, OpenSSL 1.0.2g  1 Mar 2016\r\ndebug1: Reading configuration data /var/johnar/.ssh/config\r\ndebug1: /var/johnar/.ssh/config line 1: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 6336\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\nShared connection to 172.28.55.15 closed.\r\n", 
E               "stderr_lines": [
E                   "OpenSSH_7.2p2 Ubuntu-4ubuntu2.8, OpenSSL 1.0.2g  1 Mar 2016", 
E                   "debug1: Reading configuration data /var/johnar/.ssh/config", 
E                   "debug1: /var/johnar/.ssh/config line 1: Applying options for *", 
E                   "debug1: Reading configuration data /etc/ssh/ssh_config", 
E                   "debug1: /etc/ssh/ssh_config line 19: Applying options for *", 
E                   "debug1: auto-mux: Trying existing master", 
E                   "debug2: fd 3 setting O_NONBLOCK", 
E                   "debug2: mux_client_hello_exchange: master version 4", 
E                   "debug3: mux_client_forwards: request forwardings: 0 local, 0 remote", 
E                   "debug3: mux_client_request_session: entering", 
E                   "debug3: mux_client_request_alive: entering", 
E                   "debug3: mux_client_request_alive: done pid = 6336", 
E                   "debug3: mux_client_request_session: session request sent", 
E                   "debug1: mux_client_request_session: master session id: 2", 
E                   "debug3: mux_client_read_packet: read header failed: Broken pipe", 
E                   "debug2: Received exit status from master 1", 
E                   "Shared connection to 172.28.55.15 closed."
E               ], 
E               "stdout": "", 
E               "stdout_lines": []
E           }

Can anyone fix this problem? It is hard for me to understand.

**Comment by stephengzh** [comment]
This issue has been fixed.

**Comment by samaity** [comment]
> This issue has been fixed.

@stephengzh, I am facing a similar kind of issue. Could you kindly provide the details of how you fixed this issue? Thanks!
