### ISSUE TITLE
pytest ptf "host unreachable" in several test cases on latest master branch (Jul/14/2020, commit aec9f58f906feb20d4024d6686603d51649bac9b)

### ISSUE THREAD

**Issue by alanC-Cameo** [Azure/sonic-mgmt#1961]
**Description**
I have encountered a ptf host unreachable issue on several test cases while I'm sure that the ptf is actually accessible and well defined in file veos and lab.

**Steps to reproduce the issue:**
1. ansible-playbook -i veos -l lab-esc601-32-MAX test_sonic.yml -e testbed_name=vms-601-t1 -e testbed_file=testbed.csv -e testbed_type=t1 -e ptf_host=ptf_vms6-1 -vvvv -e testcase_name=decap

**Describe the results you received:**
TASK [test : debug] *************************************************************************************************************************************************************************************************************************
task path: /var/alan_chen/sonic-mgmt/ansible/roles/test/tasks/pytest_runner.yml:68
Friday 24 July 2020  08:10:12 +0000 (0:00:08.081)       0:00:30.668 ***********
ok: [lab-esc601-32-MAX] => {
    "msg": [
        "============================= test session starts ==============================",
        "platform linux2 -- Python 2.7.12, pytest-4.6.5, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python",
        "cachedir: .pytest_cache",
        "metadata: {'Python': '2.7.12', 'Platform': 'Linux-4.15.0-111-generic-x86_64-with-Ubuntu-16.04-xenial', 'Packages': {'py': '1.9.0', 'pytest': '4.6.5', 'pluggy': '0.13.1'}, 'Plugins': {u'repeat': u'0.8.0', u'xdist': u'1.28.0', u'ansible': u'2.2.2', u'forked': u'1.2.0', u'html': u'1.22.1', u'metadata': u'1.10.0'}}",
        "ansible: 2.8.12",
        "rootdir: /var/alan_chen/sonic-mgmt/tests, inifile: pytest.ini",
        "plugins: ansible-2.2.2, metadata-1.10.0, html-1.22.1, forked-1.2.0, xdist-1.28.0, repeat-0.8.0",
        "collecting ... collected 1 item",
        "",
        **_"decap/test_decap.py::test_decap ERROR                                    [100%]",_**
        "",
        "==================================== ERRORS ====================================",
        "_________________________ ERROR at setup of test_decap _________________________",
        "",
        "ptfhost = <tests.common.devices.PTFHost object at 0x7f5d9171e250>",
        "",
        "    @pytest.fixture(scope=\"session\", autouse=True)",
        "    def change_mac_addresses(ptfhost):",
        "        \"\"\"",
        "            Change MAC addresses (unique) on PTF host.",
        "    ",
        "            Args:",
        "                ptfhost (AnsibleHost): Packet Test Framework (PTF)",
        "    ",
        "            Returns:",
        "                None",
        "        \"\"\"",
        "        logger.info(\"Change interface MAC addresses on ptfhost '{0}'\".format(ptfhost.hostname))",
        **">       ptfhost.script(CHANGE_MAC_ADDRESS_SCRIPT)",**
        "",
        "common/fixtures/ptfhost_utils.py:82: ",
        "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ",
        "common/devices.py:77: in _run",
        "    res = self.module(*module_args, **complex_args)[self.hostname]",
        "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ",
        "",
        "self = <pytest_ansible.module_dispatcher.v28.ModuleDispatcherV28 object at 0x7f5d8f27e950>",
        "module_args = ('scripts/change_mac.sh',)",
        "complex_args = {'_raw_params': 'scripts/change_mac.sh'}, hosts = [ptf_vms6-1]",
        "no_hosts = False",
        "args = ['pytest-ansible', '-vvvvv', 'ptf_vms6-1', '--connection=smart', '--become', '--become-method=sudo', ...]",
        "argument = 'module-path', arg_value = '../ansible/library'",
        "cb = <pytest_ansible.module_dispatcher.v28.ResultAccumulator object at 0x7f5d8f27ecd0>",
        "kwargs = {'inventory': <ansible.inventory.manager.InventoryManager object at 0x7f5d90095850>, 'loader': <ansible.parsing.datalo...ass': None}, 'stdout_callback': <pytest_ansible.module_dispatcher.v28.ResultAccumulator object at 0x7f5d8f27ecd0>, ...}",
        "play_ds = {'become': True, 'become_user': 'root', 'gather_facts': 'no', 'hosts': 'ptf_vms6-1', ...}",
        "play = pytest-ansible",
        "",
        "    def _run(self, *module_args, **complex_args):",
        "        \"\"\"Execute an ansible adhoc command returning the result in a AdhocResult object.\"\"\"",
        "        # Assemble module argument string",
        "        if module_args:",
        "            complex_args.update(dict(_raw_params=' '.join(module_args)))",
        "    ",
        "        # Assert hosts matching the provided pattern exist",
        "        hosts = self.options['inventory_manager'].list_hosts()",
        "        no_hosts = False",
        "        if len(hosts) == 0:",
        "            no_hosts = True",
        "            warnings.warn(\"provided hosts list is empty, only localhost is available\")",
        "    ",
        "        self.options['inventory_manager'].subset(self.options.get('subset'))",
        "        hosts = self.options['inventory_manager'].list_hosts(self.options['host_pattern'])",
        "        if len(hosts) == 0 and not no_hosts:",
        "            raise ansible.errors.AnsibleError(\"Specified hosts and/or --limit does not match any hosts\")",
        "    ",
        "        # Log the module and parameters",
        "        log.debug(\"[%s] %s: %s\" % (self.options['host_pattern'], self.options['module_name'], complex_args))",
        "    ",
        "        # Pass along cli options",
        "        args = ['pytest-ansible', '-vvvvv', self.options['host_pattern']]",
        "        for argument in ('connection', 'user', 'become', 'become_method', 'become_user', 'module_path'):",
        "            arg_value = self.options.get(argument)",
        "            argument = argument.replace('_', '-')",
        "    ",
        "            if arg_value in (None, False):",
        "                continue",
        "    ",
        "            if arg_value is True:",
        "                args.append('--{0}'.format(argument))",
        "            else:",
        "                args.append('--{0}={1}'.format(argument, arg_value))",
        "    ",
        "        # Use Ansible's own adhoc cli to parse the fake command line we created and then save it",
        "        # into Ansible's global context",
        "        adhoc = AdHocCLI(args)",
        "        adhoc.parse()",
        "    ",
        "        # And now we'll never speak of this again",
        "        del adhoc",
        "    ",
        "        # Initialize callback to capture module JSON responses",
        "        cb = ResultAccumulator()",
        "    ",
        "        kwargs = dict(",
        "            inventory=self.options['inventory_manager'],",
        "            variable_manager=self.options['variable_manager'],",
        "            loader=self.options['loader'],",
        "            stdout_callback=cb,",
        "            passwords=dict(conn_pass=None, become_pass=None),",
        "        )",
        "    ",
        "        # create a pseudo-play to execute the specified module via a single task",
        "        play_ds = dict(",
        "            name=\"pytest-ansible\",",
        "            hosts=self.options['host_pattern'],",
        "            become=self.options['become'],",
        "            become_user=self.options['become_user'],",
        "            gather_facts='no',",
        "            tasks=[",
        "                dict(",
        "                    action=dict(",
        "                        module=self.options['module_name'], args=complex_args",
        "                    ),",
        "                ),",
        "            ]",
        "        )",
        "        log.debug(\"Play(%s)\", play_ds)",
        "        play = Play().load(play_ds, variable_manager=self.options['variable_manager'], loader=self.options['loader'])",
        "    ",
        "        # now create a task queue manager to execute the play",
        "        tqm = None",
        "        try:",
        "            log.debug(\"TaskQueueManager(%s)\", kwargs)",
        "            tqm = TaskQueueManager(**kwargs)",
        "            tqm.run(play)",
        "        finally:",
        "            if tqm:",
        "                tqm.cleanup()",
        "    ",
        "        # Log the results",
        "        log.debug(cb.results)",
        "    ",
        "        # Raise exception if host(s) unreachable",
        "        # FIXME - if multiple hosts were involved, should an exception be raised?",
        "        if cb.unreachable:",
        ">           raise AnsibleConnectionFailure(\"Host unreachable\", dark=cb.unreachable, contacted=cb.contacted)",
        **"E           AnsibleConnectionFailure: Host unreachable",**
        "",
        "/usr/local/lib/python2.7/dist-packages/pytest_ansible-2.2.2-py2.7.egg/pytest_ansible/module_dispatcher/v28.py:147: AnsibleConnectionFailure",
        "=============================== warnings summary ===============================",
        "/usr/local/lib/python2.7/dist-packages/_pytest/cacheprovider.py:127",
        "  /usr/local/lib/python2.7/dist-packages/_pytest/cacheprovider.py:127: PytestCacheWarning: could not create cache path /var/alan_chen/sonic-mgmt/tests/.pytest_cache/v/cache/stepwise",
        "    self.warn(\"could not create cache path {path}\", path=path)",
        "",
        "/usr/local/lib/python2.7/dist-packages/_pytest/cacheprovider.py:127",
        "  /usr/local/lib/python2.7/dist-packages/_pytest/cacheprovider.py:127: PytestCacheWarning: could not create cache path /var/alan_chen/sonic-mgmt/tests/.pytest_cache/v/cache/nodeids",
        "    self.warn(\"could not create cache path {path}\", path=path)",
        "",
        "/usr/local/lib/python2.7/dist-packages/_pytest/cacheprovider.py:127",
        "  /usr/local/lib/python2.7/dist-packages/_pytest/cacheprovider.py:127: PytestCacheWarning: could not create cache path /var/alan_chen/sonic-mgmt/tests/.pytest_cache/v/cache/lastfailed",
        "    self.warn(\"could not create cache path {path}\", path=path)",
        "",
        "-- Docs: https://docs.pytest.org/en/latest/warnings.html",
        "=========================== short test summary info ============================",
        "ERROR decap/test_decap.py::test_decap - AnsibleConnectionFailure: Host unreac...",
        "===================== 3 warnings, 1 error in 4.57 seconds ======================"
    ]
}

**Additional information you deem important:**
master branch (Jul/14/2020, commit aec9f58f906feb20d4024d6686603d51649bac9b)

[ptf]
ptf_vms6-1    ansible_host=192.168.3.19 ansible_ssh_user=root ansible_ssh_password=root

**Comment by yxieca** [comment]
@alanC-Cameo can you retry with latest master again? I suspect the issue is addressed by #1897

**Comment by alanC-Cameo** [comment]
tks yxieca for the reply.
unfortunately the fix#1897 changes nothing in my case.

here is a list of my fail cases due to the same "ptf host unreachable" issue.
-bgp_speaker
-decap
-dhcp_relay
-everflow_testbed
-lag_2
-mtu
-ntp
-dip_sip
-vxlan_decap

**Comment by alanC-Cameo** [comment]
tks for support and I found it is caused by a typo of "ansible_ssh_password", revised to "ansible_ssh_pass" and works.
