### ISSUE TITLE
How to print additional debug info as I set?

### ISSUE THREAD

**Issue by ljyfree** [Azure/sonic-mgmt#1978]
**Description**

**Steps to reproduce the issue:**
1.run the case
```
./run_tests.sh -d vlab-01 -f ../ansible/vtestbed.csv -i ../ansible/lab -n vms-kvm-t1 -d vlab-01 -l DEBUG -t t1,any -u -x -c arp/test_neighbor_mac_noptf.py
```
2.The log print on terminal show that 
```
Failed :Failed to find a routed interface in '{}'
```
3.I doubt if the regular expression match the output for "show interface status"
```
admin@vlab-01:~$ show interface status
      Interface            Lanes    Speed    MTU    FEC           Alias             Vlan    Oper    Admin    Type    Asym PFC
---------------  ---------------  -------  -----  -----  --------------  ---------------  ------  -------  ------  ----------
      Ethernet0      25,26,27,28      40G   9100    N/A    fortyGigE0/0           routed    up       up     N/A         off
      Ethernet4      29,30,31,32      40G   9100    N/A    fortyGigE0/4           routed    up       up     N/A         off
```
4. So I wanted to add some print in "/var/johnar/sonic-mgmt/ansible/library/show_interface.py".
5. No matter adding "print" or "logger.info" , no corresponding debug msg print on terminal.

My question are:
(1)Anyone encountered the same problem "Failed to find a routed interface in '{}'"？
(2)How add extra debug info in python script to locate problem？

BTW， the log file in tests/logs did not record extra debug info as I set "print" or "logger.info".

**Comment by ljyfree** [comment]
I have confirmed that the script in tests could print msg via logger.info().
However it did not work for the script under https://github.com/Azure/sonic-mgmt/tree/master/ansible/library.

**Comment by wangxin** [comment]
The "show_interface.py" is a customized ansible module. It is executed on remote host. It's logs can't be captured in the test script log. This is a limitation of running ansible modules. To debug issues of the test script, you have to explicitly return the debug information in the ansible module using pattern like below:
```
self.module.fail_json(msg="Your debug info")
```

**Comment by ljyfree** [comment]
I will try it and thanks!
