### ISSUE TITLE
[sonic-installer] "sonic_installer binary_version" deprecated command

### ISSUE THREAD

**Issue by shlomibitton** [Azure/sonic-mgmt#2017]
**Description**

"sonic_installer binary_version..." deprecated command failing regression auto deploy image based on master branch.

**Steps to reproduce the issue:**
1. Run the command "sonic_installer binary_version..." on a switch with installed image based on master branch.

**Describe the results you received:**

Error: No such command "binary_version"

**Describe the results you expected:**

Successful deploy regardless the used branch on DUT.

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by wangxin** [comment]
It looks like `sonic_installer binary_version` will be deprecated. Command `sonic-installer binary-version` should be able to work.

**Comment by shlomibitton** [comment]
@wangxin should we adapt the sonic-mgmt code base to work with the old type as well for supporting testing of images based on 201911 branch?

**Comment by wangxin** [comment]
The sonic-mgmt master branch is used for both SONiC master and 201911 testing. However, the 201911 image only supports the old style sonic_installer command. I am afraid that before the sonic-mgmt 201911 branch is out, we need to adapt the code to work for both types.
