### ISSUE TITLE
Ansible ping fails on Arista VM

### ISSUE THREAD

**Issue by richawil7** [Azure/sonic-mgmt#2056]
**Description**
Unable to "ansible ping" a VM.  Host shows the VM is running.  Able to ping the VM and manually SSH to the VM.

**Steps to reproduce the issue:**
1. Created VMs using ./testbed-cli.sh start-vms server_1 password.txt
2. Ran ping command: ansible -m ping -i veos server_1
3. Ping fails

**Describe the results you received:**
<10.250.0.2> (1, '\n> /bin/sh -c \'echo PLATFORM; uname; echo FOUND; command -v \'"\'"\'/usr/bin/python\'"\'"\'; command -v \'"\'"\'python3.7\'"\'"\'; command -v \'"\'"\'python3.6\'"\'"\'; command -v \'"\'"\'python3.5\'"\'"\'; command -v \'"\'"\'python2.7\'"\'"\'; command -v \'"\'"\'python2.6\'"\'"\'; command -v \'"\'"\'/usr/libexec/platform-python\'"\'"\'; command -v \'"\'"\'/usr/bin/python3\'"\'"\'; command -v \'"\'"\'python\'"\'"\'; echo ENDFOUND && sleep 0\'\n% Invalid input at line 1\n', '')
<10.250.0.2> Failed to connect to the host via ssh: 
[WARNING]: Unhandled error in Python interpreter discovery for host VM0100: unexpected output from Python
interpreter discovery
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/system/ping.py
Pipelining is enabled.
<10.250.0.2> ESTABLISH SSH CONNECTION FOR USER: admin
<10.250.0.2> SSH: EXEC sshpass -d10 ssh -o ControlMaster=auto -o ControlPersist=120s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o StrictHostKeyChecking=no -o 'User="admin"' -o ConnectTimeout=10 -o ControlPath=/home/caglab/.ansible/cp/020ba61a20 10.250.0.2 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<10.250.0.2> (1, "\n> /bin/sh -c '/usr/bin/python && sleep 0'\n% Invalid input at line 1\n", '')
<10.250.0.2> Failed to connect to the host via ssh: 
[WARNING]: Platform unknown on host VM0100 is using the discovered Python interpreter at /usr/bin/python, but
future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.
VM0100 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }, 
    "changed": false, 
    "module_stderr": "", 
    "module_stdout": "\n> /bin/sh -c '/usr/bin/python && sleep 0'\n% Invalid input at line 1\n", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}

**Describe the results you expected:**
I expected the ansible ping to pass.

**Additional information you deem important:**
I can SSH to the VM manually.
caglab@cag-rtp-ucs1-sonic:~/sonic-mgmt/ansible$ ssh admin@10.250.0.2
VM0100>exit

I think the problem is that in order for ansible ping to work, it needs to SSH into the VM and find the python interpreter.
But to find python on an Arista EOS, you have to log into the router as root.
But the ansible ping command is SSHing into the router as user = admin.

How do I get ansible ping to SSH using the user = root?
In what creds.yml file should this be set?

**Comment by wangxin** [comment]
Could you please try:
```
ansible -m ping -i veos.vtb server_1 -u root -k
```

Reference: https://github.com/Azure/sonic-mgmt/blob/master/ansible/doc/README.testbed.VsSetup.md

**Comment by richawil7** [comment]
caglab@cag-rtp-ucs1-sonic:~/sonic-mgmt/ansible$ ansible -m ping -i veos server_1 -u root -k

STR-ACS-SERV-01 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }, 
    "changed": false, 
    "ping": "pong"
}
[WARNING]: Platform unknown on host VM0102 is using the discovered Python interpreter at /usr/bin/python, but
future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.
VM0102 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }, 
    "changed": false, 
    "module_stderr": "", 
    "module_stdout": "\n> /bin/sh -c '/usr/bin/python && sleep 0'\n% Invalid input at line 1\n", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}

SSHing as user admin takes you to the Arista CLI.  Linux commands don't work here and /usr/bin/python is not found:
caglab@cag-rtp-ucs1-sonic:~/sonic-mgmt/ansible$ ssh admin@10.250.0.3
Password: 
Last login: Fri Aug  7 19:10:59 2020 from 10.250.0.245
ARISTA02T1>en
ARISTA02T1#ls /usr/bin/python
% Invalid input
ARISTA02T1#exit
Connection to 10.250.0.3 closed.

But if we SSH in as user root, we get the Arista EOS shell and python is found:
caglab@cag-rtp-ucs1-sonic:~/sonic-mgmt/ansible$ ssh root@10.250.0.3
Password: 
Arista Networks EOS shell
-bash-4.1# ls /usr/bin/python
/usr/bin/python

**Comment by stephengzh** [comment]
@richawil7 
I had this error before. 
However, I did:
Open veos file( Or you are using veos.vtb, whatever)

After each VM you are using, add:
ansible_ssh_user: root ansible_ssh_pass: 123456

Like:


vms_1:
  hosts:
    VM0100:
      ansible_host: 10.250.0.2
      ansible_ssh_user: root
      ansible_ssh_pass: 123456
    VM0101:
      ansible_host: 10.250.0.3
      ansible_ssh_user: root
      ansible_ssh_pass: 123456

The pass is according to your password.txt.
Try again.( Not need to restart VMs. Just run ansible ping. 
Anyway, this method works.
@wangxin

**Comment by stephengzh** [comment]
If you are using old veos:

do:

VM0100 ansible_host=10.250.0.3 ansible_ssh_user=root ansible_ssh_pass=123456
