### ISSUE TITLE
Ixia API server deployment instruction 

### ISSUE THREAD

**Issue by SubhajitPalKeysight** [Azure/sonic-mgmt#2083]
**Description**

**Steps to reproduce the issue:**
1.Currently Ixia API server docker depolyment instruction is on README.testbed.VsSetup.md. We need to move that to README.testbed.Overview.md 

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

**Comment by lguohan** [comment]
any update on this issue?

**Comment by SubhajitPalKeysight** [comment]
> 
> 
> any update on this issue?

This has been taken care of by PR  #2084

**Comment by SubhajitPalKeysight** [comment]
Taken care of in PR # 2084
