### ISSUE TITLE
Maybe a bug happened in adding topo to VMs based on the new veos file(the converted yml file) updated today.

### ISSUE THREAD

**Issue by stephengzh** [Azure/sonic-mgmt#2099]
Hey guys,
 
I was doing the add-topo step based on the new veos file updated today. And I found a bug.
I intended to add t0 topo into 4 VMs. What I am using are  VM0106, VM0107, VM0108 adn VM0109.

The vm_base in my testbed.csv file is VM0106, so, the topology should added from VM0106 to VM0109.
However, I obtained this result here:

PLAY RECAP ******************************************************************************************************************************************************************************************************************************
STR-ACS-SERV-01            : ok=103  changed=6    unreachable=0    failed=0    skipped=89   rescued=0    ignored=0   
VM0106                     : ok=20   changed=3    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0   
VM0107                     : ok=20   changed=3    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0   
VM0108                     : ok=4    changed=0    unreachable=0    failed=0    skipped=17   rescued=0    ignored=0   
VM0109                     : ok=0    changed=0    unreachable=0    failed=0    skipped=14   rescued=0    ignored=0   

As we can see, the VM0108 and VM0109 are skipped. I checked these four VMs. VM0106 and VM0107 are added topology successfully except VM0108 and VM0109.
Result:
VM0106->ARISTA01T1   
VM0107->ARISTA02T1   
VM0108->VM0108
VM0109->VM0109

After that, I did another try:
I changed vm_base in my testbed.csv file to VM0108.

I obtained this result:

PLAY RECAP ******************************************************************************************************************************************************************************************************************************
STR-ACS-SERV-01            : ok=103  changed=6    unreachable=0    failed=0    skipped=89   rescued=0    ignored=0   
VM0106                     : ok=20   changed=3    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0   
VM0107                     : ok=20   changed=3    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0   
VM0108                     : ok=21   changed=1    unreachable=0    failed=0    skipped=6    rescued=0    ignored=0   
VM0109                     : ok=17   changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0   

This time, four VMs are added t0 topology, however, the result has changed like this:

VM0106->ARISTA03T1   
VM0107->ARISTA04T1   
VM0108->ARISTA01T1
VM0109->ARISTA02T1

Can anyone fix this?

**Comment by stephengzh** [comment]
@jleveque Based on your commit.

**Comment by jleveque** [comment]
@stephengzh: I believe this issue was fixed by https://github.com/Azure/sonic-mgmt/pull/2095. Can you please confirm?

**Comment by stephengzh** [comment]
@jleveque Cheers bro, it works now.
