### ISSUE TITLE
ecmp test case fail with error "Please set vm_hosts variable with a list of VMs"

### ISSUE THREAD

**Issue by rajneeshaec** [Azure/sonic-mgmt#2107]
**Description**
ecmp test case fail with error "Please set vm_hosts variable with a list of VMs"

TASK [test : fail] ************************************************************************************************************************************************
task path: /var/johnar/new_jun_commit/sonic-mgmt/ansible/roles/test/tasks/ecmp.yml:7
Friday 14 August 2020  11:00:44 +0000 (0:00:00.591)       0:00:32.761 *********
fatal: [str-marvell-acs-1]: FAILED! => {
    "changed": false,
    "msg": "Please set vm_hosts variable with a list of VMs"
}

**Steps to reproduce the issue:**
1. Deploy t1 topology
2. Run ecmp test case

**Describe the results you received:**
TASK [test : fail] ************************************************************************************************************************************************
task path: /var/johnar/new_jun_commit/sonic-mgmt/ansible/roles/test/tasks/ecmp.yml:7
Friday 14 August 2020  11:00:44 +0000 (0:00:00.591)       0:00:32.761 *********
fatal: [str-marvell-acs-1]: FAILED! => {
    "changed": false,
    "msg": "Please set vm_hosts variable with a list of VMs"
}

* What is the correct way to pass the vm_hosts parameter?

**Comment by alanC-Cameo** [comment]
It would be something like below:
alan_chen@3c76e330b7bd:~/sonic-mgmt/ansible$ ansible-playbook -i veos -l lab-esc601-32-MAX test_sonic.yml -e testbed_name=vms-601-t1 -e testbed_file=testbed.csv -e testbed_type=t1 -e ptf_host=ptf_vms6-1 -vvvv -e sonicadmin_user=admin -e sonicadmin_password=password -e testcase_name=ecmp -e vm_hosts=192.168.3.20 -e vm_source=192.168.3.19

192.168.3.19 is the ptf
192.168.3.20 is the vEOS VM

**Comment by rajneeshaec** [comment]
Thanks @alanC-Cameo 
   I am able to run the ecmp test case
