### ISSUE TITLE
Missing vxlan_decap.json.j2 in test case "wr_arp" (master on Jul/14/2020 commit)

### ISSUE THREAD

**Issue by alanC-Cameo** [Azure/sonic-mgmt#2150]
**Description**
Missing vxlan_decap.json.j2 when runing test case "wr_arp" in t0 topology; master on Jul/14/2020 commit.

**Steps to reproduce the issue:**
1. alan_chen@3c76e330b7bd:~/sonic-mgmt/ansible$ ansible-playbook -i veos -l lab-esc601-32-MAX test_sonic.yml -e testbed_name=vms-601-t0 -e testbed_file=testbed.csv -e testbed_type=t0 -e ptf_host=ptf_vms6-1 -vvvv -e sonicadmin_user=admin -e sonicadmin_password=password -e testcase_name=wr_arp
2.
3.

**Describe the results you received:**
TASK [test : Render DUT parameters to json file for the test] ***************************************************************
task path: /var/alan_chen/sonic-mgmt/ansible/roles/test/tasks/wr_arp.yml:98
Thursday 27 August 2020  09:41:20 +0000 (0:00:00.795)       0:05:32.660 *******
<192.168.3.19> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.3.19> SSH: EXEC sshpass -d10 ssh -vvv -o ControlMaster=auto -o ControlPersist=120s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o StrictHostKeyChecking=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/var/alan_chen/.ansible/cp/b311b5f99c 192.168.3.19 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp `"&& mkdir $HOME/.ansible/tmp/ansible-tmp-1598521281.02-57324-102122124294527 && echo ansible-tmp-1598521281.02-57324-102122124294527="` echo $HOME/.ansible/tmp/ansible-tmp-1598521281.02-57324-102122124294527 `" ) && sleep 0'"'"''
...
...
...
fatal: [lab-esc601-32-MAX -> 192.168.3.19]: FAILED! => {
    "changed": false,
    **"msg": "Could not find or access 'vxlan_decap.json.j2'**\nSearched in:\n\t/var/alan_chen/sonic-mgmt/ansible/roles/test/templates/vxlan_decap.json.j2\n\t/var/alan_chen/sonic-mgmt/ansible/roles/test/vxlan_decap.json.j2\n\t/var/alan_chen/sonic-mgmt/ansible/roles/test/tasks/templates/vxlan_decap.json.j2\n\t/var/alan_chen/sonic-mgmt/ansible/roles/test/tasks/vxlan_decap.json.j2\n\t/var/alan_chen/sonic-mgmt/ansible/templates/vxlan_decap.json.j2\n\t/var/alan_chen/sonic-mgmt/ansible/vxlan_decap.json.j2 on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"
}

**Comment by wangxin** [comment]
The wr_arp test has been converted to pytest (PR #1572 ). Could you try the pytest version `sonic-mgmt/tests/arp/test_wr_arp.py`?
The wr_arp.yml playbook should have been updated to call the pytest version.

**Comment by alanC-Cameo** [comment]
tks wangxin for quick response.

test run success via **"alan_chen@3c76e330b7bd:~/sonic-mgmt/tests$ ./run_tests.sh -f testbed.csv -i veos -n vms-601-t0 -d lab-esc601-32-MAX -t t0,any -u -o -c arp/test_wr_arp.py"** now, yet the result is still NG due to swss, syncd, ... docker crash of a 201911 sonic image during the test.

**Comment by alanC-Cameo** [comment]
ansible "wr_arp" test case passed by copying missing vxlan_decap.json.j2 from 201811 version, and removing EVERFLOW{} and EVERFLOWV6{} in ACL_TABLE{} in config_db.json for swss, snmp, ... docker crash issue.
