### ISSUE TITLE
"TypeError: string indices ..." & "iptables: Bad rule ..." in test case "qos_sai" (master on Jul/14/2020 commit)

### ISSUE THREAD

**Issue by alanC-Cameo** [Azure/sonic-mgmt#2151]
**Description**
"TypeError: string indices must be integers, not str" & "iptables: Bad rule (does a matching rule exist in that chain?)." errors received when running test case "qos_sai"; master on Jul/14/2020 commit

**Steps to reproduce the issue:**
1. alan_chen@3c76e330b7bd:~/sonic-mgmt/ansible$ ansible-playbook -i veos -l lab-esc601-32-MAX test_sonic.yml -e testbed_name=vms-601-t0 -e testbed_file=testbed.csv -e testbed_type=t0 -e ptf_host=ptf_vms6-1 -vvvv -e sonicadmin_user=admin -e sonicadmin_password=password -e testcase_name=qos_sai -e ptf_portmap=roles/test/files/cameo/default_interface_to_front_map.ini 
2.
3.

**Describe the results you received:**
TASK [test : Get IPs for non-vlan testing ports] ********************************************************
task path: /var/alan_chen/sonic-mgmt/ansible/roles/test/tasks/qos_get_ports.yml:77
Friday 28 August 2020  00:50:22 +0000 (0:00:00.173)       0:00:32.189 *********
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: alan_chen
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp `"&& mkdir $HOME/.ansible/tmp/ansible-tmp-1598575823.01-58032-60432964879546 && echo ansible-tmp-1598575823.01-58032-60432964879546="` echo $HOME/.ansible/tmp/ansible-tmp-1598575823.01-58032-60432964879546 `" ) && sleep 0'
Using module file /var/alan_chen/sonic-mgmt/ansible/library/testing_port_ip_facts.py
<localhost> PUT /var/alan_chen/.ansible/tmp/ansible-local-574380nbZmW/tmpf7zq9S TO /var/alan_chen/.ansible/tmp/ansible-tmp-1598575823.01-58032-60432964879546/AnsiballZ_testing_port_ip_facts.py
<localhost> EXEC /bin/sh -c 'chmod u+x /var/alan_chen/.ansible/tmp/ansible-tmp-1598575823.01-58032-60432964879546/ /var/alan_chen/.ansible/tmp/ansible-tmp-1598575823.01-58032-60432964879546/AnsiballZ_testing_port_ip_facts.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /var/alan_chen/.ansible/tmp/ansible-tmp-1598575823.01-58032-60432964879546/AnsiballZ_testing_port_ip_facts.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /var/alan_chen/.ansible/tmp/ansible-tmp-1598575823.01-58032-60432964879546/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/var/alan_chen/.ansible/tmp/ansible-tmp-1598575823.01-58032-60432964879546/AnsiballZ_testing_port_ip_facts.py", line 114, in <module>
    _ansiballz_main()
  File "/var/alan_chen/.ansible/tmp/ansible-tmp-1598575823.01-58032-60432964879546/AnsiballZ_testing_port_ip_facts.py", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/var/alan_chen/.ansible/tmp/ansible-tmp-1598575823.01-58032-60432964879546/AnsiballZ_testing_port_ip_facts.py", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_testing_port_ip_facts_payload_vnKTyJ/__main__.py", line 69, in <module>
  File "/tmp/ansible_testing_port_ip_facts_payload_vnKTyJ/__main__.py", line 61, in main
**TypeError: string indices must be integers, not str**

fatal: [lab-esc601-32-MAX -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/alan_chen/.ansible/tmp/ansible-tmp-1598575823.01-58032-60432964879546/AnsiballZ_testing_port_ip_facts.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/var/alan_chen/.ansible/tmp/ansible-tmp-1598575823.01-58032-60432964879546/AnsiballZ_testing_port_ip_facts.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/alan_chen/.ansible/tmp/ansible-tmp-1598575823.01-58032-60432964879546/AnsiballZ_testing_port_ip_facts.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_testing_port_ip_facts_payload_vnKTyJ/__main__.py\", line 69, in <module>\n  File \"/tmp/ansible_testing_port_ip_facts_payload_vnKTyJ/__main__.py\", line 61, in main\nTypeError: string indices must be integers, not str\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
...
...
...
TASK [test : Remove iptables rule to drop BGP SYN Packet from Peer] ***************************************************
task path: /var/alan_chen/sonic-mgmt/ansible/roles/test/tasks/qos_sai.yml:513
Friday 28 August 2020  00:50:32 +0000 (0:00:09.322)       0:00:42.115 *********
<192.168.3.13> ESTABLISH SSH CONNECTION FOR USER: admin
<192.168.3.13> SSH: EXEC sshpass -d10 ssh -vvv -o ControlMaster=auto -o ControlPersist=120s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o StrictHostKeyChecking=no -o 'User="admin"' -o ConnectTimeout=10 -o ControlPath=/var/alan_chen/.ansible/cp/c2130bf51b 192.168.3.13 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp `"&& mkdir $HOME/.ansible/tmp/ansible-tmp-1598575832.93-58307-171084618204310 && echo ansible-tmp-1598575832.93-58307-171084618204310="` echo $HOME/.ansible/tmp/ansible-tmp-1598575832.93-58307-171084618204310 `" ) && sleep 0'"'"''
...
fatal: [lab-esc601-32-MAX]: FAILED! => {
    "changed": true,
    **"cmd": "iptables -D INPUT -j DROP -p tcp --destination-port bgp",**
    "delta": "0:00:00.005643",
    "end": "2020-08-28 00:50:33.203209",
    "invocation": {
        "module_args": {
            "_raw_params": "iptables -D INPUT -j DROP -p tcp --destination-port bgp",
            "_uses_shell": true,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2020-08-28 00:50:33.197566",
    **"stderr": "iptables: Bad rule (does a matching rule exist in that chain?).",**
    "stderr_lines": [
        "iptables: Bad rule (does a matching rule exist in that chain?)."
    ],
    "stdout": "",
    "stdout_lines": []
}

**Comment by wangxin** [comment]
The qos_sai test has been converted to pytest (PR #1713). Could you try the pytest version?

**Comment by alanC-Cameo** [comment]
> The qos_sai test has been converted to pytest (PR #1713). Could you try the pytest version?

Tks xin for your reply.

Does it has any difference in function verification between ansible "qos_sai" & pytest "test_qos_sai.py" test case? Or "test_qos_sai.py" is just 100% converted from "qos_sai" and verifies the same things?

Our product uses different chips from brcm & mlnx; could you hint what should I modify to couple with our products?

thank in advance.

**Comment by neethajohn** [comment]
The functionality is the same for the pytest version. for the test to run successfully, you need to ensure that you have the parameters defined in tests/qos/files/qos.yml for the asic type you are qualifying. Also you need to pass in the 'ptf_portmap' arg which matches your device

for eg, 
Mellanox-SN2700, ptf_portmap should be the file ansible/roles/test/files/mlnx/default_interface_to_front_map.ini
Arista-7260CX3-Q64, ptf_portmap should be the file  ansible/roles/test/files/brcm/66_interface_to_front_map.ini

**Comment by alanC-Cameo** [comment]
@neethajohn tks for reply and tests/qos/files/qos.yml may be the root cause for my running fail pytest "test_qos_sai.py". guess I need to inquiry my vendor to provide the correct parameters of its asic.

**Comment by alanC-Cameo** [comment]
issue fixed by vendor patch to "qos_get_ports.yml" for testing_ports_id[], "library/testing_port_ip_facts.py" for testing_ports_ip[], and missing WRED{}, QUEUE{}, and SCHEDULER{} in config_db.json
