### ISSUE TITLE
KeyError: 'device_conn' in test case "pfc_asym" (master on Jul/14/2020 commit)

### ISSUE THREAD

**Issue by alanC-Cameo** [Azure/sonic-mgmt#2154]
**Description**
KeyError: 'device_conn' of common/fixtures/conn_graph_facts.py:14 in test case "pfc_asym"; master on Jul/14/2020 commit. This error occurs on both ansible and pytest.

**Steps to reproduce the issue:**
1. "alan_chen@3c76e330b7bd:~/sonic-mgmt/ansible$ ansible-playbook -i veos -l lab-esc601-32-MAX test_sonic.yml -e testbed_name=vms-601-t0 -e testbed_file=testbed.csv -e testbed_type=t0 -e ptf_host=ptf_vms6-1 -vvvv -e sonicadmin_user=admin -e sonicadmin_password=password -e testcase_name=pfc_asym"
or 
"alan_chen@3c76e330b7bd:~/sonic-mgmt/tests$ ./run_tests.sh -f testbed.csv -i veos -n vms-601-t0 -d lab-esc601-32-MAX -t t0,any -u -o -c pfc_asym/test_pfc_asym.py"
2.
3.

**Describe the results you received:**
TASK [test : debug] ************************************************************************************************************
task path: /var/alan_chen/sonic-mgmt/ansible/roles/test/tasks/pytest_runner.yml:68
Friday 28 August 2020  07:58:09 +0000 (0:00:27.094)       0:00:47.525 *********
ok: [lab-esc601-32-MAX] => {
    "msg": [
        "============================= test session starts ==============================",
        "platform linux2 -- Python 2.7.12, pytest-4.6.5, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python",
        "cachedir: .pytest_cache",
        "metadata: {'Python': '2.7.12', 'Platform': 'Linux-4.15.0-112-generic-x86_64-with-Ubuntu-16.04-xenial', 'Packages': {'py': '1.9.0', 'pytest': '4.6.5', 'pluggy': '0.13.1'}, 'Plugins': {u'repeat': u'0.8.0', u'xdist': u'1.28.0', u'ansible': u'2.2.2', u'forked': u'1.2.0', u'html': u'1.22.1', u'metadata': u'1.10.0'}}",
        "ansible: 2.8.12",
        "rootdir: /var/alan_chen/sonic-mgmt/tests, inifile: pytest.ini",
        "plugins: ansible-2.2.2, metadata-1.10.0, html-1.22.1, forked-1.2.0, xdist-1.28.0, repeat-0.8.0",
        "collecting ... collected 4 items",
        "",
        "pfc_asym/test_pfc_asym.py::test_pfc_asym_off_tx_pfc ERROR                [ 25%]",
        "pfc_asym/test_pfc_asym.py::test_pfc_asym_off_rx_pause_frames ERROR       [ 50%]",
        "pfc_asym/test_pfc_asym.py::test_pfc_asym_on_tx_pfc ERROR                 [ 75%]",
        "pfc_asym/test_pfc_asym.py::test_pfc_asym_on_handle_pfc_all_prio ERROR    [100%]",
        "",
        "==================================== ERRORS ====================================",
        "__________________ ERROR at setup of test_pfc_asym_off_tx_pfc __________________",
        "",
        "localhost = <tests.common.devices.Localhost object at 0x7f779244b110>",
        "duthost = <tests.common.devices.SonicHost object at 0x7f7794534590>",
        "conn_graph_facts = {}",
        "",
        "    @pytest.fixture(scope=\"module\")",
        "    def fanout_graph_facts(localhost, duthost, conn_graph_facts):",
        "        facts = dict()",
        ">       for intf in conn_graph_facts[\"device_conn\"]:",
        **"E       KeyError: 'device_conn'",**
        "",
        **"common/fixtures/conn_graph_facts.py:14: KeyError",**

**Comment by wangxin** [comment]
Could you check content of file 'ansible/group_vars/all/inv_mapping.yml'. This file contains the mapping between inventory file to lab connection graph xml file. Please ensure that it has the correct mapping between your inventory file and lab connection graph file.

**Comment by alanC-Cameo** [comment]
@wangxin tks for the reply and I'll give it a try and report later.

**Comment by alanC-Cameo** [comment]
@wangxin 

I have made a workaround to directly load my conn_graph file and successfully bypass the **KeyError: 'device_conn"** issue and can continue the tests, yet it fails at some other point as below due to **"AttributeError: 'super' object has no attribute '\_\_getattr\_\_'"**. Have you met such error before?

        "_____________________ test_pfc_asym_on_handle_pfc_all_prio _____________________",
        "",
        "ptfhost = <tests.common.devices.PTFHost object at 0x7ffb2f0e9050>",
        "setup = {'fanout_inventory': 'lab', 'pfc_bitmask': {'pfc_mask': 24, 'pfc_rx_mask': 255, 'pfc_tx_mask': 24}, 'ptf_test_params':...0x1000000000128', u'oid:0x1000000000129', u'oid:0x1000000000126', u'oid:0x1000000000127', u'oid:0x1000000000124', ...]}",
        "enable_pfc_asym = None",
        "pfc_storm_runner = <tests.common.fixtures.pfc_asym.StormRunner object at 0x7ffb2c120b10>",
        "",
        "    def test_pfc_asym_on_handle_pfc_all_prio(ptfhost, setup, enable_pfc_asym, pfc_storm_runner):",
        "        \"\"\"",
        "        @summary: Asymmetric PFC is enabled. Verify that while receiving PFC frames DUT handle PFC frames on all",
        "                    priorities when asymetric mode is enabled",
        "        @param ptfhost: Fixture which can run ansible modules on the PTF host",
        "        @param setup: Fixture which performs setup/tardown steps needed for test case preparation",
        "        @param pfc_storm_runner: Fixture which start/stop PFC generator on Fanout switch",
        "        @param enable_pfc_asym: Fixture which enable/disable asymmetric PFC on all server interfaces",
        "        \"\"\"",
        "        pfc_storm_runner.server_ports = True",
        ">       pfc_storm_runner.run()",
        "",
        "pfc_asym/test_pfc_asym.py:74: ",
        "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ",
        "common/fixtures/pfc_asym.py:121: in run",
        "    **params)",
        "common/devices.py:949: in exec_template",
        "    return self.host.exec_template(ansible_root, ansible_playbook, inventory, **kwargs)",
        "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ",
        "",
        "self = <tests.common.devices.SonicHost object at 0x7ffb2cf62250>",
        "module_name = 'exec_template'",
        "",
        "    def __getattr__(self, module_name):",
        "        if self.host.has_module(module_name):",
        "            self.module_name = module_name",
        "            self.module = getattr(self.host, module_name)",
        "    ",
        "            return self._run",
        "    ",
        ">       return super(AnsibleHostBase, self).__getattr__(module_name)",
        "E       AttributeError: 'super' object has no attribute '__getattr__'",
        "",
        "common/devices.py:56: AttributeError",
        "=============================== warnings summary ===============================",
        "/usr/local/lib/python2.7/dist-packages/_pytest/cacheprovider.py:127",
        "  /usr/local/lib/python2.7/dist-packages/_pytest/cacheprovider.py:127: PytestCacheWarning: could not create cache path /var/alan_chen/sonic-mgmt/tests/.pytest_cache/v/cache/stepwise",
        "    self.warn(\"could not create cache path {path}\", path=path)",
        "",
        "/usr/local/lib/python2.7/dist-packages/_pytest/cacheprovider.py:127",
        "  /usr/local/lib/python2.7/dist-packages/_pytest/cacheprovider.py:127: PytestCacheWarning: could not create cache path /var/alan_chen/sonic-mgmt/tests/.pytest_cache/v/cache/nodeids",
        "    self.warn(\"could not create cache path {path}\", path=path)",
        "",
        "/usr/local/lib/python2.7/dist-packages/_pytest/cacheprovider.py:127",
        "  /usr/local/lib/python2.7/dist-packages/_pytest/cacheprovider.py:127: PytestCacheWarning: could not create cache path /var/alan_chen/sonic-mgmt/tests/.pytest_cache/v/cache/lastfailed",
        "    self.warn(\"could not create cache path {path}\", path=path)",
        "",
        "-- Docs: https://docs.pytest.org/en/latest/warnings.html",
        "=========================== short test summary info ============================",
        "ERROR pfc_asym/test_pfc_asym.py::test_pfc_asym_off_tx_pfc - AttributeError: '...",
        "ERROR pfc_asym/test_pfc_asym.py::test_pfc_asym_off_rx_pause_frames - Attribut...",
        "ERROR pfc_asym/test_pfc_asym.py::test_pfc_asym_on_tx_pfc - AttributeError: 's...",
        "ERROR pfc_asym/test_pfc_asym.py::test_pfc_asym_on_handle_pfc_all_prio - Attri...",
        "FAILED pfc_asym/test_pfc_asym.py::test_pfc_asym_off_tx_pfc - AttributeError: ...",
        "FAILED pfc_asym/test_pfc_asym.py::test_pfc_asym_off_rx_pause_frames - Attribu...",
        "FAILED pfc_asym/test_pfc_asym.py::test_pfc_asym_on_tx_pfc - AttributeError: '...",
        "FAILED pfc_asym/test_pfc_asym.py::test_pfc_asym_on_handle_pfc_all_prio - Attr...",
        "=============== 4 failed, 3 warnings, 4 error in 339.44 seconds ================"

**Comment by alanC-Cameo** [comment]
"AttributeError: 'super' object has no attribute '__getattr__'" is fixed by merging #2244
