### ISSUE TITLE
File "ptf_portmap" is missing when running ECMP script

### ISSUE THREAD

**Issue by okanchou9** [Azure/sonic-mgmt#232]
Hi,

I'm running the ECMP script to verify my DUT with the following CLI:

ansible-playbook -i inventory --limit switch1 test_sonic.yml -b --tags ecmp -e "ptf_host=172.18.0.2" -vvvvv

switch1 is the DUT
mgmt IP address of PTF is 172.18.0.2

According to the link(https://github.com/Azure/sonic-mgmt/blob/3db159c078a1afad9355fab0ed2a81519edf6b7e/ansible/roles/test/tasks/ecmp.yml) of ecmp.yml:

- name: copy portmap
      copy: src={{ ptf_portmap }} dest=/root
      delegate_to: "{{ ptf_host }}"

There is a step to copy the file of ptf_portmap to PTF but the file is undefined:

TASK [test : copy portmap] *****************************************************
task path: /home/tester/sonic_ansible/sonic-mgmt/ansible/roles/test/tasks/ecmp.yml:5
Monday 31 July 2017  11:39:43 +0800 (0:00:00.091)       0:00:09.714 *********** 
fatal: [switch1]: FAILED! => {"failed": true, "msg": "ERROR! 'ptf_portmap' is undefined"}

Please let me know how to get this file, thanks.

---
Regards,
Kenie Liu

**Comment by maggiemsft** [comment]
This PTF ECMP test is not actively maintained.
It might be deleted/deprecated soon.
All the current ECMP tests are covered under FIB

**Comment by lguohan** [comment]
@maggiemsft , can you remove ecmp test from the playbook?

**Comment by stcheng** [comment]
already addressed
