### ISSUE TITLE
[test_bgp_gr_helper.py] Failed: ipv4 or ipv6 default route not available

### ISSUE THREAD

**Issue by stephengzh** [Azure/sonic-mgmt#2350]
**Description**

Hi, when executing the test_bgp_gr_helper.py, failed in ipv4 or ipv6 default route not available

**Steps to reproduce the issue:**
1. Deploy t1 topo
2. Run test_announce_route.py
3. Run test_bgp_gr_helper.py

**Describe the results you received:**
_______________________________________________________________________________ ERROR at setup of test_bgp_gr_helper_routes_perserved _______________________________________________________________________________

duthost = <tests.common.devices.SonicHost object at 0x7f47bb25bed0>
nbrhosts = {'ARISTA01T0': {'conf': {'bgp': {'asn': 64001, 'peers': {65100: ['10.0.0.32', 'FC00::41']}}, 'bp_interface': {'ipv4': ...0::2/128'}}, 'properties': ['common', 'spine']}, 'host': <tests.common.devices.EosHost object at 0x7f47b8c81e90>}, ...}
    @pytest.fixture(scope='module')
    def setup_bgp_graceful_restart(duthost, nbrhosts):
    
        config_facts  = duthost.config_facts(host=duthost.hostname, source="running")['ansible_facts']
        bgp_neighbors = config_facts.get('BGP_NEIGHBOR', {})
    
        def configure_nbr_gr(node=None, results=None):
            """Target function will be used by multiprocessing for configuring VM hosts.
    
            Args:
                node (object, optional): A value item of the dict type fixture 'nbrhosts'. Defaults to None.
                results (Proxy to shared dict, optional): An instance of multiprocessing.Manager().dict(). Proxy to a dict
                    shared by all processes for returning execution results. Defaults to None.
            """
            if node is None or results is None:
                logger.error('Missing kwarg "node" or "results"')
                return
    
            node_results = []
            logger.info('enable graceful restart on neighbor host {}'.format(node['host'].hostname))
            logger.info('bgp asn {}'.format(node['conf']['bgp']['asn']))
            node_results.append(node['host'].eos_config(
                    lines=['graceful-restart restart-time 300'], \
                    parents=['router bgp {}'.format(node['conf']['bgp']['asn'])], \
                    module_ignore_errors=True)
                )
            node_results.append(node['host'].eos_config(
                    lines=['graceful-restart'], \
                    parents=['router bgp {}'.format(node['conf']['bgp']['asn']), 'address-family ipv4'], \
                    module_ignore_errors=True)
                )
            node_results.append(node['host'].eos_config(
                    lines=['graceful-restart'], \
                    parents=['router bgp {}'.format(node['conf']['bgp']['asn']), 'address-family ipv6'], \
                    module_ignore_errors=True)
                )
            results[node['host'].hostname] = node_results
    
        results = parallel_run(configure_nbr_gr, (), {}, nbrhosts.values(), timeout=120)
    
        check_results(results)
    
        logger.info("bgp neighbors: {}".format(bgp_neighbors.keys()))
        if not wait_until(300, 10, duthost.check_bgp_session_state, bgp_neighbors.keys()):
            pytest.fail("not all bgp sessions are up after enable graceful restart")
    
        if not wait_until(60, 5, duthost.check_default_route):
>           pytest.fail("ipv4 or ipv6 default route not available")
E           Failed: ipv4 or ipv6 default route not available

bgp_neighbors = {'10.0.0.1': {'admin_status': u'up', 'asn': u'65200', 'holdtime': u'10', 'keepalive': u'3', ...}, '10.0.0.11': {'admin...ve': u'3', ...}, '10.0.0.15': {'admin_status': u'up', 'asn': u'65200', 'holdtime': u'10', 'keepalive': u'3', ...}, ...}
config_facts = {'ACL_TABLE': {'DATAACL': {'policy_desc': u'DATAACL', 'ports': [u'Ethernet16', u'Ethernet0', u'Ethernet17', u'Ethernet...'bgp_asn': u'65100', 'cloudtype': u'None', 'default_bgp_status': u'up', 'default_pfcwd_status': u'disable', ...}}, ...}
configure_nbr_gr = <function configure_nbr_gr at 0x7f47b9df9c08>
duthost    = <tests.common.devices.SonicHost object at 0x7f47bb25bed0>
nbrhosts   = {'ARISTA01T0': {'conf': {'bgp': {'asn': 64001, 'peers': {65100: ['10.0.0.32', 'FC00::41']}}, 'bp_interface': {'ipv4': ...0::2/128'}}, 'properties': ['common', 'spine']}, 'host': <tests.common.devices.EosHost object at 0x7f47b8c81e90>}, ...}
results    = <DictProxy object, typeid 'dict' at 0x7f47b8827b10>

**Describe the results you expected:**
Pass

**Additional information you deem important:**

    **Output of `show version`:**
  ```
201911
  ```
    **Attach debug file `sudo generate_dump`:**

    ```
NA
    ```

**Comment by oxygen980** [comment]
Hey, 

I am having issue with running 'test_announce_route' on t1 topology, How did you make it work for t1?
initially I opened a bug https://github.com/Azure/sonic-mgmt/issues/2454 but closed my issue is similar to yours except I am not able to run 'test_announce_route' .

Any help is Appreciated!

**Comment by stephengzh** [comment]
@oxygen980 This issue has been fixed. Just repeat the steps: 1. deploy t1 topology, deploy minigraph, and run test_announce_route.py
