### ISSUE TITLE
Switch PortChannel interfaces go down during BGP storm

### ISSUE THREAD

**Issue by marian-pritsak** [Azure/sonic-mgmt#242]
Steps to reproduce:
1. Deploy t1-lag topology to testbed;
2. Deploy t1-lag minigraph to DUT;
3. Wait for PortChannel interfaces to come up;
4. Bug -> When DUT and VMs exchange routes, some PortChannel interfaces tend to go down.

Version: SONiC-OS-HEAD.344-1be1c46

@lguohan @pavel-shirshov Did you observe similar problems on t1-lag? I am wondering if it is due to perforamance of our server.

**Comment by stcheng** [comment]
what do you mean by saying 'port channel interfaces tend to go down'?
is it the port channel interface going down or the BGP session down?

**Comment by pavel-shirshov** [comment]
Hi Marian,

I didn't see such issue. What I saw that after reboot phy interfaces go up, then go down for a second, and then go up again.
PortChannel is usually up all the time.
