### ISSUE TITLE
test_cpu_memory_usage.py does not pass negative test

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-mgmt#2440]
**Description**

**Steps to reproduce the issue:**
1. start yes > /dev/null on the dut
2. yes process will occupy 100% cpu for one core
3. run test_cpu_memory_usage.py

**Describe the results you received:**
test pass

```
top - 07:13:25 up 2 days, 12:18,  2 users,  load average: 1.02, 0.79, 0.57
Tasks: 259 total,   2 running, 230 sleeping,   0 stopped,  27 zombie
%Cpu(s): 12.6 us, 13.1 sy,  0.0 ni, 74.0 id,  0.3 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   2866.4 total,    303.1 free,   1729.0 used,    834.3 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.    883.0 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                              
13051 admin     20   0    5876    752    688 R  99.3   0.0   3:28.49 yes   
```
**Describe the results you expected:**
test to fail

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
@yxieca  and @lolyu to check.

**Comment by lolyu** [comment]
I misunderstood the requirement for `cpu usage percent over a single core` so the cpu usage calculated now is divided by the cores count. Changing back to `irix` mode to solve this.
