### ISSUE TITLE
[sensors] Sensors test is failing as a result of bad PR merged

### ISSUE THREAD

**Issue by shlomibitton** [Azure/sonic-mgmt#2444]
**Description**

Sensors test is failing after merging a bad PR:
https://github.com/Azure/sonic-mgmt/pull/2255
The change causing the test to fail as a result of sysfs paths are "is not exist" even if they are.

**Steps to reproduce the issue:**
1. Run sensors test.
2. Observer "is not exist" failures.

**Describe the results you received:**

**For example 'PMB-1' values:**

E               "Path pmbus-i2c-5-41/PMB-1 0.9V VCORE Rail Curr (out)/curr2_crit_alarm is not exist", 
E               "Path pmbus-i2c-5-41/PMB-1 0.9V VCORE Rail Curr (out)/curr2_lcrit_alarm is not exist", 
E               "Path pmbus-i2c-5-41/PMB-1 0.9V VCORE Rail Curr (out)/curr2_max_alarm is not exist", 
E               "Path pmbus-i2c-5-41/PMB-1 PSU 12V Rail (in)/in1_crit_alarm is not exist", 
E               "Path pmbus-i2c-5-41/PMB-1 PSU 12V Rail (in)/in1_lcrit_alarm is not exist", 
E               "Path pmbus-i2c-5-41/PMB-1 PSU 12V Rail (in)/in1_max_alarm is not exist", 
E               "Path pmbus-i2c-5-41/PMB-1 PSU 12V Rail (in)/in1_min_alarm is not exist", 
E               "Path pmbus-i2c-5-41/PMB-1 0.9V VCORE Rail (out)/in2_crit_alarm is not exist", 
E               "Path pmbus-i2c-5-41/PMB-1 0.9V VCORE Rail (out)/in2_lcrit_alarm is not exist", 
E               "Path pmbus-i2c-5-41/PMB-1 0.9V VCORE Rail (out)/in2_max_alarm is not exist", 
E               "Path pmbus-i2c-5-41/PMB-1 0.9V VCORE Rail (out)/in2_min_alarm is not exist", 

**Describe the results you expected:**
Test should pass.

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by liat-grozovik** [comment]
@NazarTkachuk FYI

**Comment by NazarTkachuk** [comment]
I'll take a look on this issue. Looks like sensors test started failing with latest SONIC image

**Comment by NazarTkachuk** [comment]
@shlomibitton Could you please provide output for the command `sensors -A -u`?

**Comment by shlomibitton** [comment]
@NazarTkachuk [attached.[](url)](url)
[sensors_1025.txt](https://github.com/Azure/sonic-mgmt/files/5470899/sensors_1025.txt)

**Comment by NazarTkachuk** [comment]
The main failure reason was regular expression metacharacters in expected path. PR#2449 should fix this issue.
@shlomibitton Could you please try PR#2449?

**Comment by shlomibitton** [comment]
@NazarTkachuk I checked with the fix on https://github.com/Azure/sonic-mgmt/pull/2449 and it fixed the issue
thanks
