### ISSUE TITLE
Is any possibility to combine exabgpv4 and exabgpv6 to single service?

### ISSUE THREAD

**Issue by gord1306** [Azure/sonic-mgmt#2495]
**Description**
Is any possibility to combine exabgpv4 and exabgpv6 to single service? In current t1 topology, it may require much more nexthop groups than before (announce route in arista VM) during ECMP convergence. And some platform may not support some much nexthop groups

**Steps to reproduce the issue:**
Announce route in t1 or t1-lag topolgies

**Describe the results you received:**
Nexhop groups may not enough and cause SAI error

**Describe the results you expected:**
ECMP can be stable during testing

**Additional information you deem important:**

**Comment by lguohan** [comment]
this should be an image issue, combine to single service won't solve the image issue. please open issue on sonic-buildimage.

**Comment by gord1306** [comment]
> this should be an image issue, combine to single service won't solve the image issue. please open issue on sonic-buildimage.

Yes, I agreed with you, but I am thinking whether current t1 topology could be a general testing topology. Or users should customize the t1 topology for their own platforms.

**Comment by gord1306** [comment]
Confirm this is an image issue, the routeorch already do exhaust to avoid to many create event to asic db
