### ISSUE TITLE
ansible/library/show_interface.py cannot correctly parse output of "show interface status"

### ISSUE THREAD

**Issue by Junchao-Mellanox** [Azure/sonic-mgmt#2496]
**Description**

ansible/library/show_interface.py uses a regular expression to parse the output of "show platform interface".  Sometimes the output is like:

```
      Interface            Lanes    Speed    MTU    FEC    Alias             Vlan    Oper    Admin    Type    Asym PFC
---------------  ---------------  -------  -----  -----  -------  ---------------  ------  -------  ------  ----------
      Ethernet0          0,1,2,3      10G   9100   none     etp1           routed    down     down     N/A         off
      Ethernet4          4,5,6,7      10G   9100   none     etp2            trunk      up       up     N/A         off
      Ethernet8        8,9,10,11      10G   9100   none     etp3            trunk      up       up     N/A         off
     Ethernet12      12,13,14,15      10G   9100   none     etp4            trunk      up       up     N/A         off
     Ethernet16      16,17,18,19      10G   9100   none     etp5            trunk      up       up     N/A         off

```

After show_interface.py parsing the first line, I got a result like:
```
name: Ethernet0
speed: 10G
alias: none
vlan: etp1
oper_status: routed
admin_status: down
```

**Steps to reproduce the issue:**
1. on switch, run command "show interface status"
2. check it against the regular expression defined in show_interface.py

**Describe the results you received:**

```
name: Ethernet0
speed: 10G
alias: none
vlan: etp1
oper_status: routed
admin_status: down
```

**Describe the results you expected:**

```
name: Ethernet0
speed: 10G
alias: etp1
vlan: routed
oper_status: down
admin_status: down
```

**Comment by yxieca** [comment]
@Junchao-Mellanox can you specify your sonic-mgmt repo checkout branch and commit ID?

I tested latest github/master and I don't see such issue:

20:17:08 WARNING test_foo.py:test_interface_status:3: Interface status {u'Ethernet0': {u'alias': u'etp1', u'oper_state': u'up', u'name': u'Ethernet0', u'admin_state': u'up', u'vlan': u'PortChannel0002', u'speed': u'100G', u'fec': u'rs'}}

admin@str-dx010-acs-1:~$ show interfaces status
      Interface            Lanes    Speed    MTU    FEC    Alias             Vlan    Oper    Admin             Type    Asym PFC
---------------  ---------------  -------  -----  -----  -------  ---------------  ------  -------  ---------------  ----------
      Ethernet0      65,66,67,68     100G   9100     rs     etp1  PortChannel0002      up       up  QSFP28 or later         off
      Ethernet4      69,70,71,72     100G   9100     rs     etp2  PortChannel0002      up       up  QSFP28 or later         off
      Ethernet8      73,74,75,76     100G   9100     rs     etp3  PortChannel0005      up       up  QSFP28 or later         off

**Comment by Junchao-Mellanox** [comment]
Hi @yxieca, when I use the latest 201911, the result looks good. I will close this issue.

**Comment by Junchao-Mellanox** [comment]
Hi @yxieca , I reopened this issue. And I also created a PR to fix this. Please see https://github.com/Azure/sonic-mgmt/pull/2584.

**Comment by Junchao-Mellanox** [comment]
Fixed by https://github.com/Azure/sonic-mgmt/pull/2584
