### ISSUE TITLE
[test_lag_2] test_lag_2.py failed due to empty ptf_map

### ISSUE THREAD

**Issue by Junchao-Mellanox** [Azure/sonic-mgmt#2497]
**Description**

The error log is:
```
    def get_extended_minigraph_facts(self, tbinfo): 

        mg_facts = self.minigraph_facts(host = self.hostname)['ansible_facts'] 

        mg_facts['minigraph_ptf_indeces'] = mg_facts['minigraph_port_indices'].copy() 

 

        # Fix the ptf port index for multi-dut testbeds. These testbeds have 

        # multiple DUTs sharing a same PTF host. Therefore, the indeces from 

        # the minigraph facts are not always match up with PTF port indeces. 

        try: 

            dut_index = tbinfo['duts'].index(self.hostname) 

>           map = tbinfo['topo']['ptf_map'][dut_index] 

E           KeyError: 0 
```

After debugging it, I found that tbinfo['topo']['ptf_map'] is an empty dict here. And I found that tbinfo['topo']['ptf_map'] is populated by TestbedInfo.calculate_ptf_index_map, see https://github.com/Azure/sonic-mgmt/blob/master/tests/conftest.py#L118. https://github.com/Azure/sonic-mgmt/blob/f031f3272219fa0c6eddafc870fcde103f80cf81/tests/conftest.py#L151 requires the vlan format like "0.31@34", but in ansible/vars/topo_t1-lag.yml, the vlan format is still pure number. Not sure whether this is an issue. Please advice.

**Steps to reproduce the issue:**
1. Run test_lag_2.py

**Describe the results you received:**

E           KeyError: 0 

**Describe the results you expected:**

No error.

**Comment by lguohan** [comment]
fixed in #2483
