### ISSUE TITLE
unstable test_bgpmon

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-mgmt#2562]
**Description**

**Steps to reproduce the issue:**
check the log here.

https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image-pr/7269/testReport/junit/bgp/test_bgpmon/test_bgpmon_no_resolve_via_default/

**Describe the results you received:**

Error Message
Failed: Syn packets is captured when resolve-via-default is disabled
Stacktrace
duthost = <tests.common.devices.MultiAsicSonicHost object at 0x7f326d00af90>
common_setup_teardown = (u'10.1.0.32', '11.0.0.1', [28, 29, 30, 31])
ptfadapter = <tests.common.plugins.ptfadapter.ptfadapter.PtfTestAdapter testMethod=runTest>

    def test_bgpmon_no_resolve_via_default(duthost, common_setup_teardown, ptfadapter):
        """
        Verify no syn for BGP is sent when 'ip nht resolve-via-default' is disabled.
        """
        local_addr, peer_addr, peer_ports = common_setup_teardown
        exp_packet = build_syn_pkt(local_addr, peer_addr)
        # Load bgp monitor config
        logger.info("Configured bgpmon and verifying no packet on {} when resolve-via-default is disabled".format(peer_ports))
        try:
            # Disable resolve-via-default
            duthost.command("vtysh -c \"configure terminal\" \
                            -c \"no ip nht resolve-via-default\"")
            duthost.command("sonic-cfggen -j {} -w".format(BGPMON_CONFIG_FILE))
            # Verify no syn packet is received
            pytest_assert(0 == testutils.count_matched_packets_all_ports(test=ptfadapter, exp_packet=exp_packet, ports=peer_ports, timeout=BGP_CONNECT_TIMEOUT),
>                        "Syn packets is captured when resolve-via-default is disabled")
E                        Failed: Syn packets is captured when resolve-via-default is disabled

common_setup_teardown = (u'10.1.0.32', '11.0.0.1', [28, 29, 30, 31])
duthost    = <tests.common.devices.MultiAsicSonicHost object at 0x7f326d00af90>
exp_packet = <ptf.mask.Mask instance at 0x7f326c674370>
local_addr = u'10.1.0.32'
peer_addr  = '11.0.0.1'
peer_ports = [28, 29, 30, 31]
ptfadapter = <tests.common.plugins.ptfadapter.ptfadapter.PtfTestAdapter testMethod=runTest>

**Describe the results you expected:**

test pass

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
another test failure. 

https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image/561/testReport/junit/bgp/test_bgpmon/test_bgpmon_no_resolve_via_default/

**Comment by bingwang-ms** [comment]
Working on.
