### ISSUE TITLE
Question on bgp_gr_helper.py test

### ISSUE THREAD

**Issue by richawil** [Azure/sonic-mgmt#2620]
I have a question about the test in sonic-mgmt/tests/bgp/bgp_gr_helper.py.
At the top of the file, it indicates this test is applicable to the T1 topology:
pytestmark = [
    pytest.mark.topology('t1'),
    pytest.mark.device_type('vs')
]

Later in the file, it wants to get the neighbor device connected ports.
But it only cares about neighbors on ports which are PortChannels:
    # get neighbor device connected ports
    nbr_ports = []
    if ifname.startswith("PortChannel"):
        for member in po[ifname]['members']:
            nbr_ports.append(dev_nbr[member]['port'])
    else:
        pytest.skip("Do not support peer device not connected via port channel")

Correct me if I’m wrong, but in the T1 topology, there are no port channel interfaces configured.
So is it expected for this pytest to end as shown:

====================== 1 skipped in 1986.73 seconds =====================

And if so, does it really make sense to run this test case on the T1 topology?

SONiC Software Version: SONiC.cisco_201911.0-56e65ec6
Distribution: Debian 9.13
Kernel: 4.19.0-9-cisco-amd64
Build commit: 56e65ec6
Build date: Wed Nov 18 14:47:34 UTC 2020
Built by: mhatty@cag-rtp-bld-02.cisco.com

Platform: x86_64-8203_sys-r0
HwSKU: 32x100Gb
ASIC: cisco-8000
Serial Number: [unknown]
Uptime: 07:29:18 up  7:28,  1 user,  load average: 5.04, 4.42, 4.46

**Comment by gord1306** [comment]
#2448 has already removed this skip, could you try to patch it and verify?

**Comment by richawil** [comment]
Yes, that resolved the problem.
