### ISSUE TITLE
[interface_naming_mode] Config interface namingmode error when using "sudo" under the root user

### ISSUE THREAD

**Issue by stephengzh** [Azure/sonic-mgmt#2688]
**Description**

E                   "module_args": {
E                       "_raw_params": "sudo config interface_naming_mode default", 
E                       "_uses_shell": true, 
E                       "argv": null, 
E                       "chdir": null, 
E                       "creates": null, 
E                       "executable": null, 
E                       "removes": null, 
E                       "stdin": null, 
E                       "stdin_add_newline": true, 
E                       "strip_empty_ends": true, 
E                       "warn": true
E                   }
E               }, 
E               "msg": "non-zero return code", 
E               "rc": 2, 
E               "start": "2020-12-19 05:51:21.271826", 
E               "stderr": "Usage: config interface_naming_mode default [OPTIONS]\nTry \"config interface_naming_mode default -h\" for help.\n\nError: Cannot set interface naming mode for root user!", 
E               "stderr_lines": [
E                   "Usage: config interface_naming_mode default [OPTIONS]", 
E                   "Try \"config interface_naming_mode default -h\" for help.", 
E                   "", 
E                   "Error: Cannot set interface naming mode for root user!"
E               ], 

**Steps to reproduce the issue:**
1. Deploy t0 topo
2. Deploy minigraph
3. run test_iface_namingmode

**Describe the results you received:**
Error: Cannot set interface naming mode for root user!

**Describe the results you expected:**
Pass

**Additional information you deem important:**

I reproduce the cmd mannually in some circumstances:

1). When the DUT is under admin user, it returns a success:

admin@str-msn2700-01:~$ sudo config interface_naming_mode default
Please logout and log back in for changes take effect.

2). When the DUT is under root user, it returns the error:
root@str-msn2700-01:/home/admin# sudo config interface_naming_mode default
Usage: config interface_naming_mode default [OPTIONS]
Try "config interface_naming_mode default -h" for help.

Error: Cannot set interface naming mode for root user!

3). And without using sudo under root user, it returns the success:

root@str-msn2700-01:/home/admin# config interface_naming_mode default
Please logout and log back in for changes take effect.

    **Output of `show version`:**

root@str-msn2700-01:/home/admin# config interface_naming_mode default
Please logout and log back in for changes take effect.
root@str-msn2700-01:/home/admin# show ver

SONiC Software Version: SONiC.master.522-dirty-20201215.060116
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build commit: 4257c792
Build date: Tue Dec 15 06:08:23 UTC 2020
Built by: johnar@jenkins-worker-8

Platform: x86_64-ruijie_b6510-48vs8cq-r0
HwSKU: B6510-48VS8CQ
ASIC: broadcom
ASIC Count: 1
Serial Number: AAA1234567891
Uptime: 06:16:56 up 21:08,  1 user,  load average: 0.32, 0.73, 0.80

Docker images:
REPOSITORY                    TAG                                IMAGE ID            SIZE
docker-snmp                   latest                             b483850a99c9        485MB
docker-snmp                   master.522-dirty-20201215.060116   b483850a99c9        485MB
docker-teamd                  latest                             278ec7d8b43a        492MB
docker-teamd                  master.522-dirty-20201215.060116   278ec7d8b43a        492MB
docker-sonic-mgmt-framework   latest                             8a8002b5b7ed        609MB
docker-sonic-mgmt-framework   master.522-dirty-20201215.060116   8a8002b5b7ed        609MB
docker-router-advertiser      latest                             c386bafb71a1        448MB
docker-router-advertiser      master.522-dirty-20201215.060116   c386bafb71a1        448MB
docker-platform-monitor       latest                             2ddebb766809        573MB
docker-platform-monitor       master.522-dirty-20201215.060116   2ddebb766809        573MB
docker-lldp                   latest                             82862b16aea0        488MB
docker-lldp                   master.522-dirty-20201215.060116   82862b16aea0        488MB
docker-dhcp-relay             latest                             b457f75353f5        455MB
docker-dhcp-relay             master.522-dirty-20201215.060116   b457f75353f5        455MB
docker-database               latest                             d71f985a3277        448MB
docker-database               master.522-dirty-20201215.060116   d71f985a3277        448MB
docker-orchagent              latest                             901fedf415f3        506MB
docker-orchagent              master.522-dirty-20201215.060116   901fedf415f3        506MB
docker-nat                    latest                             bd470d765c1d        495MB
docker-nat                    master.522-dirty-20201215.060116   bd470d765c1d        495MB
docker-sonic-telemetry        latest                             2be7723ff3c6        523MB
docker-sonic-telemetry        master.522-dirty-20201215.060116   2be7723ff3c6        523MB
docker-fpm-frr                latest                             019f642edec4        508MB
docker-fpm-frr                master.522-dirty-20201215.060116   019f642edec4        508MB
docker-sflow                  latest                             075965ad793b        493MB
docker-sflow                  master.522-dirty-20201215.060116   075965ad793b        493MB
docker-syncd-brcm             latest                             d8c8182d9372        542MB
docker-syncd-brcm             master.522-dirty-20201215.060116   d8c8182d9372        542MB

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by stephengzh** [comment]
@wangxin Can you check this error? Especially the additional information I provided.

**Comment by monipko** [comment]
@stephengzh looks like you have to update sonic-mgmt docker image.
 You can find reference here: [Azure/sonic-buildimage/pull/4681](https://github.com/Azure/sonic-buildimage/pull/4681)

**Comment by stephengzh** [comment]
This issue is not seen.
