### ISSUE TITLE
[test_telemetry.py] test_sysuptime & test_osbuild_version should run only against master as this functionality is not implemented in 201911

### ISSUE THREAD

**Issue by stepanblyschak** [Azure/sonic-mgmt#2714]
**Description**

**Steps to reproduce the issue:**
1. Run telemetry/ tests
2.
3.

**Describe the results you received:**
telemetry/test_telemetry.py::test_sysuptime&telemetry/test_telemetry.py::test_osbuild_version are failing.

**Describe the results you expected:**
telemetry/test_telemetry.py::test_sysuptime&telemetry/test_telemetry.py::test_osbuild_version are skipped.

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
@macikgozwa

**Comment by lguohan** [comment]
fixed in https://github.com/Azure/sonic-mgmt/pull/2797
