### ISSUE TITLE
Data Plane Utilities

### ISSUE THREAD

**Issue by theasianpianist** [Azure/sonic-mgmt#2759]
Methods to send and verify data plane traffic:

1. Send traffic from the T1 to the server after performing some action. Verify: server received packet in time, did/did not receive IP-in-IP tunnel packet on T1
2. Send traffic from the server to the T1 after performing some action. Verify: T1 received packet in time

Depends on #2754, #2816

**Comment by vaibhavhd** [comment]
Not merging this PR yet as the verification is blocked, due to some issues in simulating switchover scenario and the lack of ICMP responder in PTF to relay link manager packets.
