### ISSUE TITLE
IP-in-IP Tunnel Test Cases

### ISSUE THREAD

**Issue by theasianpianist** [Azure/sonic-mgmt#2777]
Send encapsulated traffic from ToR A to B, and B to A. Verify that the tunnel packet has the correct parameters, and that each ToR can receive and decapsulate the packet from the other.

Depends on #2816

**Comment by lolyu** [comment]
Hi @theasianpianist, so for the testcase, what do you mean by `Send encapsulated traffic from ToR A to B, and B to A.`? Are those encapsulated traffic generated by the test? If so, is there a need to verify the tunnel traffic?

**Comment by theasianpianist** [comment]
@lolyu Yes, this should make use of the utils you wrote from #2816. This was previously mislabeled, it is an orchagent test case, see Section 4 here for details: https://github.com/Azure/sonic-mgmt/blob/e8def919d5a069cdeb77b34c676e9b58283d3c0f/docs/testplan/dual_tor/dual_tor_orch_test_plan.md
