### ISSUE TITLE
Add test case to check Max MTU

### ISSUE THREAD

**Issue by prsunny** [Azure/sonic-mgmt#279]
Create test case to check Max MTU (9100) for t1/t1-lag topologies.

1. Send Jumbo frame as Ping and expect response
2. Send Jumbo frame to an IP destination and expect routed packet.

**Comment by prsunny** [comment]
Pull-request raised.
https://github.com/Azure/sonic-mgmt/pull/280

**Comment by prsunny** [comment]
First phase changes merged. 
Pending: Address two review comments from Guohan

**Comment by daall** [comment]
Fixed by #280.
