### ISSUE TITLE
Failed to run Basic Router test

### ISSUE THREAD

**Issue by antonpatenko** [Azure/sonic-mgmt#28]
`The file_name 'roles/test/tasks/interface_up_down.yml' does not exist, or is not readable`
Task path: `roles/test/tasks/sonic.yml:71`

The command to run tests: 
`ansible-playbook -i inventory --limit <switch_name> test_sonic.yml -b --tags basic_router -vvvvv -e "ptf_host=<ptf_host_name>"`

**Comment by marian-pritsak** [comment]
Looks like we're missing minigraph_facts.py
