### ISSUE TITLE
Test Setup Fixtures

### ISSUE THREAD

**Issue by theasianpianist** [Azure/sonic-mgmt#2834]
Create fixtures for common setup/teardown actions including setting the upper ToR to active.

**Comment by bingwang-ms** [comment]
We have a fixture ```rand_one_dut_hostname``` already, which select a tor randomly. Do we need to set the selected tor as active?

**Comment by theasianpianist** [comment]
The tests are written with the assumption that the upper ToR always starts as the active ToR, so picking a ToR randomly may not work. My thought was simply to add a dual-tor specific conftest and add an auto-used fixture which calls `toggle_all_simulator_ports_to_tor_a`

**Comment by bingwang-ms** [comment]
I have a PR which pre selects a DUT (say upper TOR). If we need to set ToR_A as active, the PR will be a solution. But it's a huge change, which need a lot verification.

**Comment by bingwang-ms** [comment]
I created a PR #2850 to set the randomly selected ToR as active.
