### ISSUE TITLE
Issue about "vlan_intfs" generation for T0 topology

### ISSUE THREAD

**Issue by keboliu** [Azure/sonic-mgmt#2940]
**Description**
in file "ansible/config_sonic_basedon_testbed.yml" there is ansible script to generate a VLAN interface list for T0 topoloyg:
```
  - name: find all vlan interface names for T0 topology
    set_fact:
      vlan_intfs: "{{ vlan_intfs|default([])}} + ['{{ port_alias[item] }}' ]"
    with_items: "{{ host_if_indexes }}"
    when: "('host_interfaces_by_dut' in vm_topo_config) and ('tor' in vm_topo_config['dut_type'] | lower)"

```
https://github.com/Azure/sonic-mgmt/blob/d57abad93e159bf31151d01e6efef1a82ce7c591/ansible/config_sonic_basedon_testbed.yml#L83

for this line, I am very curious why need to combine a default list and port_alias[item] together to have a VLAN interface list? 
shouldn't **port_alias[item]** be enough?  and the default list will cause redundant interfaces to be added or even cause issues in some cases.
for example, the default list will be etp2 ~ etp25 and if we have lots of port split configured on the testbeds:

```
admin@sonic# show in st
      Interface            Lanes    Speed    MTU    FEC    Alias             Vlan    Oper    Admin             Type    Asym PFC
---------------  ---------------  -------  -----  -----  -------  ---------------  ------  -------  ---------------  ----------
      Ethernet0              0,1      50G   9100   none    etp1a           routed    down     down  QSFP28 or later         off
      Ethernet2              2,3      50G   9100   none    etp1b            trunk      up       up  QSFP28 or later         off
      Ethernet8              8,9      50G   9100   none    etp2a            trunk      up       up  QSFP28 or later         off
     Ethernet10            10,11      50G   9100   none    etp2b            trunk      up       up  QSFP28 or later         off
     Ethernet16            16,17      50G   9100   none    etp3a            trunk      up       up  QSFP28 or later         off
     Ethernet18            18,19      50G   9100   none    etp3b            trunk      up       up  QSFP28 or later         off
     Ethernet24      24,25,26,27     100G   9100     rs     etp4            trunk      up       up  QSFP28 or later         off
     Ethernet32            32,33      50G   9100   none    etp5a            trunk      up       up  QSFP28 or later         off
     Ethernet34            34,35      50G   9100   none    etp5b            trunk      up       up  QSFP28 or later         off
     Ethernet40            40,41      50G   9100   none    etp6a            trunk      up       up  QSFP28 or later         off
     Ethernet42            42,43      50G   9100   none    etp6b            trunk      up       up  QSFP28 or later         off
     Ethernet48            48,49      50G   9100   none    etp7a            trunk      up       up  QSFP28 or later         off
     Ethernet50            50,51      50G   9100   none    etp7b            trunk      up       up  QSFP28 or later         off
     Ethernet56      56,57,58,59     100G   9100     rs     etp8            trunk      up       up  QSFP28 or later         off
     Ethernet64            64,65      50G   9100   none    etp9a            trunk      up       up  QSFP28 or later         off
     Ethernet66            66,67      50G   9100   none    etp9b            trunk      up       up  QSFP28 or later         off
     Ethernet72            72,73      50G   9100   none   etp10a            trunk      up       up  QSFP28 or later         off
     Ethernet74            74,75      50G   9100   none   etp10b            trunk      up       up  QSFP28 or later         off
     Ethernet80            80,81      50G   9100   none   etp11a            trunk      up       up  QSFP28 or later         off
     Ethernet82            82,83      50G   9100   none   etp11b            trunk      up       up  QSFP28 or later         off
     Ethernet88      88,89,90,91     100G   9100     rs    etp12            trunk      up       up  QSFP28 or later         off
     Ethernet96            96,97      50G   9100   none   etp13a            trunk      up       up  QSFP28 or later         off
     Ethernet98            98,99      50G   9100   none   etp13b            trunk      up       up  QSFP28 or later         off
    Ethernet104          104,105      50G   9100   none   etp14a            trunk      up       up  QSFP28 or later         off
    Ethernet106          106,107      50G   9100   none   etp14b            trunk      up       up  QSFP28 or later         off
    Ethernet112          112,113      50G   9100   none   etp15a           routed    down     down  QSFP28 or later         off
    Ethernet114          114,115      50G   9100   none   etp15b           routed    down     down  QSFP28 or later         off
    Ethernet120  120,121,122,123     100G   9100     rs    etp16           routed      up       up  QSFP28 or later         off
    Ethernet128          128,129      50G   9100   none   etp17a  PortChannel0001      up       up  QSFP28 or later         off
    Ethernet130          130,131      50G   9100   none   etp17b  PortChannel0002      up       up  QSFP28 or later         off
    Ethernet136          136,137      50G   9100   none   etp18a  PortChannel0003      up       up  QSFP28 or later         off
    Ethernet138          138,139      50G   9100   none   etp18b  PortChannel0004      up       up  QSFP28 or later         off
```
in the above configuration, port etp16 is a routed port of T0 topo and expected to be admin shutdown, but since etp16 is in the default VLAN interface list and will be added to the "vlan_intfs" with other "real" vlan interface deduced from port_alias[item], then we will see that it will not be shut down as expected as in the above case and will cause test issue.

**Steps to reproduce the issue:**
1. Do port split as shows above 
2. generate a minigraph and apply it
3. will see etp16 not shutdown

**Describe the results you received:**

routed port in T0 topo is not shutdown

**Describe the results you expected:**

routed port in T0 topo should be shutdown

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**
    minigraph, config_db and port_config.ini was attached.

    ```
    (paste your output here)
    ```

[dump.zip](https://github.com/Azure/sonic-mgmt/files/5932296/dump.zip)

**Comment by liat-grozovik** [comment]
@yaxia can you please take a look?

**Comment by wangxin** [comment]
> for this line, I am very curious why need to combine a default list and port_alias[item] together to have a VLAN interface list?
shouldn't port_alias[item] be enough?

The default list is to initialize ansible variable `vlan_intfs` with an empty list. Then ansible loops through the enabled host interface list (got from previous step) to build a full list of `vlan_intfs`. In the minigraph.xml you attached, the list of vlan interfaces is correct. Interface `etp16` is not in it. I don't see issue with the logic here.
```
      <VlanInterfaces>
        <VlanInterface>
          <Name>Vlan1000</Name>
          <AttachTo>etp1b;etp2a;etp2b;etp3a;etp3b;etp4;etp5a;etp5b;etp6a;etp6b;etp7a;etp7b;etp8;etp9a;etp9b;etp10a;etp10b;etp11a;etp11b;etp12;etp13a;etp13b;etp14a;etp14b</AttachTo>
          <NoDhcpRelay>False</NoDhcpRelay>
          <StaticDHCPRelay>0.0.0.0/0</StaticDHCPRelay>
          <Type i:nil="true"/>
          <DhcpRelays>192.0.0.1;192.0.0.2;192.0.0.3;192.0.0.4</DhcpRelays>
          <VlanID>1000</VlanID>
          <Tag>1000</Tag>
          <Subnets>192.168.0.0/21</Subnets>
        </VlanInterface>
      </VlanInterfaces>
```
Actually interface `etp16` is configured as a `routed` interface, not a `trunk` interface. I am not sure why `etp16` has `"admin_status": "up"` in the config_db.json. Probably some tests accidentally set its admin status to up?

Can you:
* Re-run `testbed-cli.sh deploy-mg` with verbose option `-vvv` to see if the problem still persists.
* Attach the log of `testbed-cli.sh` if the issue can be reproduced.

**Comment by keboliu** [comment]
[log.zip](https://github.com/Azure/sonic-mgmt/files/6020480/log.zip)

@wangxin thanks for check this issue, I think this issue is not related to other tests cases.  I can see that after deploy this interface will be set to up before any test cases performed.  I use the following two commands to deploy this testbed:

```
./testbed-cli.sh gen-mg r-tigon-04-t0 lab vault -vvv
ansible-playbook -i inventory --limit r-tigon-04-t0 deploy_minigraph.yml -e dut_minigraph=r-tigon-04.t0.xml -b -vvv 

```

I attached the log for the above two commands in the zip file.

**Comment by wangxin** [comment]
Checked your log, used two steps to deploy minigraph:
* step 1 Generate minigraph
* step 2 Deploy minigraph using a customized playbook `deploy_minigraph.yml`. This playbook is not in public git repo.

The problem is that in step 1, the port_alias module is executed on localhost. In this case, platform KVM is assumed. Your customized port_config.ini is not used, log in `log_generate_minigraph.txt`, line 1160:
```
TASK [find interface name mapping and individual interface speed if defined with local data] ***************************************************************************************************
task path: /root/mars/workspace/sonic-mgmt/ansible/config_sonic_basedon_testbed.yml:79
Monday 22 February 2021  07:55:06 +0000 (0:00:00.062)       0:00:03.189 ******* 
Using module file /root/mars/workspace/sonic-mgmt/ansible/library/port_alias.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
ok: [r-tigon-04 -> localhost] => {
    "ansible_facts": {
        "port_alias": [
            "etp1", 
            "etp2", 
            "etp3", 
            "etp4", 
            "etp5", 
```

Then, based on this wrong port_alias, the vlan_intfs list is wrong.

Can you try to directly run `r-tigon-04-t0 lab vault -vvv` to see if the issuer persists?

**Comment by wangxin** [comment]
If you wish to use `gen-mg` firstly, please also put your customized `port_config.ini` to corresponding folder in the `sonic-mgmt` container.

**Comment by keboliu** [comment]
this issue was fixed after some local testbed configuration change, so I close this issue.
