### ISSUE TITLE
test_vlan.py failure

### ISSUE THREAD

**Issue by allas-nvidia** [Azure/sonic-mgmt#2987]
**Description**

**Steps to reproduce the issue:**
Run test itself.

**Describe the results you received:**
The failure will be during executing the function setup_vlan (before executing the tests)

**Describe the results you expected:**
Test should be PASSED

**Additional information you deem important:**
It seems that the test tries to assign more than one untagged VLAN to the interface.
It was allowed in the past, however next PR:
https://github.com/Azure/sonic-utilities/pull/1382
which was merged to MASTER changes this behaviour and now fails if user tries to add more then a single untagged VLAN to an interface
The test should be changed accordingly.

**Comment by SavchukRomanLv** [comment]
@allas-nvidia did this    [2973](https://github.com/Azure/sonic-mgmt/pull/2973)  fix the problem

**Comment by liat-grozovik** [comment]
the PR was verified and found to be working. Thanks.
