### ISSUE TITLE
function get_asic() returns wrong object

### ISSUE THREAD

**Issue by AntonHryshchuk** [Azure/sonic-mgmt#3103]
**Description**

In commit https://github.com/Azure/sonic-mgmt/commit/b38562a82ddf1222845c9795e73ac3c62aa9140f
Was changed returned object in function get_asic().
From SonicAsic, which contained method get_docker_cmd().
To SonicHost, which don't have method get_docker_cmd().

As a result, test test_xcvr_info_in_db.py failed with error message:

platform_tests/test_xcvr_info_in_db.py:36: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
common/platform/transceiver_utils.py:137: in check_transceiver_status
    check_transceiver_basic(dut, asic_index, interfaces, xcvr_skip_list)
common/platform/transceiver_utils.py:66: in check_transceiver_basic
    docker_cmd = asichost.get_docker_cmd(cmd, "database")
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tests.common.devices.SonicHost object at 0x7f8a23805550>, module_name = 'get_docker_cmd'

    def __getattr__(self, module_name):
        if self.host.has_module(module_name):
            self.module_name = module_name
            self.module = getattr(self.host, module_name)
    
            return self._run
        raise AttributeError(
>           "'%s' object has no attribute '%s'" % (self.__class__, module_name)
            )
E       AttributeError: '<class 'tests.common.devices.SonicHost'>' object has no attribute 'get_docker_cmd'

**Steps to reproduce the issue:**
1. run the platform_tests/test_xcvr_info_in_db.py

**Comment by liat-grozovik** [comment]
@abdosi and @yaxia please note recent degradation.
if the fix provided in commit is approved the tests which assumed to be working should be fixed as well.

**Comment by abdosi** [comment]
Let me check on this.

**Comment by vcheketx** [comment]
@abdosi This issue also occurs during platform_tests/test_sequential_restart.py::test_restart_swss:
`E       AttributeError: '<class 'tests.common.devices.SonicHost'>' object has no attribute 'get_service_name'`
Could you take a look at this and update your fix for 'get_service_name' also?
