### ISSUE TITLE
Lag_2 test in T1-Lag topo- Need Clarification

### ISSUE THREAD

**Issue by chitra-raghavan** [Azure/sonic-mgmt#313]
We see some failures while running lag_2 test in T1-Lag Topology

**T1-Lag topology:**
Lag-2:
The physical ports used on S6100 in our tetsbed are non-contiguous
The script for Lag_2 **_[single_lag_test.yml]_** takes the interface number from topo_t1-lag.yml vlan info.
The _topo_t1-lag.yml_ file has the vlan listed in contiguous order from 0 to31

_**Snip from single_lag_test.yml**_

- set_fact:
    **iface_behind_lag_member_0: "{{ topology['VMs'][peer_device]['vlans'][0] }}"**
 
- set_fact:
    **iface_behind_lag_member_1: "{{ topology['VMs'][peer_device]['vlans'][1] }}"** 

We modified topo_t1-lag.yml vlan number to match the physical interface numbering on sonic dut.
After modifying this we do not see the failure in lag2 tests.
Can you help out in making us understand the reason to take the port numbers from vlan info?

**Comment by maggiemsft** [comment]
fix merged
