### ISSUE TITLE
"check_all_psu_on" function didn't filling the parameter "psu_test_results" in else condition

### ISSUE THREAD

**Issue by AntonHryshchuk** [Azure/sonic-mgmt#3224]
**Description**
The function "check_all_psu_on" into the file test_platform_info.py doesn't filling in "else" condition the parameter "psu_test_results".

```
def check_all_psu_on(dut, **psu_test_results**):
    power_off_psu_list = []
    if "201811" in dut.os_version or "201911" in dut.os_version:
        cli_psu_status = dut.command(CMD_PLATFORM_PSUSTATUS)
        for line in cli_psu_status["stdout_lines"][2:]:
            fields = line.split()
            **psu_test_results**[fields[1]] = False
            if " ".join(fields[2:]) == "NOT OK":
                power_off_psu_list.append(fields[1])
    else:
        # Use JSON output
        cli_psu_status = dut.command(CMD_PLATFORM_PSUSTATUS_JSON)
        psu_info_list = json.loads(cli_psu_status["stdout"])
        for psu_info in psu_info_list:
            if psu_info["status"] == "NOT OK":
                power_off_psu_list.append(psu_info["index"])
    if power_off_psu_list:
        logging.warn('Powered off PSUs: {}'.format(power_off_psu_list))
    return len(power_off_psu_list) == 0
```
As you can see, the "else condition didn't have filling of parameter "psu_test_results". 
As an affect, the test case "test_turn_on_off_psu_and_check_psustatus" always failed.

**Steps to reproduce the issue:**
run test case "test_turn_on_off_psu_and_check_psustatus" from  test_platform_info.py

**Describe the results you received:**
psu_test_results = {} 
pytest_require(check_all_psu_on(duthost, psu_test_results), "Some PSU are still down, skip rest of the testing in this case") 
pytest_assert(len(psu_test_results.keys()) == psu_num, \ 
>    "In consistent PSU number output by '%s' and '%s'" % (CMD_PLATFORM_PSUSTATUS, "sudo psuutil numpsus")) 
E    Failed: In consistent PSU number output by 'show platform psustatus' and 'sudo psuutil numpsus' 

**Describe the results you expected:**
The test case is passed

**Additional information you deem important:**

  **Output of `show version`:**

    ```
    root@r-leopard-32:/home/admin# show version 
    SONiC Software Version: SONiC.SONIC.202012.53-aee4892c_Internal
    Distribution: Debian 10.8
    Kernel: 4.19.0-12-2-amd64
    Build commit: aee4892c
    Build date: Thu Mar 25 07:17:58 UTC 2021
    Built by: sw-r2d2-bot@r-build-sonic-ci03
    Platform: x86_64-mlnx_msn4700-r0
    HwSKU: ACS-MSN4700
    ASIC: mellanox
    ASIC Count: 1
    Serial Number: MT2022X08597
    Uptime: 09:29:45 up  1:02,  1 user,  load average: 0.19, 1.09, 1.27
    ```
[sonic_dump_r-leopard-32_20210329_093705.tar.gz](https://github.com/Azure/sonic-mgmt/files/6220759/sonic_dump_r-leopard-32_20210329_093705.tar.gz)

    **Attach debug file `sudo generate_dump`:**

    ```

**Comment by wangxin** [comment]
Thanks @AntonHryshchuk for reporting and fixing this!

**Comment by wangxin** [comment]
Issue fixed.
