### ISSUE TITLE
IPinIP test case support for Standalone TH2 (7260CX3) to modify config DB DEVICE_METADATA localhost subtype

### ISSUE THREAD

**Issue by gechiang** [Azure/sonic-mgmt#3256]
**Description**

Need testcase support for IPinIP testing on Standalone TH2 SKU (7260CX3). 
BRCM has implemented new IPinIP tunnel support that is needed for DualToR. The support requires new SOC properties enabled at boot time so that the new IPinIP implementation would be used.  Currently this SOC properties are only applied if the DUT is configured for DualToR in the config DB.  But if 7260CX3 is a standalone DUT, This configuration would never be set.
Since we like to be able to test the new IPinIP functionality with standalone 7260CX3 SKUs, it requires the testcase be changed to first modify the config DB of the standalone 7260CX3 to add "subtype": "DualToR" under the DEVICE_METADATA: "localhost" section:
```
DEVICE_METADATA": {
        "localhost": {
            "bgp_asn": "4200065100",
            "buffer_model": "traditional",
            "cloudtype": "None",
            "default_bgp_status": "up",
            "default_pfcwd_status": "enable",
            "deployment_id": "1",
            "docker_routing_config_mode": "separated",
            "hostname": "str-7260cx3-acs-2",
            "hwsku": "Arista-7260CX3-D108C8",
            "mac": "74:83:ef:09:33:1c",
            "platform": "x86_64-arista_7260cx3_64",
            "region": "None",
            "synchronous_mode": "enable",
            "subtype": "DualToR",
            "type": "ToRRouter”
        }
    },
```
Once this is added, reload the SWSS and SYNCD dockers so that the ASIC will be booted up with proper config.bcm properties.
Run the IPinIP tests
At the end o f the test case modify the config DB to remove the "DualToR" setting.

Please be sur if the "DualToR" setting was ever modified in configDB as part of the testcase, it must always remove it no matter what is the result of the testcase.

This testcase change is pending the following PR:
https://github.com/Azure/sonic-buildimage/pull/7168
Please make sure that the testcase change is only applicable for master image or 202012 based image (when the above PR is also part of 202012).

**Comment by bingwang-ms** [comment]
The feature is implemented in #3110 and verified on ```SONiC.HEAD.591-e6afc5ad```
https://github.com/Azure/sonic-mgmt/blob/0058c43a036569cb68edda652977e81eb0619397/tests/common/dualtor/dual_tor_mock.py#L250-L278
