### ISSUE TITLE
Need new test: RADV/IPv6 RA

### ISSUE THREAD

**Issue by yxieca** [Azure/sonic-mgmt#3294]
**Description**

This is a test gap:

We need a test to test RADV/IPv6 Router advertisements:
- Need to test that radvd configured and running for the appropriate roles
- Verify /etc/radvd.conf is generated properly for each applicable VLAN interface
- Ensure RA is advertised on LL address

**Comment by prsunny** [comment]
Just few notes:
1. RA to be advertised on LL address. 
2. Verify config /etc/radvd.conf for the configured Vlan.
