### ISSUE TITLE
[IPinIP decap] Test to verify DSCP pipe mode

### ISSUE THREAD

**Issue by prsunny** [Azure/sonic-mgmt#3355]
**Description**

Require test to verify DSCP pipe mode for Broadcom platforms (202012 version and above). With the [PR ](https://github.com/Azure/sonic-buildimage/pull/7234) to change dscp mode from pipe to uniform, need a test enhancement to cover pipe mode.

This enhancement can be done over the current [test_decap.py](https://github.com/Azure/sonic-mgmt/blob/master/tests/decap/test_decap.py#L109) script. However, this may require a removal of existing IP TUNNEL config and re-installation. Currently there is a limitation with Tunnel delete tracked as part of CSP CS00012182145

**Steps to reproduce the issue:**
1. Run test_decap test.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**
Test should cover both dscp uniform and pipe models. 

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by antonptashnik** [comment]
hi @prsunny . Taking this issue into account I understand that DSCP uniform mode is an additional mode appeared in SONiC 202012, so versions before 202012 support only DSCP pipe and later versions support both DSCP pipe and uniform. Correct ?

**Comment by prsunny** [comment]
> hi @prsunny . Taking this issue into account I understand that DSCP uniform mode is an additional mode appeared in SONiC 202012, so versions before 202012 support only DSCP pipe and later versions support both DSCP pipe and uniform. Correct ?

thats right
