### ISSUE TITLE
Need new test: System and Management - Netconf

### ISSUE THREAD

**Issue by kevinskwang** [Azure/sonic-mgmt#3588]
Scope: to be defined

**Comment by wangxin** [comment]
Azure currently uses Netconf to deploy configurations to specific platforms. This test case is aimed at verifying that devices can be configured through the use of this tool and that specific show commands can also be executed for the purposes of monitoring and collecting information. 

This verification does not require the DUT to be under any specific topology and it can be tested on a standalone device. 

netconf agent tty 
netconf-yang agent ssh
ssh server netconf vrf MANAGEMENT

**Comment by ZhaohuiS** [comment]
Confirm that SONiC doesn't support NetConf, close this test gap.
