### ISSUE TITLE
Need new test: DHCP Relay

### ISSUE THREAD

**Issue by kevinskwang** [Azure/sonic-mgmt#3599]
This is a test gap:

Need to test 4 vlans.

**Comment by ZhaohuiS** [comment]
[test_gap] Need 4 vlans for dhcp relay/dhcpv6 relay #4859 was merged. Close this issue.
Currently, PR pipeline only covers 2 vlans config, we plan to cover 4 vlans config in nightly running job.
So far the lab is down, when lab is coming back, will add this part into nightly run.
