### ISSUE TITLE
Need new test: Escape Character

### ISSUE THREAD

**Issue by kevinskwang** [Azure/sonic-mgmt#3620]
This is a test gap.

**Comment by yxieca** [comment]
Test step:
- on console session, Try to traceroute/ping to another IP and then press Cntrl-C to escape.
- make sure traceroute/ping can be escaped.

**Comment by Blueve** [comment]
What is the goal of this test? 

If the intension is to avoid conflict(with TS escape characters), then we need to know that different TS device might using different escape characters, it is hard to construct a test.

If the intension is only for testing escape traceroute/ping program, then we are no need to on a console session.

If the intension is for testing escape traceroute/ping from SONiC TS, then it would be more make sense.
