### ISSUE TITLE
Need new test: ACL with VLAN rule Tests

### ISSUE THREAD

**Issue by qiluo-msft** [Azure/sonic-mgmt#3623]
**Description**
- [ ] VLAN ID w/ Untagged VLAN
- [ ] VLAN ID w/ Tagged VLAN
- [ ] VLAN ID where an interface is a tagged and untagged VLAN member (make sure that if we have 1 rule for the tagged VLAN and 1 rule for the untagged VLAN that the proper rule gets hit)

Note on this: You need to have routable VLANs in order for the tests to work b/c they depend on checking if packets are forwarded/dropped as expected.

Also, clarification on the 3rd test case - the idea is to check that if a given port is a member of both a tagged VLAN and an untagged VLAN, then you can send packets to it from either VLAN and the matching behavior should work.

**Comment by bingwang-ms** [comment]
PR https://github.com/Azure/sonic-mgmt/pull/3716 covers part of the scenarios in this test gap. I'll try to reach out to the PR author and try to co-work with him/her
