### ISSUE TITLE
Dict object has no attribute 'mgmtip' and 'HwSku' in resume_fanout_ports.yml

### ISSUE THREAD

**Issue by JibinBao** [Azure/sonic-mgmt#3666]
**Description**
Definition of variable is not correct in resume_fanout_ports.yml
Original code:
  
  ```
 - set_fact:
        peer_host: "{{device_info['mgmtip']}}"
        peer_hwsku: "{{device_info['HwSku']}}"
```

When run resume_fanout_ports.yml, will raise error as follow:
"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'mgmtip'\n\nThe error appears to be in '/root/mars/workspace/sonic-mgmt/ansible/roles/test/tasks/resume_fanout_ports.yml': line 15, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - set_fact:\n      ^ here\n" 

Because data structure of device_info is as follows:
 ```
"device_info": { 

            "arc-switch1007": { 

                "HwSku": "MLNX-OS", 

                "ManagementGw": "10.210.25.1", 

                "ManagementIp": "10.210.25.42/24", 

                "Type": "FanoutLeaf", 

                "mgmtip": "10.210.25.42" 

            } 

        }, 
```
So it should be changed to 
```
- set_fact:
        peer_host: "{{device_info[peer_device]['mgmtip']}}"
        peer_hwsku: "{{device_info[peer_device]['HwSku']}}"
```

**Steps to reproduce the issue:**
1. Make some interface shoutdown
2. Run ansible test case: warm_reboot_multi_sad_inboot.yaml

**Describe the results you received:**
Raise exception follow:
"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'mgmtip'\n\nThe error appears to be in '/root/mars/workspace/sonic-mgmt/ansible/roles/test/tasks/resume_fanout_ports.yml': line 15, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - set_fact:\n      ^ here\n" 

**Describe the results you expected:**
No any exception is raised, and peer_host and  peer_hwsku are set successfully.

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by wangxin** [comment]
Fixed by https://github.com/Azure/sonic-mgmt/pull/3681
