### ISSUE TITLE
[Warmboot] Request test to verify port status after warmboot

### ISSUE THREAD

**Issue by prsunny** [Azure/sonic-mgmt#3683]
**Description**
Observed an issue during warmboot where we were unable to bring up the port, if the port was "admin" down originally and device goes for warmboot.  This is a test-gap. Need to enhance the warmboot test to include this scenario:

1. Admin down a port
2. Perform warmboot
3. Admin up the port
4. Verify port oper status (must be "up")

**Steps to reproduce the issue:**
1. Steps above

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by stepanblyschak** [comment]
We have warm_reboot_sad path test cases which do LAG member shutdown, VLAN member shutdown before warm-reboot.
It works like this:
1. Shutdown port
2. Warm-reboot test
3. Verify port is still down after warm-reboot (and if this is a LAG member then LAG is down and LAG is down on the peer)
4. Startup port
After that as part of sanity check ports is verified to be up.
(There are also multi_sad cases where several ports are shutdown)

@prsunny Do you think it is enough to cover your scenario? Do we need to put explicit check in the test and not rely on sanity (it could be that user disabled sanity in commmand line)?

**Comment by prsunny** [comment]
1. Suggest to cover oper-down before warmboot and enable port from peer-side after warmboot.
