### ISSUE TITLE
[sonic-installer] Request for a  test to do cover sonic_installer install master --> master image.

### ISSUE THREAD

**Issue by judyjoseph** [Azure/sonic-mgmt#3724]
**Description**
There was a sonic-buildimage issue reported (https://github.com/Azure/sonic-buildimage/issues/8032) which is about a failure when we install a new version of master image - with the DUT already running master. sonic_installer install command works fine when upgrading from older version like 201811/201911 --> a master image

So it is good to add a test to cover this scenario of sonic_install between same version, like master --> master.

**Steps to reproduce the issue:**
1. Install a sonic-buildimage public/master based image on a DUT
2. reboot the DUT and make sure it is running with that master image
3. Do another sonic_installer install to upgrade to a newer version of master image itself, there is failure seen as mentioned in https://github.com/Azure/sonic-buildimage/issues/8032

**Describe the results you received:**
Errors as reported in https://github.com/Azure/sonic-buildimage/issues/8032

**Describe the results you expected:**
Should install the new version master image with the sonic_installer command.

**Comment by yxieca** [comment]
Testbed dedicated to test master images will go through upgrade every nighty.
