### ISSUE TITLE
Fast-reboot.py tests , doesnt handle the  mapping of  non-contiguous 32 ports in 64 port devices. 

### ISSUE THREAD

**Issue by chitra-raghavan** [Azure/sonic-mgmt#374]
### **Issue** 

Fast-reboot.py tests , doesnt handle the  mapping of  non-contiguous 32 ports in 64 port devices. 

In the arp responder file ,  mapping of  ip and mac are done with the ports generated by from_t1.json file.

The list of ports are taken from /tmp/from_t1.json file.
https://github.com/Azure/sonic-mgmt/blob/master/ansible/roles/test/files/helpers/arp_responder.py

This file from_t1.json  is generated inside the Fast-Reboot test , which takes input from the vlan ports of the device.
https://github.com/Azure/sonic-mgmt/blob/master/ansible/roles/test/files/ptftests/fast-reboot.py.

In fast-boot.py it is assumed that the device number can be mapped to  the file  from_t1.json , which is used by arp_responder. 
Since ptf is having only 32 ports, exact mapping of ports cannot be done using device interface if the  used ports is not in range of 1 to 32. .

**Comment by pavel-shirshov** [comment]
Hi Chitra,

Can you please explain what do you mean by "doesnt handle the mapping of non-contiguous 32 ports in 64 port devices"?

Other comments:

> Since ptf is having only 32 ports, exact mapping of ports cannot be done using device interface if the 
used ports is not in range of 1 to 32.

ptf supports as many ports as you want it to.
The number of supported ports are defined by "platform". You can use custom platform by putting a custom platform file into your own "platform-dir". You can use ptf option "--platform-dir" for this.  https://github.com/p4lang/ptf/blob/master/ptf#L237

The fast-reboot test using a custom "remote" platform. You can find the source file of the platform here:
https://github.com/Azure/sonic-mgmt/blob/master/ansible/roles/test/files/ptftests/remote.py

It's copied into the ptf container by this line:
https://github.com/Azure/sonic-mgmt/blob/master/ansible/roles/test/tasks/fast-reboot.yml#L20

And it is used by fast-reboot test here: https://github.com/Azure/sonic-mgmt/blob/master/ansible/roles/test/tasks/fast-reboot.yml#L103

I run the test on 64 port device. I use only 36 vlan member ports of the device. The port range of the vlan ports are not contiguous.

Please let me know if you have other questions

**Comment by chitra-raghavan** [comment]
Thanks Pavel, we will check this and get back.

**Comment by pavel-shirshov** [comment]
closing as outdated
