### ISSUE TITLE
IP and UDP header length needs to be changed for "tests/dhcp_relay/test_dhcp_pkt_fwd.py::TestDhcpPktFwd::testDhcpPacketForwarding[pktInfo2]" script

### ISSUE THREAD

**Issue by jsanghra** [Azure/sonic-mgmt#3815]
**Description**

Seeing Issue with "dhcp_relay/test_dhcp_pkt_fwd.py " script with "request" packet .

The DHCP request packets are not even making it to the router.
And it happens only with DHCP request packets and not the others.
After taking a closer look at the DHCP request packet that is generated by the PTF, it turned out that IPv4 and UDP length fields are incorrect and it seems a malformed packet.

After fixing the test script locally to have the right values in the IP and UDP header fields, the test case passes.

--- dhcp_relay/test_dhcp_pkt_fwd.py.orig	2021-07-15 16:13:08.934490769 +0000
+++ dhcp_relay/test_dhcp_pkt_fwd.py	2021-07-15 19:41:51.353441563 +0000
@@ -231,8 +231,10 @@
             packet: DHCP Request packet
         """
         ether = scapy.Ether(dst=dutMac, src=self.DHCP_RELAY["mac"], type=0x0800)
-        ip = scapy.IP(src=self.DHCP_RELAY["loopback"], dst=self.DHCP_SERVER["ip"], len=336, ttl=64)
-        udp = scapy.UDP(sport=self.DHCP_SERVER["port"], dport=self.DHCP_SERVER["port"], len=316)
+        #ip = scapy.IP(src=self.DHCP_RELAY["loopback"], dst=self.DHCP_SERVER["ip"], len=336, ttl=64)
+        ip = scapy.IP(src=self.DHCP_RELAY["loopback"], dst=self.DHCP_SERVER["ip"], len=328, ttl=64)
+        #udp = scapy.UDP(sport=self.DHCP_SERVER["port"], dport=self.DHCP_SERVER["port"], len=316)
+        udp = scapy.UDP(sport=self.DHCP_SERVER["port"], dport=self.DHCP_SERVER["port"], len=308)

This issue happens with below request[pktinfo2] packet type :
dhcp_relay/test_dhcp_pkt_fwd.py::TestDhcpPktFwd::testDhcpPacketForwarding[pktInfo2]

After making the above IP and UDP header length change - request packet testcase is passing .

**Comment by kellyyeh** [comment]
@jsanghra We are seeing constant pass for this test. What image version are you using and what platform are you running this test on?

**Comment by jsanghra** [comment]
@rraguraj : can you please provide this info ?

**Comment by rraguraj** [comment]
@kellyyeh We are using 202012 image on Cisco 8000 platform

**Comment by sachinv-msft** [comment]
@kellyyeh any updates on this PR?

**Comment by rraguraj** [comment]
Created https://github.com/Azure/sonic-mgmt/pull/5441
