### ISSUE TITLE
Need new test: PFC Rx frame counters

### ISSUE THREAD

**Issue by neethajohn** [Azure/sonic-mgmt#3819]
Test steps
* disable pfcwd
* Clear pfc counters prior to the test
* Send PFC frames on a particular priority to the DUT
* Verify using "show pfc counters" that PFC frames are counted only for the respective priority and all other priorities show PFC RX frame count as 0.  Keep polling at regular intervals to ensure that only the correct priority count keeps increasing and all other priorities remain 0
* reenable pfcwd

**Comment by wenyiz2021** [comment]
Sent PR: 
https://dev.azure.com/mssonic/internal/_git/sonic-mgmt-int/pullrequest/287
waiting for Nejo to review
