### ISSUE TITLE
ERROR! The vault password file /var/userlab/sonic-mgmt/ansible/password.txt was not found

### ISSUE THREAD

**Issue by olegroyal** [Azure/sonic-mgmt#382]
**Description**
I'm installing TESTBED SETUP according to
https://github.com/Azure/sonic-mgmt/blob/master/ansible/doc/README.testbed.Setup.md
I'm using Debian 9
I have a problem on the following step : 
 Setup VMs in the server
./testbed-cli.sh start-vms server_1 password.txt

**Steps to reproduce the issue:**
userlab@76c38be6e506:~/sonic-mgmt/ansible$ ./testbed-cli.sh start-vms server_1 password.txt
Starting VMs on server 'server_1'
ERROR! The vault password file /var/userlab/sonic-mgmt/ansible/password.txt was not found

**Comment by stcheng** [comment]
the password file shall be created by users. the user could encrypt some credential files in the vault.

**Comment by lguohan** [comment]
@maggiemsft, can you update the README.testbed.Setup.md to add a note for this?

**Comment by maggiemsft** [comment]
updated readme to instruct user how to get around this
