### ISSUE TITLE
Getting YAML syntax error while running testbed-cli.sh from main.yml

### ISSUE THREAD

**Issue by olegroyal** [Azure/sonic-mgmt#389]
userlab@468bc9854d63:~/sonic-mgmt/ansible$ sudo ./testbed-cli.sh  start-vms server_1 password.txt
Starting VMs on server 'server_1'
ansible-playbook 2.4.2.0
  config file = /var/userlab/sonic-mgmt/ansible/ansible.cfg
  configured module search path = [u'/var/userlab/sonic-mgmt/ansible/library', u'/var/userlab/sonic-mgmt/ansible/library/ixia']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
Using /var/userlab/sonic-mgmt/ansible/ansible.cfg as config file
Parsed /var/userlab/sonic-mgmt/ansible/veos inventory source with ini plugin
Read vars_file 'vars/azure_storage.yml'
Read vars_file 'vars/azure_storage.yml'
ERROR! Syntax Error while loading YAML.

The error appears to have been in '/var/userlab/sonic-mgmt/ansible/roles/vm_set/tasks/main.yml': line 107, column 12, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    src: roles/vm_set/files/vm_resumer.py
    dest: {{ root_path }}
           ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

exception type: <class 'yaml.constructor.ConstructorError'>
exception: while constructing a mapping
  in "<unicode string>", line 107, column 11
found unacceptable key (unhashable type: 'AnsibleMapping')
  in "<unicode string>", line 107, column 12

**Comment by maggiemsft** [comment]
@olegroyal  There is a pull request fixed this already. You may pull the new PR fix.
https://github.com/Azure/sonic-mgmt/pull/386

**Comment by olegroyal** [comment]
After edit I received new error : 
- name: Copy vm_resumer.py to the {{ root_path }}
   become: true
               ^ here

exception type: <class 'yaml.scanner.ScannerError'>
exception: mapping values are not allowed in this context
  in "<unicode string>", line 104, column 10

**Comment by olegroyal** [comment]
after delete all block and copy paste from "github" to file - the problem is resolved , can close it
