### ISSUE TITLE
[Bridge/Vlan MAC] Add test to cover bridge mac and flooding

### ISSUE THREAD

**Issue by prsunny** [Azure/sonic-mgmt#3916]
**Description**

With the support to set Vlan mac, need a test to ensure there is no flooding of traffic for the packets destined to the configured Vlan IP address. This is to ensure Bridge in sonic is not incorrectly flooding the self-destined packets. 

**Steps to reproduce the issue:**
1. Send ICMP packets destined to Vlan IP
2.
3.

**Describe the results you received:**

**Describe the results you expected:**
No flooding of ICMP packets

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
just a control plane test?

**Comment by wangxin** [comment]
@lguohan Sending packets to Vlan IP is dataplane. What do you mean by add control plane test? Can you elaborate?
