### ISSUE TITLE
ImportError: No module named six

### ISSUE THREAD

**Issue by olegroyal** [Azure/sonic-mgmt#392]
**Description**
after run :  ./testbed-cli.sh start-vms server_1 password.txt
receved the following Error : 
```
File "/var/userlab/sonic-mgmt/ansible/shell_plugins/docker.py", line 12, in <module>
    from ansible.compat.six import text_type
ImportError: No module named six

fatal: [STR-ACS-SERV-01]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
        to retry, use: --limit @/var/userlab/sonic-mgmt/ansible/testbed_start_VMs.retry

PLAY RECAP *********************************************************************
STR-ACS-SERV-01            : ok=0    changed=0    unreachable=0    failed=1

Tuesday 19 December 2017  08:05:22 +0000 (0:00:00.040)       0:00:00.136 ******
===============================================================================
Gathering Facts --------------------------------------------------------- 0.04s
 ------------------------------------------------------------------------------
```

**Comment by stcheng** [comment]
which ansible version are you using?

**Comment by olegroyal** [comment]
userlab@468bc9854d63:~/sonic-mgmt/ansible$ ansible --version
ansible 2.4.2.0
  config file = /var/userlab/sonic-mgmt/ansible/ansible.cfg
  configured module search path =
[u'/var/userlab/sonic-mgmt/ansible/library',
u'/var/userlab/sonic-mgmt/ansible/library/ixia']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0
20160609]

2017-12-20 2:44 GMT+02:00 Shuotian Cheng <notifications@github.com>:

**Comment by olegroyal** [comment]
userlab@468bc9854d63:~/sonic-mgmt/ansible$ ansible --version
ansible 2.4.2.0
  config file = /var/userlab/sonic-mgmt/ansible/ansible.cfg
  configured module search path = [u'/var/userlab/sonic-mgmt/ansible/library', u'/var/userlab/sonic-mgmt/ansible/library/ixia']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]

**Comment by maggiemsft** [comment]
our current support ansible version is 2.0.0.2
https://github.com/Azure/sonic-mgmt/blob/master/ansible/README.md
we are going to upgrade to newest Ansible soon. there are some incompatibility between Ansible 2.0.0.2 and 2.4.x. 
So could you downgrade to Ansible 2.0.0.2 to run current tests?

**Comment by olegroyal** [comment]
Ok thank you I will try it
