### ISSUE TITLE
[Nokia] platform_tests/api/test_watchdog.py test failure

### ISSUE THREAD

**Issue by Blueve** [Azure/sonic-mgmt#3958]
**Description**
Test failures seen in Nokia platform.
Watchdog is required feature.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by dflynn-Nokia** [comment]
This issue has been fixed in sonic-buildimage PR# [8377](https://github.com/Azure/sonic-buildimage/pull/8377)
