### ISSUE TITLE
make configure PLATFORM=generic - fail

### ISSUE THREAD

**Issue by olegroyal** [Azure/sonic-mgmt#399]
**Description**

During "Setup docker registry for PTF docker" 
https://github.com/Azure/sonic-mgmt/blob/master/ansible/doc/README.testbed.Setup.md
**Steps to reproduce the issue:**
1.  git clone --recursive https://github.com/Azure/sonic-buildimage.git  - Ok 
2. make configure PLATFORM=generic
 I received : 
Step 9/17 : RUN useradd $user -l -u $uid -g $guid -d /var/$user -m -s /bin/bash
 ---> Running in b1ede7d1f5ae
useradd: user 'root' already exists
The command '/bin/sh -c useradd $user -l -u $uid -g $guid -d /var/$user -m -s /b                                                                                     in/bash' returned a non-zero code: 9
Makefile:77: recipe for target 'configure' failed
make: *** [configure] Error 9

**Comment by maggiemsft** [comment]
could you use a regular user, not user 'root'?

**Comment by olegroyal** [comment]
I used regular user and commands via SUDO

**Comment by maggiemsft** [comment]
try no sudo, only make?

**Comment by olegroyal** [comment]
with su -- ??

**Comment by maggiemsft** [comment]
Is it possible to not using any ‘su’?
I think the root user will conflict with the docker slave while build.
If no ‘su’, any error?

**Comment by olegroyal** [comment]
I will try any combination , thank you for supporting .
