### ISSUE TITLE
Using Ansible to executed COPP Test, Ansible hangs up

### ISSUE THREAD

**Issue by huanchen** [Azure/sonic-mgmt#401]
Using Ansible to executed COPP Test, Ansible hangs up。

RUN TEST ：

ansible-playbook -i lab --limit dut-nephos-01 test_sonic.yml -e "testcase_name=copp testbed_type=ptf32 testbed_name=ptf1-m ptf_host=10.255.0.188"

-----------------------------------------------------------------------------

TASK [test : PTF Test - COPP test - ARPTest] 
Wednesday 27 December 2017  18:56:49 +0000 (0:00:00.211)       0:00:13.645 
ok: [dut-nephos-01] => {
    "msg": "ptf --test-dir ptftests copp_tests.ARPTest  --qlen=100000   --platform nn  -t \"verbose=False;pkt_tx_count=0\"  --device-socket 0-3@tcp://127.0.0.1:10900 --device-socket 1-3@tcp://10.251.0.188:10900 --disable-vxlan --disable-geneve --disable-erspan --disable-mpls --disable-nvgre 2>&1"
}

TASK [test : command]
Wednesday 27 December 2017  18:56:49 +0000 (0:00:00.251)       0:00:13.896 

------------------------------------------------------------------------------------------------------------------

Then Ansible-playbooks hangs up

I connect PTF docker，cat the info of the ptf.log as follows

--------------------------------------------------------------------------------------------------------------

18:56:49.755  root      : INFO    : Wed Dec 27 18:56:49 2017
18:56:49.783  scapy.loading: WARNING : Failed to execute tcpdump. Check it is installed and in the PATH
18:56:49.813  scapy.runtime: WARNING : No route found for IPv6 destination :: (no default route?)
18:56:49.927  root      : INFO    : Importing platform: nn
18:56:49.928  root      : DEBUG   : Configuration: {'xunit_dir': 'xunit', 'disable_ipv6': False, 'minsize': 0, 'list_test_names': False, 'test_file': None, 'test_spec': '', 'allow_user': False, 'test_order_seed': 2746, 'default_negative_timeout': 0.1, 'platform': 'nn', 'log_dir': None, 'xunit': False, 'disable_erspan': True, 'device_sockets': [(0, set([3]), 'tcp://127.0.0.1:10900'), (1, set([3]), 'tcp://10.251.0.188:10900')], 'disable_geneve': True, 'socket_recv_size': 4096, 'profile': False, 'default_timeout': 2.0, 'platform_args': None, 'relax': False, 'random_seed': None, 'interfaces': [], 'test_case_timeout': None, 'port_map': {(0, 3): 'tcp://127.0.0.1:10900', (1, 3): 'tcp://10.251.0.188:10900'}, 'disable_vxlan': True, 'disable_nvgre': True, 'qlen': 100000, 'test_order': 'default', 'profile_file': 'profile.out', 'fail_skipped': False, 'test_params': 'verbose=False;pkt_tx_count=0', 'test_dir': 'ptftests', 'list': False, 'platform_dir': '/usr/lib/python2.7/dist-packages/ptf/platforms', 'disable_mpls': True, 'debug': 'verbose', 'log_file': 'ptf.log', 'failfast': False}
18:56:49.928  root      : INFO    : port map: {(0, 3): 'tcp://127.0.0.1:10900', (1, 3): 'tcp://10.251.0.188:10900'}
18:56:49.928  root      : INFO    : Autogen random seed: 31938508

-----------------------------------------------------------------------------------------------------------------

 I try to ping sonic switch in ptf docker ,it is reachable

-----------------------------------------------------------------------------------

 ping 10.0.0.0

64 bytes from 10.0.0.0: icmp_seq=1 ttl=64 time=3.36 ms

 ping 10.0.0.2

64 bytes from 10.0.0.2: icmp_seq=1 ttl=64 time=2.46 ms

---------------------------------------------------------------------------------------

If someone encountered a similar problem ,please give me a solution, thanks

**Comment by pavel-shirshov** [comment]
Hi,

The copp test could freeze when there no connectivity to a ptf agent on local (ptf container) or remote (dut) side.
I'd suggest you to check that:
1. ptf_nn_agent.py is running in your ptf container
2. ptf_nn_agent.py is running on your DUT. It should be running inside of syncd container. If it's not. You're probably using regular syncd container. Instead you should use syncd-rpc container, which has ptf_nn_agent.py inside of it.

Let me know if you have more questions.

**Comment by pavel-shirshov** [comment]
Closing the issue as outdated
