### ISSUE TITLE
We found error message when testing 202012 image. Before this commit the test could pass. So we need revert this PR.

### ISSUE THREAD

**Issue by qiluo-msft** [Azure/sonic-mgmt#4061]
We found error message when testing 202012 image. Before this commit the test could pass. So we need revert this PR.

```
    @pytest.fixture(scope='function')
    def wait_for_counters(duthosts, rand_one_dut_hostname):
        duthost = duthosts[rand_one_dut_hostname]
        logger.info('Wait until all counters are enabled on the DUT')
        counters = ['PORT_STAT', 'PORT_BUFFER_DROP', 'QUEUE_STAT', 'PG_WATERMARK_STAT', 'RIF_STAT']
        current_attempt = 0
        while current_attempt < WAIT_FOR_COUNTERS_TIMEOUT / WAIT_FOR_COUNTERS_INTERVAL:
            output = duthost.shell("counterpoll show | sed '1,2d'", module_ignore_errors=True)
            assert output.has_key('rc') and output['rc'] == 0, "Failed to get counters status"
            counters_lines = output['stdout'].splitlines()
            enabled_counters = 0
            for line in counters_lines:
                if any(counter in line for counter in counters) and 'enable' in line:
                    enabled_counters += 1
                    continue
            if enabled_counters == len(counters):
                return
            else:
                current_attempt += 1
                time.sleep(WAIT_FOR_COUNTERS_INTERVAL)
>       assert False, "Not all counters are enabled after {} seconds".format(WAIT_FOR_COUNTERS_TIMEOUT)
E       AssertionError: Not all counters are enabled after 190 seconds
```

_Originally posted by @qiluo-msft in https://github.com/Azure/sonic-mgmt/issues/3903#issuecomment-900750279_

**Comment by qiluo-msft** [comment]
@shlomibitton Could you please check this issue on your PR?

**Comment by shlomibitton** [comment]
> @shlomibitton Could you please check this issue on your PR?

@qiluo-msft The assertion is because the counters were not enabled on the DUT, this is expected to fail if this is the case.
We can increase the timeout of this procedure to a bigger one, but I think we should check why the counters are not enabled after 190 seconds, do you have logs we can check from the DUT while running this test?

**Comment by sanmalho-git** [comment]
This fixture was added to snmp tests (tests/snmp/conftest.py). Two issues:
- The snmp tests have been converted to use run on a multi-dut setup (VoQ chassis) and thus use 'enum_rand_one*" fixtures. This fixture is using 'rand_one_dut_hostname'. Both these fixtures are mutually exclusive. 
      - Fix for this would be use not add rand_one_dut_hostname, but iterate through all the duts in duthosts.
- Not sure if 'counterpoll show' command has been adjusted for multi-asic support yet.
