### ISSUE TITLE
 [directed broadcast] How to configure DUT for directed broadcast?

### ISSUE THREAD

**Issue by okanchou9** [Azure/sonic-mgmt#422]
**Description**

Hi,

Would like to know is there any extra configuration for bcast test?
I'm trying to run this test on my DUT with t0 topology but getting failed since DUT didn't broadcast the test packet from portchannel interface to vlan network.

**Describe the results you received:**

Getting failed in bcast test.

**Describe the results you expected:**

Passed the bcast test or would like to know detailed about this test.

Please let me know if any, thanks.

---
Regards,
Kenie Liu

**Comment by cytsai0409** [comment]
More specifically, we are running the directed broadcast test(#377) .

We would like to know if directed broadcast is default enabled on DUT? Or we need to update some configuration file or run some command on DUT to manually enable directed broadcast?

We searched the directed broadcast feature on Linux and does not find useful information.

@prsunny 
Could you give us some suggestions about how to configure DUT for directed broadcast test?

Thanks.

**Comment by cytsai0409** [comment]
@maggiemsft 
Hi, maggie, sorry to bother you again.
Do you know who has experience on testing the directed broadcast test([#377](https://github.com/Azure/sonic-mgmt/pull/377))? 

We would like to know if directed broadcast is default enabled on DUT? Or we need to update some configuration file or run some command on DUT to manually enable directed broadcast?

Our DUT received the DHCP request packet but doesn't broadcast it to the vlan interfaces.

Cisco devices has specific command to manually enable the directed broadcast for security reason. So we think we might miss some configuration steps on DUT.

Could you give us some suggestions?

Thanks.

**Comment by prsunny** [comment]
Sorry for the late response. Directed broadcast is NOT default enabled on DUT. This is a feature that shall be available once the following PR is merged:

https://github.com/Azure/sonic-swss/pull/412

This is currently pending on support by SAI.

**Comment by cytsai0409** [comment]
Hi, Sunny:
Ok, got it. We will test this feature on our platforms after the PR is merged.
Thanks for your response.

**Comment by okanchou9** [comment]
@prsunny 

Thank you very much for the information about this test.
Will try to test this feature again when the PR is merged.

---
Best regards,
Kenie Liu
