### ISSUE TITLE
Cleanup of portchannel interfaces, to cover all cases.

### ISSUE THREAD

**Issue by judyjoseph** [Azure/sonic-mgmt#4245]
**Description**

There is a testcase already existing test_po_cleanup.py 
This issue is fixed in version > 201911.73

But this testcase to be tuned to take care of more scenario's like does the cleanup happen on a CPU with low number of cores also ?

**Steps to reproduce the issue:**
1. Do a config reload on a low CPU device ( a device with lower number of CPU cores )  
2. The device will have a large number of portchannels.
3. Check if the portchannels are cleaned correctly.

**Describe the results you received:**
The portchannels were not cleanup correctly.

**Describe the results you expected:**
All portchannel interfaces should be cleaned up from the kernel.

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by abdosi** [comment]
@judyjoseph as discussed to add is to scale to more port-channels then natively supported by the testbed topology by adding them as Statically.  This way we are not dependent on portchannel created by testbed topo.

**Comment by judyjoseph** [comment]
> @judyjoseph, @abdosi we also run this test on T1, where we have 24 port channels, do you want to see even larger scale?

@Ying, the scale of 24 should be good enough. My idea was to add a few of these 
1. Add some sort of a controlled loop with sleep in between -- so that the system is stressed and CPU is loaded while the cleanup is being done. Make sure the portchannels are cleanup correctly. ( This new issue we saw was only in 2700 - which has a low power CPU)
2. Also will add an explicit config reload/load-minigraph command + check the logs to make sure Port channels are cleaned up 

will raise a PR for this.
