### ISSUE TITLE
Router-MAC should not be Learnt.

### ISSUE THREAD

**Issue by abdosi** [Azure/sonic-mgmt#4282]
Issue#

From SONiC side expected behavior is that we should not do L2 Learn of Source Mac if it is MY-Mac/Self-Router-MAC.
And in case even if it get learnt it should get Age Out eventually if there is no traffic with Router-MAC as Source Address.

Add a test case to send packet with Router-Mac as SA and check it should not learnt and if learnt should get age out eventually.

**Comment by bingwang-ms** [comment]
How to define MY-Mac/Self-Router-MAC ? Is it MAC of vlan or physical interface?
And how do we understand `in case even if it get learnt it should get Age Out eventually` ? The learnt MAC will expire even it's not MY-MAC.
