### ISSUE TITLE
[multi-asic][vs]: Deploy minigraph broken

### ISSUE THREAD

**Issue by SuvarnaMeenakshi** [Azure/sonic-mgmt#4343]
**Description**

**Steps to reproduce the issue:**
1. Bring up multi-asic VS testbed using 4-asic VS image from: https://artprodcus3.artifacts.visualstudio.com/Af91412a5-a906-4990-9d7c-f697b81fc04d/be1b070f-be15-4154-aade-b1d3bfb17054/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zc29uaWMvcHJvamVjdElkL2JlMWIwNzBmLWJlMTUtNDE1NC1hYWRlLWIxZDNiZmIxNzA1NC9idWlsZElkLzM4MjQ4L2FydGlmYWN0TmFtZS9zb25pYy1idWlsZGltYWdlLnZz0/content?format=file&subPath=%2Ftarget%2Fsonic-4asic-vs.img.gz.
wget -O sonic-vs.img.gz "https://artprodcus3.artifacts.visualstudio.com/Af91412a5-a906-4990-9d7c-f697b81fc04d/be1b070f-be15-4154-aade-b1d3bfb17054/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zc29uaWMvcHJvamVjdElkL2JlMWIwNzBmLWJlMTUtNDE1NC1hYWRlLWIxZDNiZmIxNzA1NC9idWlsZElkLzM4MjQ4L2FydGlmYWN0TmFtZS9zb25pYy1idWlsZGltYWdlLnZz0/content?format=file&subPath=%2Ftarget%2Fsonic-4asic-vs.img.gz"
2. Place the above image in ~/sonic-vm/images and follow steps to bring up vs testbed.
3. ./testbed-cli.sh -t vtestbed.csv -m veos_vtb -k ceos add-topo vms-kvm-four-asic-t1-lag password.txt
4. deploy minigraph: ./testbed-cli.sh -t vtestbed.csv -m veos_vtb deploy-mg vms-kvm-four-asic-t1-lag veos_vtb password.txt.
deploy minigraph fails with this error:
```
TASK [find interface name mapping and individual interface speed if defined from dut] *************************************************************************************************************************
Friday 24 September 2021  01:13:32 +0000 (0:00:00.547)       0:00:02.145 ****** 
[WARNING]: Platform linux on host vlab-08 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information.

fatal: [vlab-08]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "failed to find the correct port config for msft_four_asic_vslist index out of range"}
```
This is due to https://github.com/Azure/sonic-mgmt/pull/3746 commit.
https://github.com/Azure/sonic-mgmt/blob/master/ansible/library/port_alias.py#L262 - switchid default value is [0] and here n-asic id reference is done. Same referencing is done in minigraph_meta.j2 template. 

deploy-mg is successful if I revert the above commit.

**Describe the results you received:**
deploy-mg on multi-asic testbed fails with an error failed to find the correct port config for msft_four_asic_vslist index out of range
/testbed-cli.sh -t vtestbed.csv -m veos_vtb deploy-mg vms-kvm-four-asic-t1-lag veos_vtb password.txt

**Describe the results you expected:**

deploy-mg should be successful.
**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by SuvarnaMeenakshi** [comment]
@sanmalho-git can you please take a look at this issue.

**Comment by sanmalho-git** [comment]
@SuvarnaMeenakshi - PR https://github.com/Azure/sonic-mgmt/pull/4420 fixes this issue. Can you please review the PR

**Comment by SuvarnaMeenakshi** [comment]
Issue resolved
