### ISSUE TITLE
[arp_responder] Possible improvement for the way of filter ARP packets

### ISSUE THREAD

**Issue by keboliu** [Azure/sonic-mgmt#442]
In the current implementation of arp_responder, it captures all the packets and then filter the arp packets by the length of packets:

`ETH_P_ALL = 0x03`
`...`
`self.socket = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(self.ETH_P_ALL))`
`...`
`if len(data) != self.ARP_PKT_LEN:`

Why not capture ARP packets directly by defining a more accurate packet type?  like:

 `ETH_P_ARP = 0x806`
`...`
`self.socket = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(self.ETH_P_ARP))` 

by this can make arp_responder more efficient and avoid to capture some other type of packets which also have the same length.

**Comment by pavel-shirshov** [comment]
Hi Kebo,

I agree with you that we might use ETH_P_ARP datatype.
But in our case we have low amount of packets from DUT (ARP requests + LLDP announces once a half of minute).
Also when I developed this arp_responder I thought about possibility of using the same code for receiving ICMPv6 requests. So ETH_P_ALL was conscious choice here.
