### ISSUE TITLE
T0/T1:autorestart/test_container_autorestart.py failed due to CONTAINER_NAME_REGEX does not match mgmt-framework

### ISSUE THREAD

**Issue by rraguraj** [Azure/sonic-mgmt#4466]
(1 test case failing)
test_container_autorestart failed for mgmt-framework since CONTAINER_NAME_REGEX does not match mgmt-framework

File "/data/tests/autorestart/test_container_autorestart.py", line 99, in ignore_expected_loganalyzer_exception
    feature = re.match(CONTAINER_NAME_REGEX, container_name).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

In test_container_autorestart.py:
CONTAINER_NAME_REGEX = (r"([a-zA-Z_]+)(\d*)$") 

This above change has gone as part of https://github.com/Azure/sonic-mgmt/pull/3696 

Workaround used to match the mgmt-framework:
CONTAINER_NAME_REGEX = (r"([a-zA-Z_-]+)(\d*)$")

**Comment by yxieca** [comment]
@rraguraj do you want to create PR to submit the suggested change and link to fix this issue?
