### ISSUE TITLE
SCP Test failing because pexpect module is missing

### ISSUE THREAD

**Issue by sumukhatv** [Azure/sonic-mgmt#4480]
**Description**
The SCP test is failing because the `pexpect` module is not present .

```
E               "msg": "non-zero return code", 
E               "rc": 1, 
E               "start": "2021-10-13 17:33:00.144688", 
E               "stderr": "Traceback (most recent call last):\n  File \"perform_scp.py\", line 1, in <module>\n    import pexpect\nImportError: No module named 'pexpect'", 
E               "stderr_lines": [
E                   "Traceback (most recent call last):", 
E                   "  File \"perform_scp.py\", line 1, in <module>", 
E                   "    import pexpect", 
E                   "ImportError: No module named 'pexpect'"
E               ], 
E               "stdout": "", 
E               "stdout_lines": []
```

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by aurghob** [comment]
Looking into it.

The tests had passed right after merge to master: https://github.com/Azure/sonic-mgmt/runs/3637947195 .

However, something must have changed afterwards in the python3 libraries that are installed on the DUT.
I'll try a couple of workarounds for now.

**Comment by aurghob** [comment]
Will try to pick this up next week and try to replicate issue with @sumukhatv's help

**Comment by aurghob** [comment]
Was able to reproduce the failure after using the 201911 image for sonic for the DUT. Also confirmed that 201911 image is the one that is running on the systems used. I did not know that there is a separate pipeline other than the github pipeline. python2 has pexpect for this image rather than python3. Will try to include a small fix for this.
