### ISSUE TITLE
packets with FCS checksum added are considered invalid

### ISSUE THREAD

**Issue by vikneels** [Azure/sonic-mgmt#4622]
As part of the below code in advanced_reboot test, we create exp_packet. However, the packet that was constructed is of 60 bytes and during pkt_match, test fails any packet with size > 60. However we could receive packets of size 64 bytes (valid eth frame with fcs added) which was considered invalid and initialization fails.  We might need to add ignore_extra_bytes when we create mask for exp_packet).

def generate_ping_dut_lo(self):
       ...

        self.ping_dut_exp_packet  = Mask(exp_packet)
        self.ping_dut_exp_packet.set_do_not_care_scapy(scapy.Ether, "dst")
        self.ping_dut_exp_packet.set_do_not_care_scapy(scapy.IP, "dst")
        self.ping_dut_exp_packet.set_do_not_care_scapy(scapy.IP, "id")
        self.ping_dut_exp_packet.set_do_not_care_scapy(scapy.IP, "chksum")

For instance, in one case exp packet was   

00 01 02 03 04 05 64 3A  EA C1 73 F8 08 00 45 00   
00 2E 00 01 00 00 40 01  AF D4 0A 01 00 20 C0 A8  
00 31 00 00 4E 4E 00 00  00 00 30 30 30 30 30 30  
30 30 30 30 30 30 30 30  30 30 30 30  
<details>
Frame 1: 60 bytes on wire (480 bits), 60 bytes captured (480 bits)
Encapsulation type: Ethernet (1)
Arrival Time: Nov 3, 2021 22:13:05.000000000 UTC
Time shift for this packet: 0.000000000 seconds
Epoch Time: 1635977585.000000000 seconds
Time delta from previous captured frame: 0.000000000 seconds
Time delta from previous displayed frame: 0.000000000 seconds
Time since reference or first frame: 0.000000000 seconds
Frame Number: 1
Frame Length: 60 bytes (480 bits)
Capture Length: 60 bytes (480 bits)
Frame is marked: False
Frame is ignored: False
Protocols in frame: eth:ethertype:ip:icmp:data
Ethernet II, Src: 64:3a:ea:c1:73:f8 (64:3a:ea:c1:73:f8), Dst: 3Com_03:04:05 (00:01:02:03:04:05)
Destination: 3Com_03:04:05 (00:01:02:03:04:05)
Source: 64:3a:ea:c1:73:f8 (64:3a:ea:c1:73:f8)
Type: IPv4 (0x0800)
Internet Protocol Version 4, Src: 10.1.0.32, Dst: 192.168.0.49
0100 .... = Version: 4
.... 0101 = Header Length: 20 bytes (5)
Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
Total Length: 46
Identification: 0x0001 (1)
Flags: 0x0000
Time to live: 64
Protocol: ICMP (1)
Header checksum: 0xafd4 [correct]
Header checksum status: Good
Calculated Checksum: 0xafd4
Source: 10.1.0.32
Source or Destination Address: 10.1.0.32
Source Host: 10.1.0.32
Source or Destination Host: 10.1.0.32
Destination: 192.168.0.49
Source or Destination Address: 192.168.0.49
Destination Host: 192.168.0.49
Source or Destination Host: 192.168.0.49
Internet Control Message Protocol
Type: 0 (Echo (ping) reply)
Code: 0
Checksum: 0x4e4e [correct]
Checksum Status: Good
Identifier (BE): 0 (0x0000)
Identifier (LE): 0 (0x0000)
Sequence number (BE): 0 (0x0000)
Sequence number (LE): 0 (0x0000)
data
Data: 303030303030303030303030303030303030
Length: 18
</details>

However from DUT, packet got was
72 06 00 01 00 45 64 3a ea c1 73 f8 08 00 45 00 
00 2e 5a fc 00 00 40 01 54 db 0a 01 00 20 c0 a8
00 2f 00 00 4e 4e 00 00 00 00 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 31 c9 04 00

which is valid one with frame check seq(31c90400) added at end. Since by default Ethernet FCS is computed and updated for every packet in NPU by default. This was considered invalid packet and init fails.

<details>
Frame 1: 64 bytes on wire (512 bits), 64 bytes captured (512 bits)
Encapsulation type: Ethernet (1)
Arrival Time: Nov 3, 2021 22:20:07.000000000 UTC
Time shift for this packet: 0.000000000 seconds
Epoch Time: 1635978007.000000000 seconds
Time delta from previous captured frame: 0.000000000 seconds
Time delta from previous displayed frame: 0.000000000 seconds
Time since reference or first frame: 0.000000000 seconds
Frame Number: 1
Frame Length: 64 bytes (512 bits)
Capture Length: 64 bytes (512 bits)
Frame is marked: False
Frame is ignored: False
Protocols in frame: eth:ethertype:ip:icmp:data
Ethernet II, Src: 64:3a:ea:c1:73:f8 (64:3a:ea:c1:73:f8), Dst: 72:06:00:01:00:45 (72:06:00:01:00:45)
Destination: 72:06:00:01:00:45 (72:06:00:01:00:45)
Source: 64:3a:ea:c1:73:f8 (64:3a:ea:c1:73:f8)
Type: IPv4 (0x0800)
Frame check sequence: 0x31c90400
Internet Protocol Version 4, Src: 10.1.0.32, Dst: 192.168.0.47
0100 .... = Version: 4
.... 0101 = Header Length: 20 bytes (5)
Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
Total Length: 46
Identification: 0x5afc (23292)
Flags: 0x0000
Time to live: 64
Protocol: ICMP (1)
Header checksum: 0x54db [correct]
Header checksum status: Good
Calculated Checksum: 0x54db
Source: 10.1.0.32
Source or Destination Address: 10.1.0.32
Source Host: 10.1.0.32
Source or Destination Host: 10.1.0.32
Destination: 192.168.0.47
Source or Destination Address: 192.168.0.47
Destination Host: 192.168.0.47
Source or Destination Host: 192.168.0.47
Internet Control Message Protocol
Type: 0 (Echo (ping) reply)
Code: 0
Checksum: 0x4e4e [correct]
Checksum Status: Good
Identifier (BE): 0 (0x0000)
Identifier (LE): 0 (0x0000)
Sequence number (BE): 0 (0x0000)
Sequence number (LE): 0 (0x0000)
data
Data: 303030303030303030303030303030303030
Length: 18

</details>

The above packet fails the pkt_match since the size is 64 against 60(that was expected). 

    def pkt_match(self, pkt):
        # just to be on the safe side
        pkt = bytearray(bytes(pkt))
        # we fail if we don't match on sizes, or if ignore_extra_bytes is set,
        # fail if we have not received at least size bytes
        if (not self.ignore_extra_bytes and len(pkt) != self.size) or len(
            pkt
        ) < self.size:
            return False
        exp_pkt = bytearray(bytes(self.exp_pkt))
        for i in range(self.size):
            if (exp_pkt[i] & self.mask[i]) != (pkt[i] & self.mask[i]):
                return False
        return True

Wondering if there is any reason the expectation is not to have FCS padded at the end from test pov?

**Comment by yxieca** [comment]
@vaibhavhd did we see same issue in our nightly test?

**Comment by vikneels** [comment]
The DUT is padding random 4 bytes value in the tail end of packet to make it 64 bytes. Since it is not actual FCS for the Ethernet frame,  nic is not stripping it. Packet decoder misled us to believe that 4 bytes as Ethernet FCS based on the field position in the packet.
