### ISSUE TITLE
[ARP test] can ARP test run on t0 topology?

### ISSUE THREAD

**Issue by keboliu** [Azure/sonic-mgmt#481]
Regarding ARP test in the [wiki](https://github.com/Azure/sonic-mgmt/blob/master/ansible/README.test.md#arp-tests) it mentioned that it can run when it connected to a PTF testbed. 

If we look into the test case, it's assigning IP address on Ethernet4 and Ethernet8, and expecting these two interfaces can response to the ARP request.

```
    - name: change SONiC DUT interface IP to test IP address
      command: /sbin/ifconfig  Ethernet4 10.10.1.2 netmask 255.255.255.240
      become: yes

    - name: change SONiC DUT interface IP to test IP address
      command: /sbin/ifconfig  Ethernet8 10.10.1.20 netmask 255.255.255.240
      become: yes
```
In the t0 configuration, Ethernet4 and Ethernet8 are untagged member ports of Vlan1000, will have issue if assign IP address to them.

```
    "VLAN_MEMBER": {
        "Vlan1000|Ethernet4": {
            "tagging_mode": "untagged"
        }, 
        "Vlan1000|Ethernet8": {
            "tagging_mode": "untagged"
        }, 

```
 Shall we add restriction to this test that it is not able to run on t0?

**Comment by maggiemsft** [comment]
ARP won't be able to run on t0, this test was originally written to be only run ptf topology
all test cases are summarized here with supported topology and required variables 
https://github.com/Azure/sonic-mgmt/blob/master/ansible/roles/test/vars/testcases.yml
