### ISSUE TITLE
[platform_tests] Test thermal_state_db.py pulls duplicated data causing test failure

### ISSUE THREAD

**Issue by amulyan7** [Azure/sonic-mgmt#5007]
The test case fails because there is a mismatch in the number of thermal_sensors read from redis-dump command and output of "show platform temperature"
The reason for mismatch is linked to the key match "\*TEMP\*"
With this key match, redis-dump pulls up entries from another table (PHYSICAL_ENTITY_INFO) with sensor names containing the word TEMP in them along with entries from TEMPERATURE_INFO table, whereas it is compared against output of "show platform temperature" which pulls data only from TEMPERATURE_INFO table. Ideally redis should only fetch data from TEMPERATURE_INFO table

This can be avoided this by changing the key match to either "TEMP*" or using full table name "TEMPERATURE_INFO*"

**Comment by anamehra** [comment]
@abdosi FYI-

**Comment by abdosi** [comment]
@amulyan7 please create PR for fixing this.

cc @judyjoseph
