### ISSUE TITLE
[ test_reboot ] has been skipped for almost all platforms and vendors

### ISSUE THREAD

**Issue by SavchukRomanLv** [Azure/sonic-mgmt#5161]
**Description**
After PR https://github.com/Azure/sonic-mgmt/pull/4624 platform_test/test_reboot has been skipped for almost all platforms except a few that has "port_type" provided in hwsku.json  [port_type](https://github.com/Azure/sonic-buildimage/search?p=1&q=%27port_type%27)

**This fix has few negative impacts for community:**

1. Skip cases for most supported platforms.
2. Skip added inside function that check interfaces and services that happens after reboot - so basically TC performs set up procedure, than reboot DUT and only after skipped. 
3. Even when "port_type" will be provided check expects at least 1 port has port_type="RJ45", if platform does not have it - test case will be skipped also.

**Steps to reproduce the issue:**
1. Run TC from platform_tests/test_reboot.py

**Describe the results you received:**
TC skipped with error: "XFailed: hwsku.json is needed for interface checking to pass, and it is not provided."

**Describe the results you expected:**
TC passed or failed 

**Additional information you deem important:**

**show version output:** 
SONiC Software Version: SONiC.master.71470-dirty-20220210.193335
Distribution: Debian 11.2
Kernel: 5.10.0-8-2-amd64
Build commit: 914a8a175
Build date: Thu Feb 10 19:42:04 UTC 2022
Built by: AzDevOps@sonic-build-workers-0015U1

Platform: x86_64-accton_as9516_32d-r0
HwSKU: newport
ASIC: barefoot
    ```
  
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by SavchukRomanLv** [comment]
@neethajohn @wangxin @yxieca  could smbd take a look? Thank you

**Comment by yxieca** [comment]
@Xichen96, @Blueve  can you look into if there is a way to enable reboot test on platforms without platform.json?
