### ISSUE TITLE
service_acl, there is no file acl.json

### ISSUE THREAD

**Issue by akenliu** [Azure/sonic-mgmt#524]
**Description**

we get the fail messages when we run the test item of service_acl.
The first line of service_acl.yml checks the file of acl.json, but it does not exist.
What is the content of the acl.json or where do we need to copy from?

**Describe the results you received:**

TASK [test : Check for existence of /etc/sonic/acl.json (this also ensures we can successfully SSH to the DuT)] ***
task path: /var/polly_hsu/sonic-mgmt/ansible/roles/test/tasks/service_acl.yml:1
Sunday 18 March 2018  14:58:47 +0000 (0:00:00.274)       0:00:17.024 ********** 
<10.250.0.196> ESTABLISH SSH CONNECTION FOR USER: admin
<10.250.0.196> SSH: EXEC sshpass -d15 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=120s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o User=admin -o ConnectTimeout=10 -o ControlPath=/var/polly_hsu/.ansible/cp/ansible-ssh-%h-%p-%r 10.250.0.196 '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=fzzcgspdpasbawuccxdodolyunswmane] password: " -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-fzzcgspdpasbawuccxdodolyunswmane; LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/python'"'"'"'"'"'"'"'"''"'"''
fatal: [str-dut-01]: FAILED! => {"changed": false, "failed": true, "failed_when_result": true, "invocation": {"module_args": {"checksum_algorithm": "sha1", "follow": false, "get_checksum": true, "get_md5": true, "path": "/etc/sonic/acl.json"}, "module_name": "stat"}, "stat": {"exists": false}}

**Describe the results you expected:**
There should be a acl.json for this test item.

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lvphuc133** [comment]
I have the same problem. The script couldn't fine the acl.json file in folder /etc/sonic/

**Comment by lvphuc133** [comment]
@akenliu,

Can you create an empty JSON file for it and try the test?
cat /etc/sonic/acl.json
{}
I tried that and it passed the file check step. But there is another issues for the next steps.
The script applies new ACL rules to filter connections for SSH and SNMP.

$ show acl rule 
Rule ID    Rule Name     Priority    Action    Match
---------  ------------  ----------  --------  ------------------
SNMP_ACL   RULE_1        9999        ACCEPT    IP_PROTOCOL: 17
                                               SRC_IP: 1.1.1.1/32
SSH_ONLY   RULE_1        9999        ACCEPT    IP_PROTOCOL: 6
                                               SRC_IP: 1.1.1.1/32
SNMP_ACL   DEFAULT_RULE  1           DROP      ETHER_TYPE: 2048
SSH_ONLY   DEFAULT_RULE  1           DROP      ETHER_TYPE: 2048

$ show acl table
Name      Type       Binding      Description
--------  ---------  -----------  -------------
EVERFLOW  MIRROR     Ethernet0    EVERFLOW
                     Ethernet4
                     Ethernet8
                     Ethernet12
                     Ethernet16
                     Ethernet20
                     Ethernet24
                     Ethernet28
                     Ethernet32
                     Ethernet36
                     Ethernet40
                     Ethernet44
                     Ethernet48
                     Ethernet52
                     Ethernet56
                     Ethernet60
                     Ethernet64
                     Ethernet68
                     Ethernet72
                     Ethernet76
                     Ethernet80
                     Ethernet84
                     Ethernet88
                     Ethernet92
                     Ethernet96
                     Ethernet100
                     Ethernet104
                     Ethernet108
                     Ethernet112
                     Ethernet116
                     Ethernet120
                     Ethernet124
SNMP_ACL  CTRLPLANE  SNMP         SNMP_ACL
SSH_ONLY  CTRLPLANE  SSH          SSH_ONLY
DATAACL   L3         Ethernet0    DATAACL
                     Ethernet4
                     Ethernet8
                     Ethernet12
                     Ethernet16
                     Ethernet20
                     Ethernet24
                     Ethernet28
                     Ethernet32
                     Ethernet36
                     Ethernet40
                     Ethernet44
                     Ethernet48
                     Ethernet52
                     Ethernet56
                     Ethernet60
                     Ethernet64
                     Ethernet68
                     Ethernet72
                     Ethernet76
                     Ethernet80
                     Ethernet84
                     Ethernet88
                     Ethernet92
                     Ethernet96
                     Ethernet100
                     Ethernet104
                     Ethernet112
                     Ethernet116
                     Ethernet120

But I am still able to to open SSH connection and query the switch using SNMPget.

Do you see the same thing?

**Comment by akenliu** [comment]
We ever used the file acl.json in the folder sonic-mgmt/ansible/roles/test/tasks/crm/, but the result was fail.
----------------------------------------------------------------
TASK [test : Ensure the SSH port on the DuT becomes closed to us] **************
task path: /var/polly_hsu/sonic-mgmt/ansible/roles/test/tasks/service_acl.yml:33
Friday 16 March 2018  02:48:33 +0000 (0:00:00.288)       0:00:19.689 ********** 
ESTABLISH LOCAL CONNECTION FOR USER: polly_hsu
10.250.0.196 EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1521168513.44-2479389087250 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1521168513.44-2479389087250 )" )
10.250.0.196 PUT /tmp/tmpX2fN0O TO /var/polly_hsu/.ansible/tmp/ansible-tmp-1521168513.44-2479389087250/wait_for
10.250.0.196 EXEC LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/python /var/polly_hsu/.ansible/tmp/ansible-tmp-1521168513.44-2479389087250/wait_for; rm -rf "/var/polly_hsu/.ansible/tmp/ansible-tmp-1521168513.44-2479389087250/" > /dev/null 2>&1
fatal: [str-dut-01]: FAILED! => {"changed": false, "elapsed": 15, "failed": true, "invocation": {"module_args": {"connect_timeout": 5, "delay": 0, "exclude_hosts": null, "host": "10.250.0.196", "path": null, "port": 22, "search_regex": null, "state": "stopped", "timeout": 15}, "module_name": "wait_for"}, "msg": "Timeout when waiting for 10.250.0.196:22 to stop."}

Today, we try a empty JSON file, the result is fail, too.
----------------------------------------------------------------
TASK [test : Wait until the original service ACLs are reinstated and the SSH port on the DUT is open to us once again] ***
task path: /var/polly_hsu/sonic-mgmt/ansible/roles/test/tasks/service_acl.yml:58
Monday 30 April 2018  00:39:28 +0000 (0:00:30.332)       0:01:04.288 ********** 
ESTABLISH LOCAL CONNECTION FOR USER: polly_hsu
localhost EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1525048768.89-129114678869682 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1525048768.89-129114678869682 )" )
localhost PUT /tmp/tmp0HIVH3 TO /var/polly_hsu/.ansible/tmp/ansible-tmp-1525048768.89-129114678869682/wait_for
localhost EXEC LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/python /var/polly_hsu/.ansible/tmp/ansible-tmp-1525048768.89-129114678869682/wait_for; rm -rf "/var/polly_hsu/.ansible/tmp/ansible-tmp-1525048768.89-129114678869682/" > /dev/null 2>&1
fatal: [str-dut-01 -> localhost]: FAILED! => {"changed": false, "elapsed": 90, "failed": true, "invocation": {"module_args": {"connect_timeout": 5, "delay": 0, "exclude_hosts": null, "host": "10.250.0.196", "path": null, "port": 22, "search_regex": "OpenSSH", "state": "started", "timeout": 90}, "module_name": "wait_for"}, "msg": "Timeout when waiting for search string OpenSSH in 10.250.0.196:22"}

Here is the ACL information in our device.
root@str-dut-01:/home/admin# show acl table
Command: acl-loader show table
Name      Type       Ports        Description
--------  ---------  -----------  -------------
EVERFLOW  MIRROR     Ethernet0    EVERFLOW
                     Ethernet4
                     Ethernet8
                     Ethernet12
                     Ethernet16
                     Ethernet20
                     Ethernet24
                     Ethernet28
                     Ethernet32
                     Ethernet36
                     Ethernet40
                     Ethernet44
                     Ethernet48
                     Ethernet52
                     Ethernet56
                     Ethernet60
                     Ethernet64
                     Ethernet68
                     Ethernet72
                     Ethernet76
                     Ethernet80
                     Ethernet84
                     Ethernet88
                     Ethernet92
                     Ethernet96
                     Ethernet100
                     Ethernet104
                     Ethernet108
                     Ethernet112
                     Ethernet116
                     Ethernet120
                     Ethernet124
                     Ethernet128
                     Ethernet132
                     Ethernet136
                     Ethernet140
                     Ethernet144
                     Ethernet148
                     Ethernet152
                     Ethernet156
                     Ethernet160
                     Ethernet164
                     Ethernet168
                     Ethernet172
                     Ethernet176
                     Ethernet180
                     Ethernet184
                     Ethernet188
                     Ethernet192
                     Ethernet196
                     Ethernet200
                     Ethernet204
                     Ethernet208
                     Ethernet212
                     Ethernet216
                     Ethernet220
                     Ethernet224
                     Ethernet228
                     Ethernet232
                     Ethernet236
                     Ethernet240
                     Ethernet244
                     Ethernet248
                     Ethernet252
SNMP_ACL  CTRLPLANE               SNMP_ACL
DATAACL   L3         Ethernet0    DATAACL
                     Ethernet4
                     Ethernet8
                     Ethernet12
                     Ethernet16
                     Ethernet20
                     Ethernet24
                     Ethernet28
                     Ethernet32
                     Ethernet36
                     Ethernet40
                     Ethernet44
                     Ethernet48
                     Ethernet52
                     Ethernet56
                     Ethernet60
                     Ethernet64
                     Ethernet68
                     Ethernet72
                     Ethernet76
                     Ethernet80
                     Ethernet84
                     Ethernet88
                     Ethernet92
                     Ethernet96
                     Ethernet100
                     Ethernet104
                     Ethernet108
                     Ethernet112
                     Ethernet116
                     Ethernet120
                     Ethernet124
SSH_ONLY  CTRLPLANE               SSH_ONLY

root@str-dut-01:/home/admin#
root@str-dut-01:/home/admin# show acl rule
Command: acl-loader show rule
Rule ID    Rule Name     Priority    Action    Match
---------  ------------  ----------  --------  ------------------
SNMP_ACL   RULE_1        9999        ACCEPT    IP_PROTOCOL: 17
                                               SRC_IP: 1.1.1.1/32
SSH_ONLY   RULE_1        9999        ACCEPT    IP_PROTOCOL: 6
                                               SRC_IP: 1.1.1.1/32
SNMP_ACL   DEFAULT_RULE  1           DROP      ETHER_TYPE: 2048
SSH_ONLY   DEFAULT_RULE  1           DROP      ETHER_TYPE: 2048

root@str-dut-01:/home/admin#

**Comment by lvphuc133** [comment]
@akenliu 

The test passed on my setup with the following changes.
1. Create an empty JSON file for default ACL rules
echo "{}" > /etc/sonic/acl.json
2. Update the latest version of config_service_acl.sh script
https://github.com/Azure/sonic-mgmt/blob/master/ansible/roles/test/files/helpers/config_service_acls.sh
This script has increased the delay time to 60 seconds after applying the ACL rules

3. Update the latest version of service_acl playbook
https://github.com/Azure/sonic-mgmt/blob/master/ansible/roles/test/tasks/service_acl.yml
This script also have changes in the delay time to adapt with the change in the script in step 2

Hope this help.
