### ISSUE TITLE
AttributeError: 'libvirtError' object has no attribute 'message'

### ISSUE THREAD

**Issue by guodong** [Azure/sonic-mgmt#5287]
Hi,  I'm trying to start the testbed according to the the document, when I issue the following cmd in the mgmt container
```
./testbed-cli.sh -m veos_vtb -n 4 -k vsonic start-vms server_1 password.txt
```
The output shows the error:

```
TASK [vm_set : Define vm VM0100] ***********************************************
Monday 07 March 2022  16:41:40 +0000 (0:00:24.786)       0:00:48.794 ********** 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'libvirtError' object has no attribute 'message'
```
And no vms are created after the cmd, is it related the version of libvirt?

**Comment by fanxinghua** [comment]
I also meet this problem, my system is ubuntu20.04, the full trace log as following

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_virt_payload_avj8cwf9/__main__.py", line 542, in core
    domain = v.define(xml)
  File "/tmp/ansible_virt_payload_avj8cwf9/__main__.py", line 455, in define
    return self.conn.define_from_xml(xml)
  File "/tmp/ansible_virt_payload_avj8cwf9/__main__.py", line 284, in define_from_xml
    return self.conn.defineXML(xml)
  File "/usr/lib/python3/dist-packages/libvirt.py", line 4047, in defineXML
    if ret is None:raise libvirtError('virDomainDefineXML() failed', conn=self)
libvirt.libvirtError: unsupported configuration: Emulator '/usr/bin/qemu-system-x86_64' does not support virt type 'kvm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/ansible_virt_payload_avj8cwf9/__main__.py", line 593, in main
    rc, result = core(module)
  File "/tmp/ansible_virt_payload_avj8cwf9/__main__.py", line 551, in core
    module.fail_json(msg='libvirtError: %s' % e.message)
AttributeError: 'libvirtError' object has no attribute 'message'

[WARNING]: 'xml' is given - ignoring 'name'

fatal: [STR-ACS-VSERV-01]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "autostart": null, 
            "command": "define", 
            "name": "vlab-01", 
            "state": null, 
            "uri": "qemu:///system", 
            "xml": "<domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>\n  <name>vlab-01</name>\n  <memory unit='KiB'>3072000</memory>\n  <currentMemory unit='KiB'>3072000</currentMemory>\n  <vcpu placement='static'>4</vcpu>\n  <resource>\n    <partition>/machine</partition>\n  </resource>\n  <os>\n    <type arch='x86_64' machine='q35'>hvm</type>\n    <boot dev='hd'/>\n  </os>\n  <features>\n    <acpi/>\n    <apic/>\n  </features>\n  <clock offset='utc'/>\n  <on_poweroff>destroy</on_poweroff>\n  <on_reboot>restart</on_reboot>\n  <on_crash>restart</on_crash>\n  <devices>\n    <emulator>/usr/bin/qemu-system-x86_64</emulator>\n    <disk type='file' device='disk'>\n      <driver name='qemu' type='qcow2' cache='writeback'/>\n      <source file='/home/fxh/sonic-vm/disks/sonic_vlab-01.img'/>\n      <target bus='virtio' dev='vda'/>\n    </disk>\n    <serial type='tcp'>\n      <source host='127.0.0.1' mode='bind' service='9000'/>\n      <target port='0'/>\n      <protocol type='telnet'/>\n    </serial>\n    <interface type='ethernet'>\n        <target dev='vlab-01-0' />\n        <model type='e1000' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-1' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-2' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-3' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-4' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-5' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-6' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-7' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-8' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-9' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-10' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-11' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-12' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-13' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-14' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-15' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-16' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-17' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-18' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-19' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-20' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-21' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-22' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-23' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-24' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-25' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-26' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-27' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-28' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-29' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-30' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-31' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <interface type='ethernet' >\n        <target dev='vlab-01-32' />\n        <model type='e1000' />\n        <mtu size='9216' />\n    </interface>\n    <controller type='usb' index='0'/>\n    <memballoon model='virtio'>\n      <alias name='balloon0'/>\n      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0'/>\n    </memballoon>\n    <watchdog model='i6300esb'/>\n  </devices>\n  <seclabel type='dynamic' model='apparmor' relabel='yes'/>\n</domain>\n"
        }
    }, 
    "msg": "'libvirtError' object has no attribute 'message'"
}

PLAY RECAP ************************************************************************************************************************************************************************************
STR-ACS-VSERV-01           : ok=88   changed=5    unreachable=0    failed=1    skipped=78   rescued=0    ignored=1

**Comment by fanxinghua** [comment]
> Hi, I'm trying to start the testbed according to the the document, when I issue the following cmd in the mgmt container
> 
> ```
> ./testbed-cli.sh -m veos_vtb -n 4 -k vsonic start-vms server_1 password.txt
> ```
> 
> The output shows the error:
> 
> ```
> TASK [vm_set : Define vm VM0100] ***********************************************
> Monday 07 March 2022  16:41:40 +0000 (0:00:24.786)       0:00:48.794 ********** 
> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'libvirtError' object has no attribute 'message'
> ```
> 
> And no vms are created after the cmd, is it related the version of libvirt?

Did you resolve this problem ?

**Comment by guodong** [comment]
@fanxinghua, I find out the reason, I use VirtualBox on Windows, but even through I checked the nested virt on setting, the vm cannot support kvm at all, then vms inside vm cannot be setup. Then I switch to using Hyper-V, then all goes well~
