### ISSUE TITLE
[test_copp.py]test case failed for DHCP6 when running test on ptf32 topo

### ISSUE THREAD

**Issue by nhe-NV** [Azure/sonic-mgmt#5329]
**Description**

test_copp.py::test_no_policer can work run on ptf32 topo, since there is no copp_tests.DHCP6TopoT1Test , the issue is introduced by https://github.com/Azure/sonic-mgmt/pull/5253, since in this PR only DHCP6Test added, but DHCP6TopoT1Test not added.
**Steps to reproduce the issue:**
1. Run test test_copp.py::test_no_policer with ptf32 topo

**Describe the results you received:**
ERROR    tests.ptf_runner:ptf_runner.py:54 Exception caught while executing case: copp_tests.DHCP6TopoT1Test. Error message: Traceback (most recent call last):
  File "/root/mars/workspace/sonic-mgmt/tests/ptf_runner.py", line 47, in ptf_runner
    result = host.shell(cmd, chdir="/root", module_ignore_errors=module_ignore_errors)
  File "/root/mars/workspace/sonic-mgmt/tests/common/devices/base.py", line 89, in _run
    raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
RunAnsibleModuleFail: run module shell failed, Ansible Results =>
{
    "changed": true, 
    "cmd": "ptf --test-dir ptftests copp_tests.DHCP6TopoT1Test --qlen=100000 --platform nn -t 'peerip=u'\"'\"'10.0.0.30'\"'\"';verbose=False;myip=u'\"'\"'10.0.0.31'\"'\"';send_rate_limit=2000;target_port=15;has_trap=True' --device-socket 0-15@tcp://127.0.0.1:10900  --device-socket 1-15@tcp://10.210.25.10:10900", 
    "delta": "0:00:01.497647", 
    "end": "2022-03-15 04:48:18.198132", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "_raw_params": "ptf --test-dir ptftests copp_tests.DHCP6TopoT1Test --qlen=100000 --platform nn -t 'peerip=u'\"'\"'10.0.0.30'\"'\"';verbose=False;myip=u'\"'\"'10.0.0.31'\"'\"';send_rate_limit=2000;target_port=15;has_trap=True' --device-socket 0-15@tcp://127.0.0.1:10900  --device-socket 1-15@tcp://10.210.25.10:10900", 
            "_uses_shell": true, 
            "argv": null, 
            "chdir": "/root", 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "stdin_add_newline": true, 
            "strip_empty_ends": true, 
            "warn": true
        }
    }, 
    "msg": "non-zero return code", 
    "rc": 1, 
    "start": "2022-03-15 04:48:16.700485", 
    "stderr": "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.\n  from cryptography.hazmat.backends import default_backend", 
    "stderr_lines": [
        "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.", 
        "  from cryptography.hazmat.backends import default_backend"
    ], 
    "stdout": "test-spec element **copp_tests.DHCP6TopoT1Test did not match any tests**", 
    "stdout_lines": [
        "test-spec element copp_tests.DHCP6TopoT1Test did not match any tests"
    ]
}

**Describe the results you expected:**
test_copp.py::test_no_policer can run on ptf32 topo

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by vcheketx** [comment]
@kellyyeh could you please take a look at this? Issue is also reproduced on T1 topo.

**Comment by kellyyeh** [comment]
@vcheketx Added DHCP6 T1 test. Could you check if the issue is resolved?
