### ISSUE TITLE
[MASIC] [202012] [201911] ACL tests failure

### ISSUE THREAD

**Issue by wenyiz2021** [Azure/sonic-mgmt#5368]
**Description**
New ACL issues introduced in 2019 when branch updated, same issue is there in 202012 for multi-asic device:

logger.error("ACL table creation failed, attempting to clean-up...")

Failed to create ACL table with cmd ""sudo ip netns exec asic0 config acl add table DATA_INGRESS_IPV4_TEST L3 -s ingress -p ".
Issue due to portchannel not provided in this cmd for multi-asic, furthermore, when adding portchannel base on duthost and namespaces, it failed to add base on duthost for multi-asic devices.

**Steps to reproduce the issue:**
1. run acl/test_acl.py on any multi-asic device
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by wenyiz2021** [comment]
health test issued:
sudo ip netns exec asic0 config acl add table DATA_INGRESS_IPV6_TEST L3V6 -s ingress -p PortChannel105,PortChannel102"

unhealth test issued:
config acl add table DATA_INGRESS_IPV6_TEST L3V6 -s ingress -p PortChannel1022,PortChannel1023,PortChannel1011,PortChannel1010,PortChannel1013,PortChannel1012,PortChannel1015,PortChannel1014,PortChannel1017,PortChannel1016,PortChannel1019,PortChannel1018,PortChannel1024,PortChannel105,PortChannel104....

**Comment by wenyiz2021** [comment]
307 def create_or_remove_acl_table(duthost, acl_table_config, setup, op):
308     for sonic_host_or_asic_inst in duthost.get_sonic_host_and_frontend_asic_instance():

(Pdb) sonic_host_or_asic_inst 
(Pdb) <MASIC>
(Pdb) duthost.get_sonic_host_and_frontend_asic_instance()
(Pdb) [<MASIC>, <SonicAsic 0>, <SonicAsic 1>, <SonicAsic 2>, <SonicAsic 3>]

**Comment by wenyiz2021** [comment]
reverting line 80 and 96 works for manual run:
ansible/templates/minigraph_png.j2

**Comment by wenyiz2021** [comment]
acl/test_acl.py::TestBasicAcl::test_ingress_unmatched_blocked[ipv4-ingress-downlink->uplink] PASSED                                                                                      [  0%]
acl/test_acl.py::TestBasicAcl::test_ingress_unmatched_blocked[ipv4-ingress-uplink->downlink] PASSED                                                                                      [  0%]
acl/test_acl.py::TestBasicAcl::test_egress_unmatched_forwarded[ipv4-ingress-downlink->uplink] SKIPPED                                                                                    [  0%]
acl/test_acl.py::TestBasicAcl::test_egress_unmatched_forwarded[ipv4-ingress-uplink->downlink] SKIPPED                                                                                    [  0%]
.....

**Comment by selldinesh** [comment]
> reverting line 80 and 96 works for manual run: ansible/templates/minigraph_png.j2
> 
> line 80: {% if inventory_hostname not in device_conn or port_alias[loop.index - 1] in device_conn[inventory_hostname] %}
> 
> which is added for chassis, need to refine this condition before reverting it..

Hi, I am facing the same problem ,getting ACL table creation failed and at the end of execution getting Loganalyzer error.
I have removed lines 80 and 96 , regenerated the minigraph.xml using ./testbed-cli.sh gen-mg vms-sn2700-t0 lab password.txt, but i don' see any difference in the minigraph.xml.
I also tried to rerun the testcase , still was getting the same errors.

**Comment by wenyiz2021** [comment]
> > reverting line 80 and 96 works for manual run: ansible/templates/minigraph_png.j2
> > line 80: {% if inventory_hostname not in device_conn or port_alias[loop.index - 1] in device_conn[inventory_hostname] %}
> > which is added for chassis, need to refine this condition before reverting it..
> 
> Hi , I am facing the same problem ,getting ACL table creation failed and at the end of execution getting Loganalyzer error. I have removed lines 80 and 96 , regenerated the minigraph.xml using ./testbed-cli.sh gen-mg vms-sn2700-t0 lab password.txt, but i don' see any difference in the minigraph.xml. I also tried to rerun the testcase , still was getting the same errors.

Try with deloy-mg after you did the change in minigraph.ml:
./testbed-cli.sh -t testbed.csv -m veos deploy-mg vms-sn2700-t0 str password.txt

**Comment by sanmalho-git** [comment]
@wenyiz2021 - On multi-asic KVM, I can see the entries created in generated minigraph.xml between line80 and line96 in ansible/templates/minigraph_png.j2.  Could you provide the values of device-conn and port_alias for your box?

Also, if the entries are in the minigraph, then do you expect the ACL tests to pass on a multi-asic box?

**Comment by SuvarnaMeenakshi** [comment]
@sanmalho-git From PR: https://github.com/Azure/sonic-mgmt/pull/4420, I see that minigraph_png fix was added to:
For supporting not all ports connected to fanout, in minigraph_png.j2, we added DeviceInterfaceLink for only ports that are defined in the device_conn (from connection graph). But, for masic KVM, device_conn is not defined, and thus we were not adding any port. The fix is that if the inventory_hostname is not present in the device_conn, then add DeviceInterfaceLink for all front_panel_asic_ifnames
With this change, multi-asic device does not generate the front-panel interface device interface link mapping to the ASIC interface name. For example:
```
      <DeviceLinkBase i:type="DeviceInterfaceLink">
        <ElementType>DeviceInterfaceLink</ElementType>
        <Bandwidth>40000</Bandwidth>
        <ChassisInternal>true</ChassisInternal>
        <EndDevice>ASIC0</EndDevice>
        <EndPort>Eth0-ASIC0</EndPort>
        <FlowControl>true</FlowControl>
        <StartDevice>vlab-08</StartDevice>
        <StartPort>Ethernet1/1</StartPort>
        <Validate>true</Validate>
      </DeviceLinkBase>
```
If the minigraph_png is only required for chassis, can you verify this change: https://github.com/Azure/sonic-mgmt/pull/5538

**Comment by SuvarnaMeenakshi** [comment]
> @sanmalho-git From PR: #4420, I see that minigraph_png fix was added to: For supporting not all ports connected to fanout, in minigraph_png.j2, we added DeviceInterfaceLink for only ports that are defined in the device_conn (from connection graph). But, for masic KVM, device_conn is not defined, and thus we were not adding any port. The fix is that if the inventory_hostname is not present in the device_conn, then add DeviceInterfaceLink for all front_panel_asic_ifnames With this change, multi-asic device does not generate the front-panel interface device interface link mapping to the ASIC interface name. For example:
> 
> ```
>       <DeviceLinkBase i:type="DeviceInterfaceLink">
>         <ElementType>DeviceInterfaceLink</ElementType>
>         <Bandwidth>40000</Bandwidth>
>         <ChassisInternal>true</ChassisInternal>
>         <EndDevice>ASIC0</EndDevice>
>         <EndPort>Eth0-ASIC0</EndPort>
>         <FlowControl>true</FlowControl>
>         <StartDevice>vlab-08</StartDevice>
>         <StartPort>Ethernet1/1</StartPort>
>         <Validate>true</Validate>
>       </DeviceLinkBase>
> ```
> 
> If the minigraph_png is only required for chassis, can you verify this change: #5538

@sanmalho-git Please check https://github.com/Azure/sonic-mgmt/pull/5538#discussion_r855572134 and let me know if you find any issue with removing this check in template.
