### ISSUE TITLE
[ACL] Switch failed to update ACL rules with the warning DATAACL does not exist

### ISSUE THREAD

**Issue by lvphuc133** [Azure/sonic-mgmt#577]
**Description**
Switch raises the warning message "DATAACL table does not exist" when trying to update ACL rules from JSON file.

**Steps to reproduce the issue:**
1. Try to load ACL JSON file with "acl-loader" command
root@strot@str-t@str-ne10032-01:~# acl-loader update full acltb_test_rules_allow_all.json
Warning: DATAACL table does not exist

root@str-ne10032-01:~# acl-loader update full /tmp/acltb_test_rules.json
Warning: DATAACL table does not exist

2. Verify the ACL rule and table and they are all empty
admin@str-ne10032-01:~$ show acl  rule <<<< **EMPTY**
Command: acl-loader show rule  
Rule ID    Rule Name    Priority    Action    Match
---------  -----------  ----------  --------  -------
admin@str-ne10032-01:~$ show acl  rule table <<<< **EMPTY**
Command: acl-loader show rule table 
Rule ID    Rule Name    Priority    Action    Match
---------  -----------  ----------  --------  -------
admin@str-ne10032-01:~$ 

The ACL rule file is:

root@str-ne10032-01:~# cat /tmp/acltb_test_rules_allow_all.json
{
    "acl": {
        "acl-sets": {
            "acl-set": {
                "dataacl": {
                    "acl-entries": {
                        "acl-entry": {
                            "1": {
                                "actions": {
                                    "config": {
                                        "forwarding-action": "ACCEPT"
                                    }
                                },
                                "config": {
                                    "sequence-id": 1
                                },
                                "l2": {
                                    "config": {
                                        "ethertype": "2048"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

**Describe the results you received:**
Look like no ACL rules are applied to the switch during ACL test so PTF tests failed for most of the cases

**Describe the results you expected:**
Can anybody tell me wht DATAACL table does not exist? How to create it for the test?

**Comment by prsunny** [comment]
Can you check if DATAACL binding is present in your minigraph?. If not, you can add and check the same.. 
 ```
<AclInterface>    
<AttachTo>Ethernet32/1;Ethernet27/1;Ethernet26/1;Ethernet11/1;Ethernet12/1;Ethernet9/1;Ethernet10/1;Ethernet25/1;Ethernet22/1;Ethernet24/1;Ethernet23/1;Ethernet7/1;Ethernet8/1;Ethernet1/1;Ethernet2/1;Ethernet17/1;Ethernet5/1;Ethernet6/1;Ethernet21/1;Ethernet18/1;Ethernet19/1;Ethernet3/1;Ethernet4/1;Ethernet20/1;Ethernet31/1;Ethernet15/1;Ethernet16/1;Ethernet30/1;Ethernet28/1;Ethernet13/1;Ethernet14/1;Ethernet29/1</AttachTo>
          <InAcl>DataAcl</InAcl>
          <Type>DataPlane</Type>
        </AclInterface>
```

**Comment by lvphuc133** [comment]
The script passed with this change in the minigraph. I check the template at https://github.com/Azure/sonic-mgmt/blob/master/ansible/templates/minigraph_dpg.j2 and found that it has the logic to generate this DataAcl. Look like I have the old version of the template. I will update it.

Thank you for your help.
