### ISSUE TITLE
[CRM] Verification step in test script crm_test_fdb_entry may be not correct

### ISSUE THREAD

**Issue by lvphuc133** [Azure/sonic-mgmt#586]
**Description**
The logic in verification step after removing FDB entries is not correct for me.

This is the steps in the test plan:
1. Set polling interval to 1 minute. <<< Set to 1 second in the script
2. Configure 1 FDB entry and observe that counters were updated as expected.
3. Remove 1 FDB entry and observe that counters were updated as expected.
4. Perform the following steps for all threshold types ("percentage", "used", "free"):
5. Set low and high thresholds according to current usage and type.
6. Verify that "EXCEEDED" message is logged (using log analyzer).
7. Set low and high thresholds to default values.
8. Verify that "CLEAR" message is logged (using log analyzer).
9. Restore default configuration.

**Describe the results you received:**
At line 72 in the script at roles/test/tasks/crm/crm_test_fdb_entry.yml

    - name: Verify "crm_stats_fdb_entry_used" counter was decremented
      assert: {that: "{{new_crm_stats_fdb_entry_used|int - crm_stats_fdb_entry_used|int == 0}}"}
Test failed at this assertion 

**Describe the results you expected:**
The value of "new_crm_stats_fdb_entry_used" is 0 which is correct because all FDB entries are removed.
The value of "crm_stats_fdb_entry_used" is 1 which is from the steps before removing FDB entries.
Base on this, the assert above may be not correct. It should be -1 or just
 assert: {that: "{{new_crm_stats_fdb_entry_used|int  == 0}}"}

Can someone please confirm if this is a script issue?

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by prsunny** [comment]
We are providing a fix for this issue.
