### ISSUE TITLE
How upload docker-ptf to the docker registry.

### ISSUE THREAD

**Issue by agzchu** [Azure/sonic-mgmt#604]
Hi All,

I've setup docker registry,but  I don't know how upload docker-ptf to the docker registry.
Which image is docker-ptf?
Could you provide complete steps to help me upload the images to docker registry.

Thank you

**Comment by lvphuc133** [comment]
Here are the steps:
1. Download sonic-mgmt source
git clone --recursive https://github.com/Azure/sonic-buildimage.git

2. Build PTF image
make configure PLATFORM=generic
make -j8 target/docker-ptf.gz

3. Load PTF image to docker images:
# docker load -i target/docker-ptf.gz
	
4. Create local private docker registry
# sudo docker run -d -p 5000:5000 registry
	
5. View docker images 
# sudo docker images
=> Find the Image ID of the docker-ptf.gz image
	
6. Create a tag for ptf image to upload it to the registry
# sudo docker tag <ptf ImageId> 127.0.0.1:5000/docker-ptf:1
	
7. Push (upload) ptf image to the registry
# sudo docker push 127.0.0.1:5000/docker-ptf:1

After this step you have the docker-ptf:1 image hosted on your local private registry at http://127.0.0.1:5000/docker-ptf:1

**Comment by agzchu** [comment]
Thank you for your helpful information.

**Comment by li7hui** [comment]
very helpful
