### ISSUE TITLE
vm_set : Install necessary packages fail

### ISSUE THREAD

**Issue by agzchu** [Azure/sonic-mgmt#608]
**Description**
after run : test@f908975614c0:~/sonic-mgmt/ansible$ ./testbed-cli.sh start-vms server_1 password.txt
receved the following Error :

    Starting VMs on server 'server_1'
    
    PLAY ***************************************************************************
    
    TASK [vm_set : get host distribution] ******************************************
    Friday 11 May 2018  03:01:08 +0000 (0:00:00.054)       0:00:00.054 ************
    changed: [STR-ACS-SERV-01]
    
    TASK [vm_set : get host distribution version] **********************************
    Friday 11 May 2018  03:01:08 +0000 (0:00:00.417)       0:00:00.471 ************
    changed: [STR-ACS-SERV-01]
    
    TASK [vm_set : get host kernel version] ****************************************
    Friday 11 May 2018  03:01:08 +0000 (0:00:00.143)       0:00:00.615 ************
    changed: [STR-ACS-SERV-01]
    
    TASK [vm_set : Check if kernel upgrade needed] *********************************
    Friday 11 May 2018  03:01:08 +0000 (0:00:00.140)       0:00:00.755 ************
    skipping: [STR-ACS-SERV-01]
    
    TASK [vm_set : debug] **********************************************************
    Friday 11 May 2018  03:01:08 +0000 (0:00:00.065)       0:00:00.820 ************
    skipping: [STR-ACS-SERV-01]
    
    TASK [vm_set : Upgrade kernel package] *****************************************
    Friday 11 May 2018  03:01:08 +0000 (0:00:00.059)       0:00:00.880 ************
    skipping: [STR-ACS-SERV-01] => (item=[])
    
    TASK [vm_set : Prompt for rebooting] *******************************************
    Friday 11 May 2018  03:01:08 +0000 (0:00:00.073)       0:00:00.953 ************
    skipping: [STR-ACS-SERV-01]
    
    TASK [vm_set : Add docker repository for 17.04] ********************************
    Friday 11 May 2018  03:01:09 +0000 (0:00:00.058)       0:00:01.011 ************
    skipping: [STR-ACS-SERV-01]
    
    TASK [vm_set : Add docker repository for 16.04] ********************************
    Friday 11 May 2018  03:01:09 +0000 (0:00:00.059)       0:00:01.071 ************
    skipping: [STR-ACS-SERV-01]
    
    TASK [vm_set : Install necessary packages] *************************************
    Friday 11 May 2018  03:01:09 +0000 (0:00:00.069)       0:00:01.141 ************
    failed: [STR-ACS-SERV-01] => (item=[u'qemu', u'openvswitch-switch', u'net-tools', u'bridge-utils', 
    u'util-linux', u'iproute2', u'vlan', u'libvirt-bin', u'python-libvirt', u'python-pip', u'apt-transport-https', 
    u'ca-certificates', u'curl', u'software-properties-common', u'docker-ce']) => {"failed": true, "item": 
    ["qemu", "openvswitch-switch", "net-tools", "bridge-utils", "util-linux", "iproute2", "vlan", "libvirt-bin", 
    "python-libvirt", "python-pip", "apt-transport-https", "ca-certificates", "curl", "software-properties- 
    common", "docker-ce"], "msg": "No package matching 'docker-ce' is available"}
    
    PLAY RECAP *********************************************************************
    STR-ACS-SERV-01            : ok=3    changed=3    unreachable=0    failed=1

**Comment by pavel-shirshov** [comment]
You need to install docker repository for the docker-ce

Check the instruction here
https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-repository

**Comment by agzchu** [comment]
Thanks,it works for me.
