### ISSUE TITLE
[BGP] bgp_gr_helper.yml does not exist in sonic-mgmt question

### ISSUE THREAD

**Issue by mooncat2** [Azure/sonic-mgmt#648]
There is a bgp_gr_helper test in testcases.yml:

bgp_gr_helper:
filename: bgp_gr_helper.yml
topologies: [t1, t1-lag]

Try to run the bgp_gr_helper test using the following CLI in my testbed:

ansible-playbook -vvv -i lab -l sonic test_sonic.yml -e testbed_name=vms-t1 -e testcase_name=bgp_gr_helper

But got error log like following:

TASK [test : run test case bgp_gr_helper.yml file] *****************************
task path: /var/sonic/sonic-mgmt/ansible/roles/test/tasks/test_sonic_by_testname.yml:35
Friday 22 June 2018  01:34:19 +0000 (0:00:00.062)       0:03:33.078 *********** 
fatal: [sonic]: FAILED! => {"failed": true, "reason": "ERROR! the file_name '/var/sonic/sonic-mgmt/ansible/bgp_gr_helper.yml' does not exist, or is not readable"}

Also I cannot find any yml file named "gp_gr_helper.yml" in folder /var/sonic/sonic-mgmt/ansible/, does anyone face this issue before?

**Comment by qiluo-msft** [comment]
Related to https://github.com/Azure/sonic-mgmt/pull/583
We are checking.

**Comment by mykolaf** [comment]
This testcase is not public and was added to testcases.yml by mistake. Don't try to run it.
