### ISSUE TITLE
[Ansible Testbed Setup] Fail on build sonic-mgmt docker

### ISSUE THREAD

**Issue by weijeng** [Azure/sonic-mgmt#651]
**Description**
Follow the README, there is a fail when build sonic-mgmt docker
https://github.com/Azure/sonic-mgmt/blob/master/ansible/doc/README.testbed.Setup.md

**Ubuntu version**
user@ubuntu-1604:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"

**Steps to reproduce the issue:**
1. git clone --recursive https://github.com/Azure/sonic-buildimage.git
2. make configure PLATFORM=generic
3. make target/docker-sonic-mgmt.gz
Log file: https://www.dropbox.com/s/hwmmegzqji1bdva/docker-sonic-mgmt.gz.log?dl=0

**Describe the results you received:**
Found existing installation: pycparser 2.14
Cannot uninstall 'pycparser'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Describe the results you expected:**

**Additional information you deem important:**

**Comment by qiluo-msft** [comment]
Thanks reporting! We are checking.

**Comment by weijeng** [comment]
Successfully built docker-sonic-mgmt.gz
Thanks a lot~
