### ISSUE TITLE
make configure PLATFORM=generic Error

### ISSUE THREAD

**Issue by li7hui** [Azure/sonic-mgmt#671]
Hello,
I was building the sonic image according to the wiki:
https://github.com/Azure/sonic-mgmt/blob/master/ansible/doc/README.testbed.Setup.md
however, I got the following error when building the sonic image. please help.
![error](https://user-images.githubusercontent.com/1718938/43524067-d2e24f82-95d0-11e8-9508-4da3d110014f.png)

**Comment by li7hui** [comment]
they have similar issue about the root user for repo2docker, i follow their method, and solve the problem. 
https://github.com/jupyter/repo2docker/issues/267

**Comment by lguohan** [comment]
thanks for reporting.  explicitly print error for root user.

https://github.com/Azure/sonic-buildimage/pull/1923
