### ISSUE TITLE
[error] ansible -vvv -m ping -i veos vm_host_1 

### ISSUE THREAD

**Issue by li7hui** [Azure/sonic-mgmt#680]
Hello,
i was setting up the testbed environment by: 
https://github.com/Azure/sonic-mgmt/blob/master/ansible/doc/README.testbed.Setup.md

there were an error when using ansible ping vm_host_1, the error message is bellow:
![error](https://user-images.githubusercontent.com/1718938/44143015-ab3a9e32-a0b4-11e8-8814-197790b30faa.png)

**The configurations:**
the content of ansible/veos:
![veos](https://user-images.githubusercontent.com/1718938/44143114-fcafd96c-a0b4-11e8-9b25-84bcfa63d23b.png)
the content of  ansible/group_vars/vm_host/creds.yml.
![creds](https://user-images.githubusercontent.com/1718938/44143195-4b1c3d84-a0b5-11e8-9299-22cba4337292.png)
the content of  ansible/host_vars/STR-ACS-SERV-01.yml.
![serv01](https://user-images.githubusercontent.com/1718938/44143243-8cf92f28-a0b5-11e8-9221-8135575069ca.png)

**Comment by qiluo-msft** [comment]
We feel difficult to repro this issue. May I ask whether you build the mgmt docker manually, or download from https://sonic-jenkins.westus2.cloudapp.azure.com/job/bldenv/job/docker-sonic-mgmt/?

If not downloading, could you try?

**Comment by li7hui** [comment]
@qiluo-msft 
i once tried to built it myself, but failed, so i downloaded it from 
https://sonic-jenkins.westus2.cloudapp.azure.com/job/bldenv/job/docker-sonic-mgmt/

**Comment by qiluo-msft** [comment]
I just tried https://sonic-jenkins.westus2.cloudapp.azure.com/job/bldenv/job/docker-sonic-mgmt/lastSuccessfulBuild/artifact/target/docker-sonic-mgmt.gz and it is working.

I suspect there is something missing on your server vm_host_1. Maybe python2.
You could try below command, and find the remote temp script and debug it on the server vm_host_1. We don't have access to your server, so you are wild and need some investigation yourself.
```
ANSIBLE_KEEP_REMOTE_FILES=1 ansible -vvv -m ping -i veos vm_host_1
```

**Comment by li7hui** [comment]
the pytho2 is the problem. thanks.
