### ISSUE TITLE
[copp] The calculation of rx_pps doesn't consider the factor of CBS

### ISSUE THREAD

**Issue by chiuhsiapeng** [Azure/sonic-mgmt#685]
**Description**

We always failed the ARP,SNMP,SSH and IP2ME tests. The statistics are always greater than 660. 
After analyzing the ARP receiving rate, I think if taking the CBS (600 packets) into consideration, it is reasonable why the average is always greater than 660.

1. In Figure 1, almost all the receiving rates are around 600, except the first second, 1180 packets are received in the first second. 
Figure 1:
![rate_1](https://user-images.githubusercontent.com/41297495/44373853-f9e57800-a51d-11e8-8e12-469736b94b7d.PNG)

2. In Figure 2, view the receiving rate by per 0.1 second in the first second.
Figure 2:
![rate_2](https://user-images.githubusercontent.com/41297495/44373894-26998f80-a51e-11e8-88d5-3905b560ea33.PNG)

3. In this case 460 and 259 packets are received in the 1st and 2nd 0.1 second, they increase the **rx_pps** up to 86.41957 ((460+259)-600*0.2)/6.9313, 6.9313 is the **Test time**.

4. As CBS is up to 600 packets, I think the value of 460 and 259 packets at the beginning moment are still comply the configuration.

5. Since these tests (ARP, SNMP, SSH, and IP2ME) usually take less than 7 seconds, the CBS 600 makes a significant deviation on **rx_pps**.

    **Output of `show version`:**

   
```
    SONiC Software Version: SONiC.master.0-e3abf0c
Distribution: Debian 8.11
Kernel: 3.16.0-5-amd64
Build commit: e3abf0c
Build date: Thu Jul 26 06:47:44 UTC 2018
Built by: chihpei@BSP-ONL-ubuntu-14.04-Server

Docker images:
REPOSITORY                 TAG                 IMAGE ID            SIZE
docker-syncd-brcm-rpc      latest              907cfcf3a7d9        598.9 MB
docker-syncd-brcm          latest              907cfcf3a7d9        598.9 MB
docker-syncd-brcm          master.0-e3abf0c    df46fbb08fa4        332.6 MB
docker-orchagent-brcm      latest              d4589a4f177e        253.5 MB
docker-orchagent-brcm      master.0-e3abf0c    d4589a4f177e        253.5 MB
docker-lldp-sv2            latest              50ad3f656a95        266.4 MB
docker-lldp-sv2            master.0-e3abf0c    50ad3f656a95        266.4 MB
docker-dhcp-relay          latest              a62eb61c0872        249.8 MB
docker-dhcp-relay          master.0-e3abf0c    a62eb61c0872        249.8 MB
docker-database            latest              269ba5788688        248.5 MB
docker-database            master.0-e3abf0c    269ba5788688        248.5 MB
docker-snmp-sv2            latest              4fcd28fd521f        287.3 MB
docker-snmp-sv2            master.0-e3abf0c    4fcd28fd521f        287.3 MB
docker-teamd               latest              c6f226e6477c        253.2 MB
docker-teamd               master.0-e3abf0c    c6f226e6477c        253.2 MB
docker-router-advertiser   latest              948f76e461b7        246.1 MB
docker-router-advertiser   master.0-e3abf0c    948f76e461b7        246.1 MB
docker-platform-monitor    latest              8524e5192dd8        277.3 MB
docker-platform-monitor    master.0-e3abf0c    8524e5192dd8        277.3 MB
docker-fpm-quagga          latest              bc8e3ab44825        260.1 MB
docker-fpm-quagga          master.0-e3abf0c    bc8e3ab44825        260.1 MB

```

**Comment by qiluo-msft** [comment]
Could you refine the words in title? What is 'he'?

**Comment by pavel-shirshov** [comment]
Can you please elaborate? Please show wrong output and explain why you think the output is wrong?

**Comment by chiuhsiapeng** [comment]
I already updated it.

Sorry for the inconvenience.

Sincerely,
Jane#

**Comment by chiuhsiapeng** [comment]
I already updated it.

Sorry for the inconvenience.

Sincerely,
Jane#

**Comment by chiuhsiapeng** [comment]
Cbs (Committed burst size) is the COPP configuration in Docker swss: /etc/swss/config.d/00-copp.config.json

According to sonic-sai-common-utils/inc/sai_qos_common.h, the unit of cbs should be based on meter type, the default is "packets"
/** Committed burst size in packets/bytes based on meter type*/
    uint64_t                   cbs;


FYI:
The following page provides good information on te related parameters:
http://support.huawei.com/enterprise/docinforeader!loadDocument1.action?contentId=DOC1000069536&partNo=10072

**Comment by paulnice** [comment]
As I understand you want us to skip the traffic measurements for first two seconds?

**Comment by chiuhsiapeng** [comment]
I think it is enough to skip the first second.

**Comment by chiuhsiapeng** [comment]
Hi,
It is difficult for me to skip the received packets in the last second. 
Is it acceptable only skip the first second?

**Comment by chiuhsiapeng** [comment]
Hi
I have made a PR #696.
This modification is based on your suggestion - skip the first second, although my first thought was just (**total_rcv_pkt_cnt** - 600) to rule out the CBS factor.
