### ISSUE TITLE
fib.yml doesn't exist in sonic-mgmt

### ISSUE THREAD

**Issue by RAJUAEC** [Azure/sonic-mgmt#770]
I am trying to run BGP_fact test cases using the following CLI in my testbed.

ansible-playbook test_sonic.yml -i inventory --limit sonic -e "testbed_type=t0" --become --tags BGP_fact --extra-vars "ptf_host=docker-ptf" -vvvv

But getting an error like given below:-
================================================
Saturday 12 January 2019  17:41:19 +0000 (0:00:00.098)       0:01:05.922 ******

TASK [test : Fib test] *********************************************************
task path: /var/azure/sonic-mgmt/ansible/roles/test/tasks/test_sonic_by_tag.yml:109
Saturday 12 January 2019  17:41:19 +0000 (0:00:00.085)       0:01:06.007 ******
fatal: [switch1]: FAILED! => {"failed": true, "reason": "ERROR! the file_name '/var/azure/sonic-mgmt/ansible/fib.yml' does not exist, or is not readable"}
================================================

and I cannot find any yml file with name fib.yml in '/var/azure/sonic-mgmt/ansible' folder.

**Comment by stcheng** [comment]
Are you running the latest version of the code? There's no fib.yml file in the repository and BGP_facts test case does not require running FIB test.

**Comment by RAJUAEC** [comment]
Issue not seen when updated the code. That's why closing this issue.
