### ISSUE TITLE
Failed to deploy minigraph on virtual switch setup

### ISSUE THREAD

**Issue by AfraMariyam** [Azure/sonic-mgmt#807]
We are trying to set up virtual switch based testbed setup by following this link:
**https://github.com/Azure/sonic-mgmt/blob/201811/ansible/doc/README.testbed.VsSetup.md**

While deploying minigraph on the DUT by running this command:
**./testbed-cli.sh -t vtestbed.csv -m veos.vtb deploy-mg vms-kvm-t0 lab password.tx**t

we are getting an error:
**TASK [find interface name mapping and individual interface speed if defined] *** Monday 11 February 2019 11:49:03 +0000 (0:00:00.421) 0:00:01.965 ******* fatal: [vlab-01]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}**

Do we have to add any ssh credentials in any other files?

**Comment by AfraMariyam** [comment]
We are trying to set up virtual switch based testbed setup by following this link:
 **https://github.com/Azure/sonic-mgmt/blob/201811/ansible/doc/README.testbed.VsSetup.md**

While deploying minigraph on the DUT by running this command:
**./testbed-cli.sh -t vtestbed.csv -m veos.vtb deploy-mg vms-kvm-t0 lab password.tx**t

we are getting an error:
**TASK [find interface name mapping and individual interface speed if defined] ***
Monday 11 February 2019  11:49:03 +0000 (0:00:00.421)       0:00:01.965 *******
fatal: [vlab-01]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}**

Do we have to add any ssh credentials in any other files?

**Comment by jipanyang** [comment]
Got the same error.  did you try " ansible -vvvv  -m ping -i veos.vtb  server_1"?  Don't remember seeing the error a few weeks ago. Other than these ping errors,  topo deployment looks ok.

**Comment by AfraMariyam** [comment]
Thank u ..When we set the proxies,it worked

**Comment by AfraMariyam** [comment]
If you are working behind a proxy,You have to set the proxies in env.yml file.It worked for us.

**Comment by nitin3685** [comment]
@AfraMariyam Thank you for replying. Since i am new to the area I have a rather silly question.
All the KVM are on the same host including the Sonic VM, why do we need to configure proxy?
Does the sonic vm need to download packages from the internet?

**Comment by AfraMariyam** [comment]
I am not sure of this .
