### ISSUE TITLE
Unable to start the VMs (vEOS and Sonic)

### ISSUE THREAD

**Issue by pkmarimuthu** [Azure/sonic-mgmt#851]
I am following the steps in below links:
https://github.com/Azure/sonic-mgmt/blob/master/ansible/doc/README.testbed.VsSetup.md) 

I am getting two erros:

Error#1:
johnar@c26723629fab:~/sonic-mgmt/ansible$ ./testbed-cli.sh -m veos.vtb start-vms server_1 password.txt
Starting VMs on server 'server_1'

PLAY ***************************************************************************

TASK [vm_set : get host distribution] ******************************************
Monday 01 April 2019  17:23:08 +0000 (0:00:00.085)       0:00:00.085 ********** 
ok: [STR-ACS-VSERV-01]

TASK [vm_set : get host distribution version] **********************************
Monday 01 April 2019  17:23:08 +0000 (0:00:00.495)       0:00:00.581 ********** 
ok: [STR-ACS-VSERV-01]

TASK [vm_set : get host kernel version] ****************************************
Monday 01 April 2019  17:23:09 +0000 (0:00:00.458)       0:00:01.040 ********** 
ok: [STR-ACS-VSERV-01]

TASK [vm_set : Check if kernel upgrade needed] *********************************
Monday 01 April 2019  17:23:09 +0000 (0:00:00.514)       0:00:01.554 ********** 
skipping: [STR-ACS-VSERV-01]

TASK [vm_set : debug] **********************************************************
Monday 01 April 2019  17:23:09 +0000 (0:00:00.161)       0:00:01.716 ********** 
skipping: [STR-ACS-VSERV-01]

TASK [vm_set : Upgrade kernel package] *****************************************
Monday 01 April 2019  17:23:10 +0000 (0:00:00.187)       0:00:01.903 ********** 
skipping: [STR-ACS-VSERV-01] => (item=[]) 

TASK [vm_set : Prompt for rebooting] *******************************************
Monday 01 April 2019  17:23:10 +0000 (0:00:00.195)       0:00:02.099 ********** 
skipping: [STR-ACS-VSERV-01]

TASK [vm_set : Install necessary packages] *************************************
Monday 01 April 2019  17:23:10 +0000 (0:00:00.191)       0:00:02.291 ********** 
failed: [STR-ACS-VSERV-01] => (item=[u'qemu', u'openvswitch-switch', u'net-tools', u'bridge-utils', u'util-linux', u'iproute2', u'vlan', u'libvirt-bin', u'python-libvirt', u'python-pip', u'apt-transport-https', u'ca-certificates', u'curl', u'software-properties-common']) => {"cmd": "apt-get update '&&' apt-get install python-apt -y -q --force-yes", "failed": true, "item": ["qemu", "openvswitch-switch", "net-tools", "bridge-utils", "util-linux", "iproute2", "vlan", "libvirt-bin", "python-libvirt", "python-pip", "apt-transport-https", "ca-certificates", "curl", "software-properties-common"], "msg": "W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Temporary failure resolving 'archive.ubuntu.com'\nW: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'\nW: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'\nW: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-security/InRelease  Temporary failure resolving 'archive.ubuntu.com'\nW: Failed to fetch https://download.docker.com/linux/ubuntu/dists/bionic/InRelease  Temporary failure resolving 'download.docker.com'\nW: Some index files failed to download. They have been ignored, or old ones used instead.\nW: --force-yes is deprecated, use one of the options starting with --allow instead.\nE: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/p/python-apt/python-apt_1.6.3ubuntu1_amd64.deb  Temporary failure resolving 'archive.ubuntu.com'\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?", "rc": 100, "stderr": "W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Temporary failure resolving 'archive.ubuntu.com'\nW: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'\nW: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'\nW: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-security/InRelease  Temporary failure resolving 'archive.ubuntu.com'\nW: Failed to fetch https://download.docker.com/linux/ubuntu/dists/bionic/InRelease  Temporary failure resolving 'download.docker.com'\nW: Some index files failed to download. They have been ignored, or old ones used instead.\nW: --force-yes is deprecated, use one of the options starting with --allow instead.\nE: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/p/python-apt/python-apt_1.6.3ubuntu1_amd64.deb  Temporary failure resolving 'archive.ubuntu.com'\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "stdout": "Err:1 https://download.docker.com/linux/ubuntu bionic InRelease\n  Temporary failure resolving 'download.docker.com'\nErr:2 http://archive.ubuntu.com/ubuntu bionic InRelease\n  Temporary failure resolving 'archive.ubuntu.com'\nErr:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease\n  Temporary failure resolving 'archive.ubuntu.com'\nErr:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease\n  Temporary failure resolving 'archive.ubuntu.com'\nErr:5 http://archive.ubuntu.com/ubuntu bionic-security InRelease\n  Temporary failure resolving 'archive.ubuntu.com'\nReading package lists...\nReading package lists...\nBuilding dependency tree...\nReading state information...\nSuggested packages:\n  python-apt-dbg python-apt-doc\nThe following NEW packages will be installed:\n  python-apt\n0 upgraded, 1 newly installed, 0 to remove and 62 not upgraded.\nNeed to get 149 kB of archives.\nAfter this operation, 682 kB of additional disk space will be used.\nErr:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 python-apt amd64 1.6.3ubuntu1\n  Temporary failure resolving 'archive.ubuntu.com'\n", "stdout_lines": ["Err:1 https://download.docker.com/linux/ubuntu bionic InRelease", "  Temporary failure resolving 'download.docker.com'", "Err:2 http://archive.ubuntu.com/ubuntu bionic InRelease", "  Temporary failure resolving 'archive.ubuntu.com'", "Err:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease", "  Temporary failure resolving 'archive.ubuntu.com'", "Err:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease", "  Temporary failure resolving 'archive.ubuntu.com'", "Err:5 http://archive.ubuntu.com/ubuntu bionic-security InRelease", "  Temporary failure resolving 'archive.ubuntu.com'", "Reading package lists...", "Reading package lists...", "Building dependency tree...", "Reading state information...", "Suggested packages:", "  python-apt-dbg python-apt-doc", "The following NEW packages will be installed:", "  python-apt", "0 upgraded, 1 newly installed, 0 to remove and 62 not upgraded.", "Need to get 149 kB of archives.", "After this operation, 682 kB of additional disk space will be used.", "Err:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 python-apt amd64 1.6.3ubuntu1", "  Temporary failure resolving 'archive.ubuntu.com'"]}

PLAY RECAP *********************************************************************
STR-ACS-VSERV-01           : ok=3    changed=0    unreachable=0    failed=1   

Monday 01 April 2019  17:25:56 +0000 (0:02:45.911)       0:02:48.202 ********** 
=============================================================================== 
TASK: vm_set : Install necessary packages ----------------------------- 165.91s
TASK: vm_set : get host kernel version ---------------------------------- 0.51s
TASK: vm_set : get host distribution ------------------------------------ 0.50s
TASK: vm_set : get host distribution version ---------------------------- 0.46s
TASK: vm_set : Upgrade kernel package ----------------------------------- 0.19s
TASK: vm_set : Prompt for rebooting ------------------------------------- 0.19s
TASK: vm_set : debug ---------------------------------------------------- 0.19s
TASK: vm_set : Check if kernel upgrade needed --------------------------- 0.16s
johnar@c26723629fab:~/sonic-mgmt/ansible$

Error#2:
johnar@c26723629fab:~/sonic-mgmt/ansible$ ansible -m ping -i veos.vtb server_1 -u root -k             
SSH password: 
STR-ACS-VSERV-01 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
VM0100 | UNREACHABLE! => {
    "changed": false, 
    "msg": "ERROR! SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", 
    "unreachable": true
}
VM0101 | UNREACHABLE! => {
    "changed": false, 
    "msg": "ERROR! SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", 
    "unreachable": true
}
VM0103 | UNREACHABLE! => {
    "changed": false, 
    "msg": "ERROR! SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", 
    "unreachable": true
}
VM0102 | UNREACHABLE! => {
    "changed": false, 
    "msg": "ERROR! SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", 
    "unreachable": true
}
johnar@c26723629fab:~/sonic-mgmt/ansible$

I am using Ubuntu 18.04 TLS VM machine. It has internet and DNS info updated. I am able to download all other packages. Only issue with ansible playbook downloading packages to setup VMs.

Based on other tickers, i tried updated creds for eos
/sonic-mgmt/ansible/group_vars/eos
ansible_user: root
ansible_password: 123456
ansible_sudo_pass: 123456

/sonic-mgmt/ansible/group_vars/vm_host
ansible_user: user
ansible_password: password
ansible_sudo_pass: password

**Comment by pkmarimuthu** [comment]
Closed as started to work after dns server from resolv.conf

**Comment by li7hui** [comment]
@pkmarimuthu 
Hi, i have the same issue as you have. Could you tell me specific detail of "stared to work after dns server from resolv.conf"?
