### ISSUE TITLE
[iface_mode]: Missing become in add_user.yml and iface_naming_mode_tests.yml

### ISSUE THREAD

**Issue by riverhong** [Azure/sonic-mgmt#938]
**Description**
When running the iface_mode test, I got permission denied error.
It seems "become: yes" is missing in add_user.yml and iface_naming_mode_tests.yml.
After adding "become: yes" in these two files as following, the test can be pass.

add_user.yml:
- name: create user 
  user:
    name: "{{uname1}}"
    groups: sudo
    state: present
    shell: /bin/bash
  become: yes

iface_naming_mode_tests.yml:
  - name: Remove the user
    user:
      name: "{{uname1}}"
      groups: sudo
      state: absent
      shell: /bin/bash
      remove: yes
    become: yes

**Comment by stcheng** [comment]
could you generate a pull request to resolve this issue?

**Comment by riverhong** [comment]
Yes, no problem.
The PR is:
https://github.com/Azure/sonic-mgmt/pull/944
