### ISSUE TITLE
[CRM] upon applying acl.json , crm stats for available counter is reduced by 6 , while  used count is 2

### ISSUE THREAD

**Issue by chitra-raghavan** [Azure/sonic-mgmt#971]
**Description**

In broadcom platforms (Z9100) While  running [crm_test_acl_counter.yml](https://github.com/Azure/sonic-mgmt/blob/master/ansible/roles/test/tasks/crm/crm_test_acl_counter.yml) ,  upon applying [acl.json](https://github.com/Azure/sonic-mgmt/blob/master/ansible/roles/test/tasks/crm/acl.json) , the counter , "crm_stats_acl_counter_available" is decremented by value 6, but "crm_stats_acl_counter_used"  just 2 and hence the testcase fails 
is  this expected  in broadcom platforms  ? 

**Before applying acl**
```
127.0.0.1:6379[2]> hgetall "CRM:ACL_TABLE_STATS:0x7000000000a3e"
1) "crm_stats_acl_counter_used"
2) "0"
3) "crm_stats_acl_entry_used"
4) "0"
5) "crm_stats_acl_counter_available"
6) "30208"
7) "crm_stats_acl_entry_available"
8) "512"
```

**After applying acl :** 

```
root@sonic-z9100-02:~# acl-loader update full acl.json

127.0.0.1:6379[2]> hgetall "CRM:ACL_TABLE_STATS:0x7000000000a3e"
1) "crm_stats_acl_counter_used"
2) "2"  << used counter is incremented by 2 
3) "crm_stats_acl_entry_used"
4) "2"
5) "crm_stats_acl_counter_available"
6) "30202"    <<<<<<<<<<<< 6 values are decremented in available counter
7) "crm_stats_acl_entry_available"
8) "510"
```

**After deleting the acl**

root@sonic-z9100-02:~#  acl-loader delete

```
127.0.0.1:6379[2]> hgetall "CRM:ACL_TABLE_STATS:0x7000000000a3e"
1) "crm_stats_acl_counter_used"
2) "0"
3) "crm_stats_acl_entry_used"
4) "0"
5) "crm_stats_acl_counter_available"
6) "30208"
7) "crm_stats_acl_entry_available"
8) "512"

```

**Steps to reproduce the issue:**
1. apply acl
2. check the crm acl counters , available vs used

**Comment by iris00522** [comment]
I can duplicate the issue on broadcom platforms, too.
I dump some data with command "fp show" for your reference.


before load the acl.jason file
----------------------------------------------------------------------------------------------------------
drivshell>fp show
fp show


FP: Range ID=1, flag=0x1, min=34048, max=35072, hw_index=0(0), style=BCM56504

FP:	unit 0:

PIPELINE STAGE INGRESS

FP:	      :tcam_sz=6144(0x1800), tcam_slices=12, tcam_ext_numb=0,

PIPELINE STAGE EGRESS

FP:	      :tcam_sz=1024(0x400), tcam_slices=4, tcam_ext_numb=0,

PIPELINE STAGE LOOKUP

FP:	      :tcam_sz=1024(0x400), tcam_slices=4, tcam_ext_numb=0,

GID          6: gid=0x6, instance=0 mode=Double, stage=Ingress lookup=Enabled, ActionResId={-1}, pbmp={0x0000000000000000000000000000000444444441111111104444444422222223}

         qset={SrcIp, DstIp, InPorts, RangeCheck, L4SrcPort, L4DstPort, EtherType, IpProtocol, TcpControl, IpType, Stage, StageIngress, IcmpTypeCode},

         Qualifiers in Part-0: {SrcIp->InPorts->RangeCheck->L4SrcPort->EtherType->IpType->IcmpTypeCode},

         Qualifiers in Part-1: {DstIp->RangeCheck->L4DstPort->IpProtocol->TcpControl->IpType},



         group_priority= 100

         slice_primary =  {slice_number=3, Entry count=256(0x100), Entry free=256(0x100)},

         slice_secondary = {slice_number=4}

         group_status={prio_min=1, prio_max=2147483647, entries_total=768, entries_free=768,

                       counters_total=38912, counters_free=30208, meters_total=2048, meters_free=1792}


-----------------------------------------------------------------------------------------------
After load the acl.jason file
------------------------------------------------------------------------------------------------
drivshell>fp show
fp show


FP: Range ID=1, flag=0x1, min=34048, max=35072, hw_index=0(0), style=BCM56504

FP:	unit 0:

PIPELINE STAGE INGRESS

FP:	      :tcam_sz=6144(0x1800), tcam_slices=12, tcam_ext_numb=0,

PIPELINE STAGE EGRESS

FP:	      :tcam_sz=1024(0x400), tcam_slices=4, tcam_ext_numb=0,

PIPELINE STAGE LOOKUP

FP:	      :tcam_sz=1024(0x400), tcam_slices=4, tcam_ext_numb=0,

GID          6: gid=0x6, instance=0 mode=Double, stage=Ingress lookup=Enabled, ActionResId={-1}, pbmp={0x0000000000000000000000000000000444444441111111104444444422222223}

         qset={SrcIp, DstIp, InPorts, RangeCheck, L4SrcPort, L4DstPort, EtherType, IpProtocol, TcpControl, IpType, Stage, StageIngress, IcmpTypeCode},

         Qualifiers in Part-0: {SrcIp->InPorts->RangeCheck->L4SrcPort->EtherType->IpType->IcmpTypeCode},

         Qualifiers in Part-1: {DstIp->RangeCheck->L4DstPort->IpProtocol->TcpControl->IpType},



         group_priority= 100

         slice_primary =  {slice_number=3, Entry count=256(0x100), Entry free=254(0xfe)},

         slice_secondary = {slice_number=4}

         group_status={prio_min=1, prio_max=2147483647, entries_total=768, entries_free=766,

                       counters_total=38912, counters_free=30202, meters_total=2048, meters_free=1792}

EID 0x00000098: gid=0x6,

         slice=3, slice_idx=0x2, part =0, prio=0x1, flags=0x10602, Installed, Enabled, color_indep=1

         slice=4, slice_idx=0x2, part =1, prio=0x1, flags=0x10604, Installed, Enabled, color_indep=1



 InPorts 

    DATA=0x0000000000000000000000000000000000000000000000002222000000000000

    MASK=0x0000000000000000000000000000000088888888444444442222222222222222

 EtherType 

    Part:0 Offset0: 100 Width0:   4 

    Part:0 Offset1: 104 Width1:   4 

    Part:0 Offset2: 108 Width2:   4 

    Part:0 Offset3: 112 Width3:   4 

    DATA=0x00000800 

    MASK=0x0000ffff 

         action={act=Drop, param0=0(0), param1=0(0), param2=0(0), param3=0(0)}

         policer=

         statistics={stat id 134  slice = 9 idx=4 entries=3}{Bytes}{Packets}{GreenBytes}{GreenPackets}{YellowBytes}{YellowPackets}{RedBytes}{RedPackets}

EID 0x00000099: gid=0x6,

         slice=3, slice_idx=0, part =0, prio=0x270f, flags=0x10602, Installed, Enabled, color_indep=1

         slice=4, slice_idx=0, part =1, prio=0x270f, flags=0x10604, Installed, Enabled, color_indep=1



 InPorts 

    DATA=0x0000000000000000000000000000000000000000000000002222000000000000

    MASK=0x0000000000000000000000000000000088888888444444442222222222222222

 EtherType 

    Part:0 Offset0: 100 Width0:   4 

    Part:0 Offset1: 104 Width1:   4 

    Part:0 Offset2: 108 Width2:   4 

    Part:0 Offset3: 112 Width3:   4 

    DATA=0x00000800 

    MASK=0x0000ffff 

         action={act=DropCancel, param0=0(0), param1=0(0), param2=0(0), param3=0(0)}

         policer=

         statistics={stat id 135  slice = 9 idx=12 entries=3}{Bytes}{Packets}{GreenBytes}{GreenPackets}{YellowBytes}{YellowPackets}{RedBytes}{RedPackets}
